### ISSUE TITLE
Can't authenticate with MySQL database

### ISSUE THREAD

**Issue by yiqiqq** [erlio/vernemq#797] opened 2018-08-14 09:11 UTC
### Environment

- VerneMQ Version: vernemq-1.4.1-1.el7.centos.x86_64
- OS: CentOS   Linux 3.10.0-693.2.2.el7.x86_64
- Erlang/OTP version (if building from source):

### Expected behavior
```
INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', PASSWORD('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
```

I want to publish a message like that:

`mosquitto_pub  -h 127.0.0.1 -t 'a/b/c' -m 'hello world' -u 'test-user' -P '123' -i 'test-client'
`
but it failed.
```
2018-08-14 17:10:14.430 [error] <0.540.0>@vmq_mqtt_fsm:auth_on_publish:702 can't auth publish [<<"test-user">>,{[],<<"test-client">>},0,[<<"a">>,<<"b">>,<<"c">>],<<"hello world">>,false] due to no_matching_hook_found
2018-08-14 17:10:14.430 [warning] <0.540.0>@vmq_ranch:teardown:138 session stopped abnormally due to 'publish_not_authorized_3_1_1'
```

- Please describe the expected behaviour.

### Actual behaviour

2018-08-14 17:10:14.430 [error] <0.540.0>@vmq_mqtt_fsm:auth_on_publish:702 can't auth publish [<<"test-user">>,{[],<<"test-client">>},0,[<<"a">>,<<"b">>,<<"c">>],<<"hello world">>,false] due to no_matching_hook_found
2018-08-14 17:10:14.430 [warning] <0.540.0>@vmq_ranch:teardown:138 session stopped abnormally due to 'publish_not_authorized_3_1_1'
```

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment] 2018-08-15 08:45
@yiqiqq thanks, just to make sure quickly:
have you turned vmq_diversity on?
`plugins.vmq_diversity = on`

have you turned file auth off?
`plugins.vmq_passwd = off`
`plugins.vmq_acl = off`

**Comment by yiqiqq** [comment] 2018-08-16 02:43
yes

```
## Lua based plugins.
##
## Default: off
##
## Acceptable values:
##   - on or off
plugins.vmq_diversity = on

```
```
##
## Acceptable values:
##   - on or off
plugins.vmq_passwd = off

## File based authorization plugin.
##
## Default: on
##
## Acceptable values:
##   - on or off
plugins.vmq_acl = off

```

**Comment by larshesel** [comment] 2018-08-16 07:09
Hi, 

Have you configured the following with the values for your database: 

```
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 127.0.0.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = vernemq
vmq_diversity.mysql.password = vernemq
vmq_diversity.mysql.database = vernemq_db
```

Note the first line `vmq_diversity.auth_mysql.enabled = on` which is also required to enable the mysql driver in the `vmq_diversity` plugin. See also http://vernemq.com/docs/configuration/db-auth.html#mysql

**Comment by yiqiqq** [comment] 2018-08-16 07:38
```
##
## Acceptable values:
##   - on or off
vmq_diversity.auth_mysql.enabled = on

##
## Default: localhost
##
## Acceptable values:
##   - text
vmq_diversity.mysql.host = ( db host)

##
## Default: 3306
##
## Acceptable values:
##   - an integer
vmq_diversity.mysql.port = 3306

##
## Default: root
##
## Acceptable values:
##   - text
vmq_diversity.mysql.user = vernemq

##
## Default: password
##
## Acceptable values:
##   - text
vmq_diversity.mysql.password =(passwd)

##
## Default: vernemq_db
##
## Acceptable values:
##   - text
vmq_diversity.mysql.database = vernemq_db
```

**Comment by yiqiqq** [comment] 2018-08-16 07:39
I  follow []( http://vernemq.com/docs/configuration/db-auth.html#mysql)  step by step

**Comment by larshesel** [comment] 2018-08-16 07:47
This may be a silly question, but did you restart VerneMQ after changing the configuration file? What's the output of `vmq-admin plugin show`? and what's the output of `vmq-admin script show`?

**Comment by yiqiqq** [comment] 2018-08-16 07:50
[root@cpay-new-server1 ~]# vmq-admin plugin show
+-------------+-----------+-------+-----+
|   Plugin    |   Type    |Hook(s)|M:F/A|
+-------------+-----------+-------+-----+
|vmq_plumtree |application|       |     |
|vmq_diversity|application|       |     |
+-------------+-----------+-------+-----+


[root@cpay-new-server1 ~]# vmq-admin script show
+-------------------------------+
|            script             |
+-------------------------------+
|/usr/share/vernemq/lua/init.lua|
+-------------------------------+

restart for many times

[root@cpay-new-server1 ~]# service vernemq restart
Restarting vernemq (via systemctl):  [  OK  ]

**Comment by yiqiqq** [comment] 2018-08-16 07:56
2018-08-16 15:50:25.064 [error] <0.357.0>@vmq_diversity_app:load_script**:96 could not load script "/usr/share/vernemq/lua/auth/mysql.lua" due to {{'EXIT',{{badmatch,{error,{normal,{child,undefined,{vmq_diversity_script_state,1},{vmq_diversity_script_state,start_link,**[1,"/usr/share/vernemq/lua/auth/mysql.lua"]},permanent,5000,worker,[vmq_diversity_script_state]}}}},[{vmq_diversity_script_sup_sup,setup_lua_states,2,[{file,"/opt/vernemq/distdir/BUILD/1.4.1/_build/default/lib/vmq_diversity/src/vmq_diversity_script_sup_sup.erl"},{line,97}]},{vmq_diversity_script_sup_sup,start_link,1,[{file,"/opt/vernemq/distdir/BUILD/1.4.1/_build/default/lib/vmq_diversity/src/vmq_diversity_script_sup_sup.erl"},{line,45}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}},{child,undefined,{vmq_diversity_script_sup_sup,"/usr/share/vernemq/lua/auth/mysql.lua"},{vmq_diversity_script_sup_sup,start_link,["/usr/share/vernemq/lua/auth/mysql.lua"]},permanent,5000,supervisor,[vmq_diversity_script_sup_sup]}}

**Comment by yiqiqq** [comment] 2018-08-16 07:59
**could not load script "/usr/share/vernemq/lua/auth/mysql.lua"   ,**

**Comment by ioolkos** [comment] 2018-08-16 12:09
The initial issue is then explained by the fact that the mysql.lua isn't loaded at all. vmq_diversity seems loaded, path & permission seem ok, it also seems to be the original mysql.lua script.

I don't understand it currently. Is there anything you think that could be special with your setup?

**Comment by yiqiqq** [comment] 2018-08-17 06:28
about  " could not load script "/usr/share/vernemq/lua/auth/mysql.lua" " 

I found why.  my db is on aliyun  RDS,  and  the password in the config file is wrong.   thank you for all the responses。

now  the error log is
```

`2018-08-17 14:21:11.183 [error] <0.6304.0>@vmq_mqtt_fsm:auth_on_publish:702 can't auth publish [<<"test-user">>,{[],<<"test-client">>},0,[<<"a">>,<<"b">>,<<"c">>],<<"hello world">>,false] due to error
2018-08-17 14:21:11.184 [warning] <0.6304.0>@vmq_ranch:teardown:138 session stopped abnormally due to 'publish_not_authorized_3_1_1'`
```

```
INSERT INTO vmq_auth_acl
   (mountpoint, client_id, username,
    password, publish_acl, subscribe_acl)
 VALUES
   ('', 'test-client', 'test-user',
    PASSWORD('123'), '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]',
                     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
```

`
`mosquitto_pub -h 127.0.0.1 -t 'a/b/c' -m 'hello world' -u 'test-user' -P '123' -i 'test-client'``


what is  the **mountpoint**  mean ?     why publish to topic  a/b/c is not accepted?

**Comment by larshesel** [comment] 2018-08-17 07:56
> I found why. my db is on aliyun RDS, and the password in the config file is wrong. thank you for all the responses。

Ok, that's great - I'll see if we can't make the error message better. `could not load script ...` isn't very helpful in that case. 

Regarding it not being accepted I'm not sure what the problem is - I don't seem to be able to reproduce the problem here. Can you enable extra logging on the database to see which queries are being executed on the database and see if everything looks ok? Could it be you're connecting to the wrong database in MySQL?

**Comment by larshesel** [comment] 2018-08-17 08:43
I was just playing around a bit with this - first setting the wrong password then the wrong database and in both cases I got an error:

```
2018-08-17 10:41:00.165 [error] <0.366.0>@vmq_diversity_script_state:init:96 can't load script "./share/lua/auth/mysql.lua" due to {throw,{auth_fail,{error_packet,2,1045,<<"28000">>,"Access denied for user 'root'@'localhost' (using password: YES)"}}}
```

and 

```
2018-08-17 10:40:17.499 [error] <0.366.0>@vmq_diversity_script_state:init:96 can't load script "./share/lua/auth/mysql.lua" due to {throw,{failed_to_set_database,"Unknown database 'vernemq_dbx'"}}
```

So the information is there, it might just be earlier in the log file.

**Comment by larshesel** [comment] 2018-08-17 08:45
Btw the mountpoint is a multi tenancy feature which can be used to serve different topic trees. Each listener can have it's own mountpoint. The default is the empty string.

**Comment by dergraf** [comment] 2018-08-24 11:26
Closing for now. Please reopen if you need more information. 
In any case we know that Lua errors could be better handled, and we're waiting for some improvements on the Erlang Lua interpreter itself see https://github.com/rvirding/luerl/issues/64.

**Closed by dergraf** 2018-08-24 11:26 UTC
