### ISSUE TITLE
Cluster login error

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#180] opened 2016-08-05 06:55 UTC
Hi!
When the node not join another node, the client "12" can login Node82 and Node83.
And after join, the client "12" can not login Node82 and Node83. And the other clients can login.
It seems that if the same client login the two nodes before join, it can not login after join.
```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster join discovery-node='VerneMQ@192.168.3.83'
Done
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.82| true  |
|VerneMQ@192.168.3.83| true  |
+--------------------+-------+

root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# tail -f log/console.log 
2016-08-05 14:46:20.981 [info] <0.645.0>@hisir_plugin:auth_on_publish:62 hisir_plugin auth_on_publish, UserName:<<"fuck">>, ClientId:<<"12">>, QoS:1, Topic:[<<"chat">>,<<"simple">>]
2016-08-05 14:46:20.981 [info] <0.645.0>@hisir_plugin:on_publish:143 hisir_plugin on_publish, UserName:<<"fuck">>, ClientId:<<"12">>, Topic:[<<"chat">>,<<"simple">>]
2016-08-05 14:46:22.308 [info] <0.600.0>@hisir_plugin:on_client_offline:147 hisir_plugin, on_client_offline, ClientId:<<"12">>
2016-08-05 14:47:31.293 [info] <0.670.0>@plumtree_peer_service:attempt_join:50 Sent join request to: 'VerneMQ@192.168.3.83'
2016-08-05 14:47:31.296 [info] <0.108.0>@plumtree_peer_service_manager:write_state_to_disk:100 writing state {[{[{actor,<<0,62,39,245,47,232,211,23,55,154,170,219,228,198,87,154,11,236,231,131>>}],1},{[{actor,<<70,4,219,47,85,131,22,203,114,47,254,113,199,166,63,38,99,101,43,10>>}],1}],{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[['VerneMQ@192.168.3.82',{[{actor,<<70,4,219,47,85,131,22,203,114,47,254,113,199,166,63,38,99,101,43,10>>}],1}]],[['VerneMQ@192.168.3.83',{[{actor,<<0,62,39,245,47,232,211,23,55,154,170,219,228,198,87,154,11,236,231,131>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,1,118,120,1,203,96,206,97,96,96,96,202,96,2,81,140,25,76,41,12,172,137,201,37,249,69,185,64,174,8,131,157,250,87,253,23,151,197,205,103,173,186,253,228,88,248,44,238,55,207,155,179,18,129,170,176,41,118,99,185,173,31,218,44,118,186,72,255,95,225,241,101,246,106,201,169,218,92,64,197,89,25,156,41,12,44,41,153,201,37,137,76,137,2,64,200,145,24,144,104,144,33,144,133,6,50,24,65,98,96,131,193,46,74,97,16,9,75,45,202,75,245,13,116,48,180,52,210,51,52,179,208,51,214,179,48,34,205,110,130,230,25,99,55,15,135,199,81,157,140,240,24,3,97,143,161,106,5,0,9,170,112,187>>
2016-08-05 14:47:49.192 [info] <0.699.0>@hisir_plugin:auth_on_register:23 hisir_plugin auth_on_register, ClientId:<<"12">>, UserName:<<"fuck">>, Password:<<"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMiIsInN1YiI6ImZ1Y2siLCJleHAiOjE0NzAzODAwMjl9.Wrz4YKUxlkRzrJRwYPF1AZZPdPuA39iXf3mJsmbIPzQ">>
2016-08-05 14:47:49.548 [warning] <0.224.0>@vmq_reg_mgr:initiate_queue_migration:234 more than one remote nodes found for migrating queue[<0.600.0>] for subscriber {[],<<"12">>}, use 'VerneMQ@192.168.3.83'
2016-08-05 14:47:49.550 [info] <0.699.0>@hisir_plugin:on_register:44 hisir_plugin on_register: {{192,168,3,236},36534}, {[],<<"12">>}, <<"fuck">>
2016-08-05 14:47:49.550 [info] <0.600.0>@hisir_plugin:on_client_offline:147 hisir_plugin, on_client_offline, ClientId:<<"12">>
2016-08-05 14:47:59.728 [info] <0.714.0>@hisir_plugin:auth_on_register:23 hisir_plugin auth_on_register, ClientId:<<"12">>, UserName:<<"fuck">>, Password:<<"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMiIsInN1YiI6ImZ1Y2siLCJleHAiOjE0NzAzODAwMzl9.HoHqHwB3ez_iUgeO_cOT3vLjpQaxO3jEtatQZnHoIGs">>
```
```
2016-08-05 14:47:49.548 [warning] <0.224.0>@vmq_reg_mgr:initiate_queue_migration:234 more than one remote nodes found for migrating queue[<0.600.0>] for subscriber {[],<<"12">>}, use 'VerneMQ@192.168.3.83'
```
Then the client can not login:
```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.37.0>]: connecting to 192.168.3.82:1883
[info] [Client <0.37.0>] connected with 192.168.3.82:1883

1> 
1> [error] [Client <0.37.0>] CONNACK Timeout!
```

**Comment by dcy** [comment] 2016-08-05 07:19
It can confirm:
Before join, the same client login the two nodes, then join the nodes, the same client can not login each node any more, the other clients can login.

**Comment by ioolkos** [comment] 2016-08-05 07:25
OK, let's see. How do you connect the problematic client in the first place (clean_session = false?).
What is the configuration for allow_multiple_sessions?

**Comment by dcy** [comment] 2016-08-05 07:26
clean_session = false and allow_multiple_sessions = off

**Comment by ioolkos** [comment] 2016-08-05 13:50
We've not been able to reproduce this in a similar way. But there is a potential for errors or at least misunderstandings with a situation when 2 'loaded' (non empty) brokers are clustered. It basically corresponds to a netsplit situation.

We still need to look further into this, apologies for the delay.

**Comment by dcy** [comment] 2016-08-06 06:57
@ioolkos You can reproduce like this(I can reproduce every time):
Two independent brokers, ```VerneMQ@192.168.3.82``` and ```VerneMQ@192.168.3.83```,
Before cluster, use the same Client(client_id="1") login ```VerneMQ@192.168.3.82``` and ```VerneMQ@192.168.3.83```.
Then join the two nodes to cluster, ```./bin/vmq-admin cluster join discovery-node='VerneMQ@192.168.3.83'```, and use the same Client(client_id="1") to login the two nodes, it can not login anymore.

**Comment by ioolkos** [comment] 2016-08-06 09:07
Allright, thanks, I'll try that later today.

Btw, what is the MQTT client library/tool your using?

**Comment by dcy** [comment] 2016-08-06 09:49
I use [emqttc](https://github.com/emqtt/emqttc), I think mosquito_sub is the same problem.

**Comment by ioolkos** [comment] 2016-08-06 13:56
As mosquitto_sub is a reconnecting client, the 2 identical subscribers will just race each other after the cluster join (at least that's what I see).

When I then try to login with a third client instance, the race continues, but I get 'queue drain' errors in addition.
VerneMQ will not stop Clients racing each other, so that's one thing to avoid client side.

**Comment by dcy** [comment] 2016-08-08 01:50
@ioolkos Didn't you reproduce the error?

**Comment by ioolkos** [comment] 2016-08-08 06:53
I did not reproduce the exact error (but only used mosquitto_sub), but yes: there is an issue with the third login. We should just have 3 racing clients at this point, but the third runs into queue drain problems.

Trying to address & do more thinking about it here: https://github.com/erlio/vmq_server/pull/86

**Comment by dcy** [comment] 2016-08-09 04:18
Hi! @ioolkos @larshesel You can use https://github.com/dcy/testc to reproduce this issue.
1. Tow new independent nodes: VerneMQ@192.168.3.82 VerneMQ@192.168.3.83, not cluster, allow_anoymous = on
2. use [testc](https://github.com/dcy/testc), use same client_id login VerneMQ@192.168.3.82 and VerneMQ@192.168.3.83
```
dcy@dcy-dcy:~/app/testc$ python start.py 
Hosts: 192.168.3.82
uid: test
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.34.0>]: connecting to 192.168.3.82:1883
[info] [Client <0.34.0>] connected with 192.168.3.82:1883
[info] [Client <0.34.0>] RECV: CONNACK_ACCEPT
Client <0.34.0> is connected
Message from hello: <<"Hello World">>

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cdcy@dcy-dcy:~/app/testc$ python start.py 
Hosts: 192.168.3.83
uid: test
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.34.0>]: connecting to 192.168.3.83:1883
[info] [Client <0.34.0>] connected with 192.168.3.83:1883
[info] [Client <0.34.0>] RECV: CONNACK_ACCEPT
Client <0.34.0> is connected
Message from hello: <<"Hello World">>

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cdcy@dcy-dcy:~/app/testc$ 

```
Nothing problem now.
3. Cluster the two nodes,
```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster join discovery-node='VerneMQ@192.168.3.83'
Done
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.82| true  |
|VerneMQ@192.168.3.83| true  |
+--------------------+-------+

root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# 

```
4. Use [testc](https://github.com/dcy/testc) to login the nodes, the same client can not login anymore, but the other clients can login
```
dcy@dcy-dcy:~/app/testc$ python start.py 
Hosts: 192.168.3.82
uid: test
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.34.0>]: connecting to 192.168.3.82:1883
[info] [Client <0.34.0>] connected with 192.168.3.82:1883
[info] [Client <0.34.0>] RECV: CONNACK_ACCEPT

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cdcy@dcy-dcy:~/app/testc$ python start.py 
Hosts: 192.168.3.83
uid: test
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.34.0>]: connecting to 192.168.3.83:1883
[info] [Client <0.34.0>] connected with 192.168.3.83:1883

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cdcy@dcy-dcy:~/app/testc$ python start.py 
Hosts: 192.168.3.83
uid: test1
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> [info] [Client <0.34.0>]: connecting to 192.168.3.83:1883
[info] [Client <0.34.0>] connected with 192.168.3.83:1883
[info] [Client <0.34.0>] RECV: CONNACK_ACCEPT
Client <0.34.0> is connected
Message from hello: <<"Hello World">>

```

**Comment by ioolkos** [comment] 2016-08-11 08:42
Hi @dcy,
thank you for your patience!

I think we have this issue fixed in this PR: https://github.com/erlio/vmq_server/pull/86
(feel free to test). it's not yet merged due to the travis build error.

But with this it seems I can safely connect 3 clean_session=false clients with the same clientid sequentially, while doing a cluster join after 2 connects.

Thanks again for your effort & reporting!

**Comment by dcy** [comment] 2016-08-18 06:19
@ioolkos When can i test this issue, i found another problem today. The client(client_id is "3") login(already login) and then will disconnect by tcp_closed. The other clients are fine.
The log of VerneMQ:
```
2016-08-18 14:11:52.454 [info] <0.15356.0>@hisir_plugin:auth_on_register:23 hisir_plugin auth_on_register, ClientId:<<"3">>, UserName:<<"fuck">>, Password:<<"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzIiwiZXhwIjoxNDcxNTAxMDcyLCJmaXJzdCI6MSwidWRpZCI6WzExNSwxMDAsMTAyLDExNSwxMDAsMTAyLDExNSwxMDAsMTAyXX0.couB3H9GmEEbjvhZ8Au6bJBtjTHbfcIc4P0wrfRUYK4">>
2016-08-18 14:11:53.062 [info] <0.15356.0>@hisir_plugin:on_register:44 hisir_plugin on_register: {{59,41,41,26},46182}, {[],<<"3">>}, <<"fuck">>
2016-08-18 14:11:53.074 [info] <0.15356.0>@hisir_plugin:auth_on_subscribe:51 hisir_plugin auth_on_subscribe, UserName:<<"fuck">>, ClientId:<<"3">>, Topics:[{[<<"notify">>,<<"all">>],1},{[<<"notify">>,<<"3">>],1},{[<<"chat">>,<<"3">>],1}]
2016-08-18 14:11:53.079 [info] <0.15356.0>@hisir_plugin:auth_on_publish:62 hisir_plugin auth_on_publish, UserName:<<"fuck">>, ClientId:<<"3">>, QoS:1, Topic:[<<"chat">>,<<"1">>]
2016-08-18 14:11:53.080 [info] <0.15356.0>@hisir_plugin:on_publish:143 hisir_plugin on_publish, UserName:<<"fuck">>, ClientId:<<"3">>, Topic:[<<"chat">>,<<"1">>]
2016-08-18 14:11:53.080 [info] <0.15356.0>@hisir_plugin:auth_on_publish:62 hisir_plugin auth_on_publish, UserName:<<"fuck">>, ClientId:<<"3">>, QoS:1, Topic:[<<"chat">>,<<"simple">>]
2016-08-18 14:11:53.080 [info] <0.15356.0>@hisir_plugin:on_publish:143 hisir_plugin on_publish, UserName:<<"fuck">>, ClientId:<<"3">>, Topic:[<<"chat">>,<<"simple">>]
2016-08-18 14:11:53.495 [warning] <0.250.0>@vmq_reg_mgr:initiate_queue_migration:234 more than one remote nodes found for migrating queue[<0.15359.0>] for subscriber {[],<<"3">>}, use 'VerneMQ@58.64.196.109'
2016-08-18 14:11:53.495 [info] <0.15359.0>@hisir_plugin:on_client_offline:147 hisir_plugin, on_client_offline, ClientId:<<"3">>
```
The client:
```
Eshell V7.3  (abort with ^G)
1> [info] [Client <0.37.0>]: connecting to 58.64.196.110:1883
[info] [Client <0.37.0>] connected with 58.64.196.110:1883
******CONNACK, code: 0
[info] [Client <0.37.0>] RECV: CONNACK_ACCEPT
Client <0.37.0> is connected
[warning] [Client <0.37.0>] Connection lost for: tcp_closed
[info] [Client <0.37.0>] try reconnecting...
Client <0.37.0> is disconnected
```

Maybe it is the same problem:
```
2016-08-18 14:11:53.495 [warning] <0.250.0>@vmq_reg_mgr:initiate_queue_migration:234 more than one remote nodes found for migrating queue[<0.15359.0>] for subscriber {[],<<"3">>}, use 'VerneMQ@58.64.196.109'
```
Could you merge it and i can use the new code to test it.
This problem is serious because the client can not work any more.

**Comment by ioolkos** [comment] 2016-08-18 06:46
Thanks @dcy. This is the same problem (field), I think.

Unfortunately PR #86 https://github.com/erlio/vmq_server/pull/86 is not yet ready to merge.
cc @dergraf

**Comment by larshesel** [comment] 2016-08-24 13:20
We just merged erlio/vmq_server#86. Any feedback would be very much appreciated and if you still experience this issue please reopen the issue.

**Closed by larshesel** 2016-08-24 13:20 UTC

**Comment by dcy** [comment] 2016-08-29 06:28
Hi! @larshesel .
I updated new code and use [testc](https://github.com/dcy/testc) test it.
The same client first login after join will be "tcp_closed". the second login will be fine, but VerneMQ will add an error log.
The VerneMQ log:
```
2016-08-29 14:16:45.003 [info] <0.308.0>@plumtree_peer_service:attempt_join:50 Sent join request to: 'VerneMQ@192.168.3.83'
2016-08-29 14:16:45.006 [info] <0.116.0>@plumtree_peer_service_manager:write_state_to_disk:100 writing state {[{[{actor,<<162,97,202,14,15,162,21,106,156,189,136,60,112,250,197,139,103,113,97,70>>}],1},{[{actor,<<184,21,206,5,69,118,169,184,186,104,178,224,204,230,192,242,130,72,143,205>>}],1}],{dict,2,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[['VerneMQ@192.168.3.82',{[{actor,<<184,21,206,5,69,118,169,184,186,104,178,224,204,230,192,242,130,72,143,205>>}],1}]],[['VerneMQ@192.168.3.83',{[{actor,<<162,97,202,14,15,162,21,106,156,189,136,60,112,250,197,139,103,113,97,70>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,1,118,120,1,203,96,206,97,96,96,96,202,96,2,81,140,25,76,41,12,172,137,201,37,249,69,185,64,174,200,162,196,83,124,252,139,68,179,230,236,237,176,41,248,117,180,59,189,48,209,45,43,17,168,10,155,226,29,162,231,88,93,203,86,238,216,149,177,233,193,153,103,7,62,53,121,244,159,5,42,206,202,224,76,97,96,73,201,76,46,73,100,74,20,0,66,142,196,128,68,131,12,129,44,52,144,193,8,18,3,27,12,118,81,10,131,72,88,106,81,94,170,111,160,131,161,165,145,158,161,153,133,158,177,158,133,17,105,118,19,52,207,24,187,121,56,60,142,234,100,132,199,24,8,123,12,85,43,0,30,115,118,63>>
2016-08-29 14:16:48.048 [info] <0.314.0>@plumtree_metadata_exchange_fsm:exchange:160 completed metadata exchange with 'VerneMQ@192.168.3.83'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
2016-08-29 14:19:14.295 [error] <0.359.0>@vmq_queue:drain:335 got unknown sync event in drain state {migrate,<9228.488.0>}
```

**Comment by larshesel** [comment] 2016-09-05 07:49
Hi @dcy I can't reproduce the "tcp_closed" issue on first login after the node join - if you are still able to please open a new issue. I do see the error log and we should probably fix that or tone it down.
