### ISSUE TITLE
Listing down all open sessions

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#520] opened 2017-10-09 10:41 UTC
### Environment

- VerneMQ Version: 1.1.0
- OS: ubuntu

I've been trying to fetch the list of all open sessions on a vernemq-node using the following command:
sudo vmq-admin session show

It lists down a default 100. When I tried to increase the limit, I get the following error:
sudo vmq-admin session show --limit=400

RPC to 'VerneMQ@127.0.0.1' failed: {'EXIT',
                                    {function_clause,
                                     [{lists,zip,
                                       [[6],[]],
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},
                                      {lists,zip,2,
                                       [{file,"lists.erl"},{line,387}]},
                                      {clique_table,'-max_widths/1-fun-0-',2,
                                       [{file,
                                         "/opt/vernemq/distdir/1.1.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,227}]},
                                      {lists,foldl,3,
                                       [{file,"lists.erl"},{line,1263}]},
                                      {clique_table,get_field_widths,3,
                                       [{file,
                                         "/opt/vernemq/distdir/1.1.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,103}]},
                                      {clique_table,autosize_create_table,3,
                                       [{file,
                                         "/opt/vernemq/distdir/1.1.0/_build/default/lib/clique/src/clique_table.erl"},
                                        {line,72}]},
                                      {clique_human_writer,write_table,1,
                                       [{file,
                                         "/opt/vernemq/distdir/1.1.0/_build/default/lib/clique/src/clique_human_writer.erl"},
                                        {line,67}]}]}}

**Comment by larshesel** [comment] 2017-10-10 06:48
Interesting. Is this reproducable every-time you do this with `--limit=400`?

**Comment by odx-tech** [comment] 2017-10-10 06:48
Yes .

**Comment by larshesel** [comment] 2017-10-10 07:37
I just tried with 500 clients connected (no subscriptions) and `--limit=400` and couldn't reproduce it. I'm using 1.2.0  but I don't think that should really matter.

Could you describe your setup more in detail? I'm sure it's a bug, but since I couldn't reproduce this right away there must be something about the clients you've connected that's different than my stock setup, so any information might be helpful putting us on the right track.

**Comment by odx-tech** [comment] 2017-10-11 03:56
So we do not have any subscriptions as well. We have about 3-4k thousand clients connected who are publishing data which is being consumed via webhooks. There is no cluster setup as well.  We have two nodes from which the client can connect to - and each of them are independent. 

Please let me know if you need anything else to debug the same.

**Comment by larshesel** [comment] 2017-12-05 09:30
Is this still an issue? If it is, can you tell us if there is anything in the logs related to when you run the command in the cli? Note we did a number of fixes to the `vmq-admin session show` command in VerneMQ 1.2.2, so it would probably be good to upgrade to that version to get those fixes.

**Comment by larshesel** [comment] 2017-12-19 10:20
Closing this for now.

**Closed by larshesel** 2017-12-19 10:20 UTC
