### ISSUE TITLE
receive message from other users

### ISSUE THREAD

**Issue by ramarro123** [erlio/vernemq#473] opened 2017-08-03 10:37 UTC
hello,

it seems that i am unable to configure vernemq  :)
i am using postgres as a backend for auth, and i add 2 users

```

"";"root";"root";"blabla";"[{"pattern": "#"}]";"[{"pattern": "#"}]"
"";"rama";"rama";"blabla";"[{"pattern": "%u/#"}]";"[{"pattern": "%u/#"}]"

```

i can login without problem with mosquitto_sub/pub, mqttjs, mqttspy

now, if i send a msg from test with
test/device/1 -> "msg"
the other session logged with test, receive the message (hurray!)

if i send the same msg with root, the other session, logged with test, doesn't receive anything.

it's that correct? shouldn't i be able to get all messages from all users if i am allowed to subscribe to a certain topic?

**Comment by ioolkos** [comment] 2017-08-03 13:52
Hi @ramarro123 
can you give me your example as full mosquitto_sub/pub commands?

**Comment by ramarro123** [comment] 2017-08-03 14:25
mosquitto_sub -i rama -u rama -P x -t "rama/device/1"
mosquitto_pub -i root -u root -P x -t "rama/device/1" -m "blue"

**Comment by ioolkos** [comment] 2017-08-03 14:41
Thanks, I wanted to make sure the topics are clear. This should work!
I guess you have taken the steps described here:
https://vernemq.com/docs/configuration/db-auth.html#postgresql

But I don't see where the problem is right now! :) @dergraf do you?

**Comment by ramarro123** [comment] 2017-08-03 14:44
absolutely, followed the guide. also since the guide it's for auth only, and i can login without exception, i guess that's working as expected. if i try with a non-present-on-db user i got

Connection Refused: not authorised.
Error: The connection was refused.

**Comment by ioolkos** [comment] 2017-08-03 14:51
jep.
do the mosquitto commands tell you more with the '-d' option ? and do you see anything in your VerneMQ logs?

**Comment by dergraf** [comment] 2017-08-03 17:31
@ramarro123 used the exact same config like you and did a

    mosquitto_sub -i rama -u rama -P x -t "rama/device/1"
    mosquitto_pub -i root -u root -P x -t "rama/device/1" -m "blue"

and the subscriber `rama` received the message `blue`, like expected, right?

**Comment by ramarro123** [comment] 2017-08-03 20:32
actually the problem in my scenario it's that rama doesn't receive "blue" :)
tomorrow i'll try to do the -d options and send it back

**Comment by larshesel** [comment] 2017-09-19 06:32
Since we didn't hear back I'm closing this.

**Closed by larshesel** 2017-09-19 06:32 UTC
