### ISSUE TITLE
MQTT Bridge configuration :: Error running translation for vmq_bridge.config

### ISSUE THREAD

**Issue by ywadi** [erlio/vernemq#280] opened 2017-02-19 10:44 UTC
### Environment

- VerneMQ Version:0.15.3
- OS: UBUNTU Xenial

### Expected behavior

- Configure Bridge to AWS IoT
```
bridge.tcp.br0 = XXXX.iot.eu-west-1.amazonaws.com:8883
bridge.tcp.br0.try_private = off
bridge.tcp.br0.topic.1 = /demo/+ both 1
bridge.tcp.br0.cleansession = on


bridge.ssl.br0.cafile = /etc/vernemq/keys/ca.pem
bridge.ssl.br0.certfile = /etc/vernemq/keys/cert.crt
bridge.ssl.br0.keyfile =  /etc/vernemq/keys/private.pem

bridge.ssl.br0.insecure = off

```

### Actual behaviour

Seems like the issue is with SSL/TLS

```

10:36:19.294 [debug] Running translation for vmq_server.persistent_client_expiration
10:36:19.294 [debug] Running translation for vmq_server.http_modules
10:36:19.294 [debug] Running translation for vmq_server.listeners
10:36:19.343 [debug] Lager installed handler lager_backend_throttle into lager_event
10:36:19.377 [debug] Running translation for vmq_server.tcp_listen_options
10:36:19.378 [error] Error generating configuration in phase apply_translations
10:36:19.378 [error] Error running translation for vmq_bridge.config, [error, {badmatch,
                                                          {["127.0.0.1:1889"],
                                                           [{topics,[]}]}}]

```

**Comment by ioolkos** [comment] 2017-02-19 13:36
Hi @ywadi thanks for using VerneMQ :)

it looks like there is a default bridge configured in your vernemq.conf file (an uncommented line like `vmq_bridge.tcp.br0 = 127.0.0.1:1889` anywhere?)
Can you check for this?

**Comment by ywadi** [comment] 2017-02-19 17:44
Hi, 
Thanks for VerneMQ its great. 
No default configs detected, this is the last test file I ran 

l```
og.console = file
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
leveldb.maximum_memory.percent = 70
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
acl_file = /etc/vernemq/vmq.acl
acl_reload_interval = 10
password_file = /etc/vernemq/vmq.passwd
password_reload_interval = 10
allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
message_size_limit = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 127.0.0.1:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000

bridge.tcp.br0 = a2nsvisrl5qlpw.iot.eu-west-1.amazonaws.com:8883
bridge.tcp.br0.try_private = off
bridge.tcp.br0.topic.1 = /demo/+ both 1
bridge.tcp.br0.cleansession = on

bridge.ssl.br0.cafile = /etc/vernemq/keys/ca.pem
bridge.ssl.br0.certfile = /etc/vernemq/keys/cert.crt
bridge.ssl.br0.keyfile =  /etc/vernemq/keys/private.pem

bridge.ssl.br0.insecure = off
```

**Comment by ioolkos** [comment] 2017-02-19 20:08
I ran a couple of configs against `vernemq config generate -l debug` but no luck. it's strange though, it has to be something simple I'm missing.

@dergraf does this ring a bell somehow?

**Comment by dergraf** [comment] 2017-02-19 21:37
We fixed a bug related to multiple bridge configurations in https://github.com/erlio/vernemq/commit/a57ee22e48b083e5c1cd2fb128a19f90c6d996cb . Can you check with the current nightly build if the problem still exists?

**Comment by ywadi** [comment] 2017-02-19 23:09
@dergraf 
I have tried to do this on the nightly still getting same issue, I used the same config but `bridge` was replaced wtih `vmq_bridge` 

```
vmq_bridge.tcp.br0 = a-------------------0.amazonaws.com:8883
vmq_bridge.tcp.br0.try_private = off
vmq_bridge.tcp.br0.topic.1 = /demo/+ both 1
vmq_bridge.tcp.br0.cleansession = on


vmq_bridge.ssl.br0.cafile = /etc/vernemq/keys/ca.pem
vmq_bridge.ssl.br0.certfile = /etc/vernemq/keys/cert.crt
vmq_bridge.ssl.br0.keyfile =  /etc/vernemq/keys/private.pem

vmq_bridge.ssl.br0.insecure = off
```


```
23:07:25.675 [debug] Running translation for lager.crash_log
23:07:25.675 [debug] Running translation for lager.crash_log_count
23:07:25.675 [debug] "vm_args.+S" in Translations to drop...
23:07:25.675 [debug] "vm_args.+a" in Translations to drop...
23:07:25.675 [debug] "vm_args.+zdbbl" in Translations to drop...
23:07:25.675 [debug] Running translation for riak_sysmon.gc_ms_limit
23:07:25.676 [debug] Running translation for riak_sysmon.schedule_ms_limit
23:07:25.676 [debug] Running translation for riak_sysmon.heap_word_limit
23:07:25.676 [debug] Running translation for eleveldb.delete_threshold
23:07:25.676 [debug] Running translation for eleveldb.tiered_slow_level
23:07:25.677 [error] Error generating configuration in phase apply_translations
23:07:25.677 [error] Error running translation for vmq_bridge.config, [error, {badmatch,
                                                          {["127.0.0.1:1889"],
                                                           [{topics,[]}]}}]
```

**Comment by dergraf** [comment] 2017-02-20 06:28
Is it possible that you are mixing tcp and tls configurations? If you want to use a tls bridge you must define

    vmq_bridge.ssl.br0 = a-------------------0.amazonaws.com:8883
    vmq_bridge.ssl.br0.try_private = off
    vmq_bridge.ssl.br0.topic.1 = /demo/+ both
    vmq_bridge.ssl.br0.cleansession = on 

The tls config isn't part of the tcp bridge, but rather specifies a bridge onits own. Therefore get rid of the tcp config and only use ssl.

**Comment by larshesel** [comment] 2017-02-21 12:00
Hi @ywadi did you resolve this issue? I just tried to reproduce with your config file on master (Nightly) and can't reproduce. I could, however, reproduce it on 0.15.3 but as mentioned we fixed a bug in nightly, so it would be interesting to see your entire config file you used for testing nightly to reproduce this.

I did just find another thing in the `vmq_bridge` config handling where it seems to start default tcp bridges to localhost if even if none are specified. I think this might be related to the problem on 0.15.3 at least. I'll investigate that and report back.

**Comment by ywadi** [comment] 2017-02-21 12:28
@larshesel 
Thanks for looking into this, I am getting kind of lost figuring out whats going on. When I did what @dergraf mentioned it parsed well and passed, the odd thing now is I am not able to actually bridge the data to AWS. It runs on but all my pubs/subs dont do anything at all. I still can not figure out if I am doing something wrong or there is something wrong as the consoles and logs seem clear but data is not passing through

**Comment by larshesel** [comment] 2017-02-21 12:52
What @dergraf said is true - each bridge defintion (in this case `br0`) can only be either `ssl` or `tcp. Not a mix. Looking closer I think this was the main issue and your config as such is OK, on nightly at least.

It's hard to say why the bridge toward AWS is not working - unfortunately the bridge doesn't log a lot of information - a point which is on our todo-list before our upcoming release of VerneMQ 1.0. Due to the lack of info from the bridge, would it be possible for you eliminate AWS connectivity errors by manually publishing messages using `mosquitto_pub` and `mosquitto_sub` or similar tools? Is it possible from the AWS side to see which clients are connected (by client-id or similar) to see if VerneMQ is able to establish a connection?

**Comment by larshesel** [comment] 2017-02-21 13:49
@ywadi I think we have a regression in Nightly where the bridge connections are not properly started. Let me look a bit closer into this before you spend a lot of time debugging.

**Comment by ywadi** [comment] 2017-02-21 16:36
@larshesel ok thanks

**Comment by larshesel** [comment] 2017-02-21 17:20
@ywadi I'll be traveling tomorrow but will be seeing if I can't get this sorted out. Thank you for your patience.

**Comment by larshesel** [comment] 2017-02-21 17:22
Btw - are you in a position to build VerneMQ yourself? If so I'd prepare a special branch for you when I have a fix - otherwise you'd have to wait until it's been reviewed and landed in the nightly build or a proper release.

**Comment by ywadi** [comment] 2017-02-22 09:53
@larshesel no problem, we can wait. If we can support in an means possible let me know.

**Comment by larshesel** [comment] 2017-02-27 08:05
Hi @ywadi we've merged a fix for this and a few other things on master and this should be in the nightly build if you'd like to test it out. Our latest changes to the `vernemq.conf` file had broken the bridge config so at least that should be fixed and my ad-hoc tests showed the bridge to be working now - so I hope it will for you as well. We'll likely do a tagged release tomorrow.

**Closed by larshesel** 2017-02-27 08:05 UTC

**Comment by larshesel** [comment] 2017-02-27 08:07
Let us know if you have any further issues! :)

**Comment by oladehin** [comment] 2017-02-28 22:14
HI @larshesel  I was following this ticket as I had a similar use case connecting verne to AWS IoT. I tried building from source as well as the nightly build and I get an error message: <server_not_found> 
Digging through the code, the error happens during the connect phase and "connect_on_error" code.

My conf file looks like this on the bridge portions:

vmq_bridge.ssl.br0 = aXXXXXXXXXXXX.iot.us-east-1.amazonaws.com:8883
vmq_bridge.ssl.br0.try_private = off
vmq_bridge.ssl.br0.topic.1 = /demo/+ in 1
vmq_bridge.ssl.br0.cleansession = on

vmq_bridge.ssl.br0.cafile = /etc/vernemq/cert/rootCA.pem
vmq_bridge.ssl.br0.certfile = /etc/vernemq/cert/cert.crt
vmq_bridge.ssl.br0.keyfile =  /etc/vernemq/cert/privKey.pem
vmq_bridge.ssl.br0.insecure = off

I was curious if you were able to get this to work against an ssl endpoint? And if you could share what your conf looked like during your test? This still wasn't working for me so possibly I'm missing something. 

Thanks!

**Comment by larshesel** [comment] 2017-03-01 07:12
hi @oladehin the error message there is somewhat unfortunate as it doesn't necessarily mean 'server not found' but could be logged due to any number of connectivity reasons (including wrongly configured SSL/TLS). 

But just to check - yesterday the whole of US-EAST-1 amazon setup was hit by an outage - could it be that was what you experienced? It looks like you're tried to connect to an iot instance there. If that was the cause it should be fixed by now.

If that was not the case, I'll try and do a test with SSL to see if I can reproduce.

**Comment by oladehin** [comment] 2017-03-01 16:06
Hi @larshesel unfortunately I did these tests over the weekend and got these issues. I also tried it against multiple regions with the same issue. 

I could imagine it is a TLS/SSL connection issue. Two quick questions:

In the configuration, AWS IoT expects a server-cert: vmq_bridge.ssl.br0.cafile = /etc/vernemq/cert/rootCA.pem (which identifies that I'm connected to the right server endpoint)

is this the right location/configuration for that cert?

then the two device certs here:

vmq_bridge.ssl.br0.certfile = /etc/vernemq/cert/cert.crt
vmq_bridge.ssl.br0.keyfile = /etc/vernemq/cert/privKey.pem

Again assuming these are correct, but possibly the keyfile needs to be in a .key extension? Not completely sure. Let me know if you'd like me to share a device cert to you so you can try with a similar configuration.

Thanks,
Wale

**Comment by larshesel** [comment] 2017-03-02 13:24
hi @oladehin 

I just did a quick setup with current master (1.0.0rc1) where I set up two VerneMQ brokers where one acted as a bridge to the other. I used the test client/server certs ca we use for our integration tests and got it to work without much hassle. 

To try to answer your questions 1) your `cafile` setup looks fine, 2) the certfile and keyfile looks OK too - the extension shouldn't matter.

What I did discover, though, was that we have a bug in our configuration parser which creates a default tcp bridge config which causes the bridge to try to connect to localhost:1889 which will obviously cause errors to be logged as there likely is no MQTT server to connect on that port. I've created a fix for this in #289

What you could do to troubleshoot this is to see with an appropriate tool (for example wireshark) if an SSL connection is made to the server:port specified in the config (`aXXXXXXXXXXXX.iot.us-east-1.amazonaws.com:8883`). If no connection was successfully establised, try and see if you can debug the issue with `mosquitto_sub/pub` which can also make tls connections.  If a connection is made and still nothing is coming through, it could be an issue that the topic published to on the aws side and the one subscribed to from the bridge side aren't exactly the same. Is there any way to ask the aws side which clients are subscribed and what topics they're subscribed to?

I hope this helps!

**Comment by vedavidhbudimuri** [comment] 2018-06-01 07:15
I'm able to create a bridge but the messages are flowing from VerneMQ to AWS IoT but not the other way around. 
Is it expected? If yes How to achieve the bidirectional bridge?

I'm trying to connect two AWS IoT Brokers with VerneMQ and trying to 
1) publish from VerneMQ and receive at Both AWS IoT Brokers -> Success
2) Publish from one of the AWS IoT Broker and receive at VerneMQ and other AWS IoT Broker -> Unable to achieve this

**Comment by vedavidhbudimuri** [comment] 2018-06-01 10:07
Hey @ioolkos 
How to specify in and out? I have connected two brokers with the config similar to the one below. To my knowledge, there isn't anything to configure at AWS IoT. Anyway, I will double check it and let you know. 


vmq_bridge.ssl.br0 = aXXXXXXXXXXXX.iot.us-east-1.amazonaws.com:8883
vmq_bridge.ssl.br0.try_private = off
vmq_bridge.ssl.br0.topic.1 = topic
vmq_bridge.ssl.br0.cleansession = on

vmq_bridge.ssl.br0.cafile = /etc/vernemq/cert/rootCA.pem
vmq_bridge.ssl.br0.certfile = /etc/vernemq/cert/cert.crt
vmq_bridge.ssl.br0.keyfile = /etc/vernemq/cert/privKey.pem
vmq_bridge.ssl.br0.insecure = off

vmq_bridge.ssl.br1 = aXXXXXXXXXXXX.iot.us-east-1.amazonaws.com:8883
vmq_bridge.ssl.br1.try_private = off
vmq_bridge.ssl.br1.topic.1 = topic
vmq_bridge.ssl.br1.cleansession = on

vmq_bridge.ssl.br1.cafile = /etc/vernemq/cert/rootCA.pem
vmq_bridge.ssl.br1.certfile = /etc/vernemq/cert/cert.crt
vmq_bridge.ssl.br1.keyfile = /etc/vernemq/cert/privKey.pem
vmq_bridge.ssl.br1.insecure = off
