### ISSUE TITLE
"can't calculate message rates"

### ISSUE THREAD

**Issue by jeremylink** [erlio/vernemq#322] opened 2017-03-21 19:46 UTC
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Centos6
- Erlang/OTP version (if building from source):

### Actual behaviour

The log file has these warnings every second:
   2017-03-21 19:38:49.132 [warning] <0.337.0>@vmq_metrics:handle_info:499 can't calculate message rates
2

I've seen this in 2 different scenarios:
1. When disconnecting devices (no authentication)
2. When I had disabled my webhooks server and so auth_on_register was failing 
    - started broker
    - started auth server
    - verified auth was working against server
    - shutdown auth server
    - tried to connect an endpoint again (failed due to auth server being down)
    -> this is when the messages started showing up in log file

**Comment by ioolkos** [comment] 2017-03-21 20:37
Hi @jeremylink thanks for your observation. 
Do you see it go away/recover? 

In principle this should be intermittent.  The rate function is called once a second, so it will be logged once a second as long as the open socket counter is smaller than the closed socket counter for some reason.

I'll better let @dergraf confirm that it is harmless though.

**Comment by jeremylink** [comment] 2017-03-21 20:55
I've left it running for a couple of hours and it is still there.

I was able to make it go away (once) by starting/stopping various clients,
but it is back again and I haven't found a new sequence that will make it
stop.

My biggest concern is that it will fill up the logs with a useless message
and "hide" the important messages.

**Comment by ioolkos** [comment] 2017-03-21 20:59
I see, thanks. We'll investigate this in any case.

**Comment by larshesel** [comment] 2017-03-24 11:11
Hi @jeremylink we were just discussing this and wanted to ask if you did a `vmq-admin metrics reset` which could be the cause of this (resetting everything to zero while sockets are open will result in a negative socket_open - socket_close value). In any case I think I'll prepare a patch to hide this reset feature as it really is only there for debugging purposes.

Just a thought.

**Comment by larshesel** [comment] 2017-03-24 11:17
Another thought - I don't believe VerneMQ compiles out of the box on the Centos6 OS series as the GCC toolchain is too old and doesn't properly support the atomic functions the metrics use to do atomic counter updates. Did you compile from source or somehow got the Centos7 packages installed? If it's not too much trouble, could you verify to see if this is an Centos6 only issue (how reproducible is it) or also occurs on Centos7?

**Comment by jeremylink** [comment] 2017-03-24 16:04
I did not do a vmq-admin metrics reset.

I was able to compile this to run on CentOS6 and am not currently running
on CentOS7. It is on my list of things to do, so once I get around to it I
will let you know if I have the same problem with 7.


-Jeremy

**Comment by larshesel** [comment] 2017-05-09 12:44
Since we haven't been able to reproduce this ourselves I'm closing this for now. Please reopen if you find out a way how to reproduce this.

**Closed by larshesel** 2017-05-09 12:44 UTC
