### ISSUE TITLE
Offline messages disappear/not loaded after broker restart

### ISSUE THREAD

**Issue by fevin86** [erlio/vernemq#564] opened 2017-12-29 07:11 UTC
### Environment

- VerneMQ Version: 1.2.2
- OS: Docker on MacOS
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.
  - ```docker run -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" -p 1883:1883 -it  erlio/docker-vernemq:1.2.2 bash```, this is just for keeping the container running
  - ```docker exec -it {container_id} bash```
    - ```start_vernemq```
  - subscribe
    ```mosquitto_sub -h {docker_host_ip} -p 1883 -t "{a_topic}" -q 1 -i offline  -c```
  - publish couple messages to verify the connection is working
    ```mosquitto_pub -h {docker_host_ip} -p 1883 -t "{a_topic}" -q 2 -m "hello"```
  - terminate the subscriber
  - publish more messages
  - check if there is offline messages in container
    ```vmq-admin session show --client_id --offline_messages```
  - if there are offline messages
    ```vernemq stop``` and ```start_vernemq```
  - do ```vmq-admin session show --client_id --offline_messages``` again, the offline messages should still show the same number

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
  - the offline messages number is back to 0

I tried the docker 1.2.1 version, it is working fine.

**Comment by fevin86** [comment] 2017-12-29 07:48
Also tested in a local built version, it is broken as well.

A binary search shows the unwanted behaviour may be introduced by: https://github.com/erlio/vernemq/commit/99b2372128119214d7ead7f0fbeee9f6e6769887

**Comment by ioolkos** [comment] 2017-12-29 08:33
Thanks for spotting this @fevin86 !
So it's just the problem that the offline metrics gets reset to 0. I can't see why this would be intentional. 
@larshesel bug or feature? :)

**Comment by fevin86** [comment] 2017-12-29 09:17
Not only about the metrics; the offline messages won’t be delivered as well.

**Comment by dergraf** [comment] 2017-12-29 09:25
This is a regression we've addressed in https://github.com/erlio/vernemq/pull/553
@larshesel I think we should merge the PR above.

**Comment by larshesel** [comment] 2018-01-02 15:49
#553 has been merged which contains a fix for this issue. I wanted to add some tests so we never see this issue again but didn't get around to writing them yet which was the reason for not merging this earlier...

It would be fantastic if you could retest with master to check this indeed solves the issue for you.

Thanks again!

**Closed by larshesel** 2018-01-02 15:49 UTC

**Comment by fevin86** [comment] 2018-01-07 23:30
@larshesel tested and passed. Thanks for the fix!
