### ISSUE TITLE
VerneMQ stops unexpectedly during load test

### ISSUE THREAD

**Issue by KnolBee** [erlio/vernemq#484] opened 2017-08-09 13:12 UTC
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):
- 1 HAProxy server M4.4xLarge (64 GB)
- 6 VerneMQ Servers M4.2xLarge (32GB)
- 4 Load test servers M4.2xLarge
- Load test servers connect to vernemq through HAProxy

### Expected behavior

- VerneMQ should not crash

### Actual behavior

- Vernemq stops randomly, out of 6 servers, 1-2 servers stops without warnin Logs below.
- When total connections reach around 1 Million, few systems go down, but others continue. The load is equally balanced by HAProxy in round robin fashion. We are about to take VerneMQ to production and this is pre production testing.
- Time taken to reach 1 million is around 30-40 Minutes. Before crash each system would have about ~160k connections.

**root@ip-172-31-4-162:/var/log/vernemq# tail erlang.log.3**

===== ALIVE Wed Aug  9 12:38:40 UTC 2017

===== Wed Aug  9 12:52:39 UTC 2017
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_terminated,plumtree,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,plumtree,shutdown})

Crash dump is being written to: /var/log/vernemq/erl_crash.dump...done

**root@ip-172-31-4-162:/var/log/vernemq# tail crash.log**
     Context:    shutdown_error
     Reason:     {noproc,{gen_server,call,[{vmq_reg_sync,'VerneMQ@172.31.4.162'},{done,<0.8539.22>,{error,owner_terminated}},infinity]}}
     Offender:   [{nb_children,1},{id,vmq_reg_sync_action},{mfargs,{vmq_reg_sync_action,start_link,[]}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

2017-08-09 12:52:29 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_reg_sync_action_sup}
     Context:    shutdown_error
     Reason:     {noproc,{gen_server,call,[{vmq_reg_sync,'VerneMQ@172.31.4.162'},{done,<0.8834.22>,{error,owner_terminated}},infinity]}}
     Offender:   [{nb_children,1},{id,vmq_reg_sync_action},{mfargs,{vmq_reg_sync_action,start_link,[]}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

**root@ip-172-31-4-162:/var/log/vernemq# tail error.log**
2017-08-09 12:52:21.935 [error] <0.260.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8172.22> exit for subscriber {[],<<"KgEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:21.945 [error] <0.297.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8262.22> exit for subscriber {[],<<"5iEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:21.978 [error] <0.261.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8205.22> exit for subscriber {[],<<"wgEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.045 [error] <0.318.0> Supervisor vmq_reg_sync_action_sup had child vmq_reg_sync_action started with vmq_reg_sync_action:start_link() at undefined exit with reason no such process or port in call to gen_server:call({vmq_reg_sync,'VerneMQ@172.31.4.162'}, {done,<0.8539.22>,{error,owner_terminated}}, infinity) in context shutdown_error
2017-08-09 12:52:22.069 [error] <0.263.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8271.22> exit for subscriber {[],<<"hfEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.106 [error] <0.277.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8298.22> exit for subscriber {[],<<"CgEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.114 [error] <0.258.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8670.22> exit for subscriber {[],<<"7rEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.123 [error] <0.279.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8661.22> exit for subscriber {[],<<"3rEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.143 [error] <0.287.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8827.22> exit for subscriber {[],<<"bwEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}
2017-08-09 12:52:22.199 [error] <0.265.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.8770.22> exit for subscriber {[],<<"avEWb">>} due to {noproc,{gen_server,call,[plumtree_metadata_leveldb_instance_sup,count_children,infinity]}}

**root@ip-172-31-4-162:/var/log/vernemq# tail console.log**
2017-08-09 12:52:22.203 [warning] <0.15751.14>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.15912.14>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.26734.10>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.26753.10>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.24436.14>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.24526.14>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.9855.21>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.9861.21>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.11354.6>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.11376.6>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.30941.0>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.31150.0>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.3292.12>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.3301.12>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.28299.5>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.28400.5>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.645.21>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.711.21>,killed}}'
2017-08-09 12:52:22.204 [warning] <0.10488.19>@vmq_ranch:teardown:127 session stopped abnormally due to '{error,{queue_down,<0.10679.19>,killed}}'

**root@ip-172-31-4-162:/var/log/vernemq# tail erl_crash.dump**
timeout
infinity
fun
''
'$end_of_table'
'nonode@nohost'
'_'
true
false
=end

Post crash restarting vernemq doesn't help

**# Restart Fails for First time**
**root@ip-172-31-0-178:/home/ubuntu# service vernemq restart**
Job for vernemq.service failed because the control process exited with error code. See "systemctl status vernemq.service" and "journalctl -xe" for details.
**root@ip-172-31-0-178:/home/ubuntu# systemctl status vernemq.service**
```
● vernemq.service - VerneMQ is a MQTT message broker
   Loaded: loaded (/lib/systemd/system/vernemq.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-08-09 13:35:49 UTC; 1min 39s ago
  Process: 4137 ExecStop=/usr/sbin/vernemq stop (code=exited, status=1/FAILURE)
  Process: 4208 ExecStart=/usr/sbin/vernemq start (code=exited, status=1/FAILURE)
 Main PID: 3586 (code=killed, signal=TERM)

Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: Starting VerneMQ is a MQTT message broker...
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Control process exited, code=exited status=1
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: Failed to start VerneMQ is a MQTT message broker.
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Unit entered failed state.
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Failed with result 'exit-code'.
**root@ip-172-31-0-178:/home/ubuntu# journalctl -xe**
Aug 09 13:35:27 ip-172-31-0-178 systemd[1]: Stopping VerneMQ is a MQTT message broker...
-- Subject: Unit vernemq.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit vernemq.service has begun shutting down.
Aug 09 13:35:28 ip-172-31-0-178 vernemq[4137]: Node 'VerneMQ@172.31.0.178' not responding to pings.
Aug 09 13:35:28 ip-172-31-0-178 vernemq[4137]: Node is not running!
Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: vernemq.service: Control process exited, code=exited status=1
Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: Stopped VerneMQ is a MQTT message broker.
-- Subject: Unit vernemq.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit vernemq.service has finished shutting down.
Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: vernemq.service: Unit entered failed state.
Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: vernemq.service: Failed with result 'exit-code'.
Aug 09 13:35:28 ip-172-31-0-178 systemd[1]: Starting VerneMQ is a MQTT message broker...
-- Subject: Unit vernemq.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit vernemq.service has begun starting up.
Aug 09 13:35:29 ip-172-31-0-178 vernemq[4438]: Starting up
Aug 09 13:35:49 ip-172-31-0-178 vernemq[4208]: vernemq failed to start within 15 seconds,
Aug 09 13:35:49 ip-172-31-0-178 vernemq[4208]: see the output of 'vernemq console' for more information.
Aug 09 13:35:49 ip-172-31-0-178 vernemq[4208]: If you want to wait longer, set the environment variable
Aug 09 13:35:49 ip-172-31-0-178 vernemq[4208]: WAIT_FOR_ERLANG to the number of seconds to wait.
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Control process exited, code=exited status=1
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: Failed to start VerneMQ is a MQTT message broker.
-- Subject: Unit vernemq.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit vernemq.service has failed.
-- 
-- The result is failed.
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Unit entered failed state.
Aug 09 13:35:49 ip-172-31-0-178 systemd[1]: vernemq.service: Failed with result 'exit-code'.
Aug 09 13:36:53 ip-172-31-0-178 sshd[5665]: Received disconnect from 201.208.237.82 port 58577:11:  [preauth]
Aug 09 13:36:53 ip-172-31-0-178 sshd[5665]: Disconnected from 201.208.237.82 port 58577 [preauth]
```
**root@ip-172-31-0-178:/home/ubuntu# tail -f /var/log/vernemq/console.log** 
```
2017-08-09 13:35:30.921 [info] <0.238.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir /var/lib/vernemq/meta/meta/10 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,54214057}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2017-08-09 13:35:30.967 [info] <0.239.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir /var/lib/vernemq/meta/meta/11 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,39645217}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2017-08-09 13:35:31.044 [error] <0.248.0> gen_server plumtree_broadcast terminated with reason: no such process or port in call to gen_server:call(plumtree_metadata_manager, {is_stale,{{vmq,subscriber},{[],<<"wKbYb">>}},[{'VerneMQ@172.31.5.165',2}]}, infinity)
2017-08-09 13:35:31.044 [error] <0.248.0> CRASH REPORT Process plumtree_broadcast with 0 neighbours exited with reason: no such process or port in call to gen_server:call(plumtree_metadata_manager, {is_stale,{{vmq,subscriber},{[],<<"wKbYb">>}},[{'VerneMQ@172.31.5.165',2}]}, infinity) in gen_server2:terminate/3 line 995
2017-08-09 13:35:31.089 [error] <0.220.0> Supervisor plumtree_sup had child plumtree_broadcast started with plumtree_broadcast:start_link() at <0.248.0> exit with reason no such process or port in call to gen_server:call(plumtree_metadata_manager, {is_stale,{{vmq,subscriber},{[],<<"wKbYb">>}},[{'VerneMQ@172.31.5.165',2}]}, infinity) in context child_terminated
2017-08-09 13:35:31.089 [info] <0.31.0> Application plumtree started on node 'VerneMQ@172.31.0.178'
2017-08-09 13:35:31.116 [info] <0.31.0> Application vmq_plugin started on node 'VerneMQ@172.31.0.178'
2017-08-09 13:35:31.116 [info] <0.31.0> Application ssl_verify_fun started on node 'VerneMQ@172.31.0.178'
2017-08-09 13:35:31.116 [info] <0.31.0> Application epgsql started on node 'VerneMQ@172.31.0.178'
2017-08-09 13:35:31.140 [info] <0.31.0> Application hackney started on node 'VerneMQ@172.31.0.178'
```

# Restart Success if tried second time, But its in inconsistent mode
**root@ip-172-31-0-178:/home/ubuntu# service vernemq restart
root@ip-172-31-0-178:/home/ubuntu# tail -f /var/log/vernemq/console.log** 
2017-08-09 13:38:37.377 [error] <0.4359.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"6S7Yb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.379 [error] <0.4360.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"HJAYb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.382 [error] <0.4361.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"HikZb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.382 [error] <0.4362.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"INXYb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.384 [error] <0.4363.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"V0XYb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.384 [error] <0.4364.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"czhZb">>} due to
                                no_matching_hook_found
2017-08-09 13:38:37.387 [error] <0.4365.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"MazYb">>} due to
                                no_matching_hook_found

**Comment by larshesel** [comment] 2017-08-09 13:20
Hi

What is the memory/cpu load on the servers when this happen?

Can you post the output if you run `erl_crashdump_analyzer.sh erl_crash.dump` on the crash dump file? (get the script here: https://github.com/ferd/recon/blob/master/script/erl_crashdump_analyzer.sh)

**Comment by KnolBee** [comment] 2017-08-09 13:53
**root@ip-172-31-0-178:/var/log/vernemq# ./erl_crashdump_analyzer.sh erl_crash.dump**
```
analyzing erl_crash.dump, generated on:  Wed Aug 9 13:47:28 2017 

Slogan: eheap_alloc: Cannot allocate 20310580872 bytes of memory (of type "heap").

Memory:
===
  processes: 16464 Mb
  processes_used: 16463 Mb
  system: 143 Mb
  atom: 0 Mb
  atom_used: 0 Mb
  binary: 54 Mb
  code: 10 Mb
  ets: 40 Mb
  ---
  total: 16607 Mb

Different message queue lengths (5 largest different):
===
  14690 0

Error logger queue length:
===
0

File descriptors open:
===
  UDP:  0
  TCP:  7213
  Files:  5
  ---
  Total:  7218

Number of processes:
===
14690

Processes Heap+Stack memory sizes (words) used in the VM (5 largest different):
===
      1 2115685508
      1 514838
      1 196650
      1 121536
      4 75113

Processes OldHeap memory sizes (words) used in the VM (5 largest different):
===
  14690 OldHeap unused: 0
  14690 0

Process States when crashing (sum): 
===
      1 Current Process Garbing
      1 Current Process Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
      1 Garbing
      3 Internal ACT_PRIO_LOW | USR_PRIO_LOW | PRQ_PRIO_LOW | TRAP_EXIT | ON_HEAP_MSGQ
      6 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | ON_HEAP_MSGQ
      2 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | TRAP_EXIT | ON_HEAP_MSGQ
      1 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
   8270 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ON_HEAP_MSGQ
   6408 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | TRAP_EXIT | ON_HEAP_MSGQ
  14689 Waiting
```

**Comment by KnolBee** [comment] 2017-08-09 14:37
```
analyzing erl_crash.dump, generated on:  Wed Aug 9 14:26:08 2017 

Slogan: Kernel pid terminated (application_controller) ({application_terminated,plumtree,shutdown})

Memory:
===
  processes: 199 Mb
  processes_used: 192 Mb
  system: 48 Mb
  atom: 0 Mb
  atom_used: 0 Mb
  binary: 0 Mb
  code: 10 Mb
  ets: 3 Mb
  ---
  total: 248 Mb

Different message queue lengths (5 largest different):
===
      4 0

Error logger queue length:
===
0

File descriptors open:
===
  UDP:  0
  TCP:  0
  Files:  1
  ---
  Total:  1

Number of processes:
===
4

Processes Heap+Stack memory sizes (words) used in the VM (5 largest different):
===
      2 17731
      1 987
      1 610

Processes OldHeap memory sizes (words) used in the VM (5 largest different):
===
      4 OldHeap unused: 0
      4 0

Process States when crashing (sum): 
===
      1 Current Process Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | TRAP_EXIT | ON_HEAP_MSGQ
      1 Current Process Running
      1 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | TRAP_EXIT | ON_HEAP_MSGQ
      3 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | TRAP_EXIT | ON_HEAP_MSGQ
      1 Running
      3 Waiting
```

**Comment by larshesel** [comment] 2017-08-09 14:46
I don't know why you deleted the first crash dump analysis, but in that crash dump it was clear that the server ran out of memory (eheap_alloc: Cannot allocate 20310580872 bytes of memory (of type "heap")), as it was trying to allocate 20GB. So the question is why did it end up using so much memory?

If you're connecting 1M clients over a period of 30 minutes that means on average 555 clients per second - maybe this is too much. It would be interesting to see the increase in memory usage during the load test.

**Comment by KnolBee** [comment] 2017-08-09 15:27
I had restarted vernemq so got confused if it had changed the logs. I have 6 vernemq in the cluster, so it makes ~92 clients per second per vernemq (HAProxy configured as round robin). Currently HAProxy is setup with rate-limit as 10 per second, i can reduce it further. But then our usecase is to have large numbers of clients within short duration. Would increasing it to 12 smaller system help? like 12 16 GB systems instead of 6 32 GB system?

**Comment by KnolBee** [comment] 2017-08-10 04:56
Is there any way I can configure Verne MQ to shut down gracefully in the event of memory limits exhausted? Stopping like this will lead to message loss :-( Anything i can configure to prevent this from happening?

**Comment by ioolkos** [comment] 2017-08-10 05:55
I don't think 12 nodes are necessarily better here.

What is your actual testing scenario? is it just connection setup? and you subscribing? are you publishing messages? how do you do the testing (what testing framework?)

Could you give us an example vernemq.conf also?

**Comment by KnolBee** [comment] 2017-08-10 06:15
Here's more info:

- Using NodeJs client for testing, using mqtt library from https://github.com/mqttjs/MQTT.js
- Running the nodejs test client on 4 Systems at the same time. Each system connects to HAproxy 1883 port which load balances connections across 6 Verne MQ systems.
- Testing includes Connection Setup: Subscribe to one topic(which will be same as the client id), And publish one test message to the topic(which will be same as client id). Basically, every client subscribes and publishes one message to a topic which will be same as its own client id.
- Post connect/subscribe/publish, client keeps the connection open forever. If there is a disconnect from server side, it again connects->subscribes->publishes.
- If test is spread across 6 hours, vernemq does fine.
- My vernemq.conf looks like below

```
allow_anonymous = off
allow_register_during_netsplit = on
allow_publish_during_netsplit = on
allow_subscribe_during_netsplit = on
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
message_size_limit = 0
upgrade_outgoing_qos = off
listener.max_connections = infinity
listener.nr_of_acceptors = 1000
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 172.31.13.97:44053
listener.http.default = 0.0.0.0:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = on
graphite_host = 172.31.13.175
graphite_port = 2003
graphite_interval = 1000
graphite_prefix = iunode.perf.a
shared_subscription_policy = prefer_local
plugins.iuplugin = on
plugins.iuplugin.path = /data/mqtt/iuplugin/_build/default
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = on
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = on
vmq_diversity.mongodb.host = 172.31.1.100
vmq_diversity.mongodb.port = 27017
vmq_diversity.mongodb.login = mongodbusername
vmq_diversity.mongodb.password =  mongodbuserpassword
vmq_diversity.mongodb.database = mongodbdatabasename
vmq_diversity.mongodb.pool_size = 1000
vmq_diversity.auth_redis.enabled = off
log.console = file
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@172.31.13.97
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 1000000
erlang.process_limit = 10000000
leveldb.maximum_memory.percent = 70
```

**Comment by KnolBee** [comment] 2017-08-10 07:58
Out of 6 systems, one or two systems starts consuming more memory, and finally crashes. At the time of crash, 5 systems used 9 GB of Ram whereas the system which crashed used ~18 GB of ram. This built up was over time. Any way to find out if there is memory leak and where it is? Also is there a way to configure erlang's max memory/heap size?

![system-1](https://user-images.githubusercontent.com/20697325/29160400-b64d668c-7dcf-11e7-86a9-f9b68c6259e7.png)
![system-2](https://user-images.githubusercontent.com/20697325/29160402-b6508b0a-7dcf-11e7-9ab7-e5103964364d.png)
![system-3](https://user-images.githubusercontent.com/20697325/29160401-b65045e6-7dcf-11e7-9cd7-8418ffc2e1b0.png)
![system-4](https://user-images.githubusercontent.com/20697325/29160403-b651d6f4-7dcf-11e7-94b5-937e1ed69983.png)
![system-5-crash](https://user-images.githubusercontent.com/20697325/29160405-b658c82e-7dcf-11e7-94f6-a2b1eb90004a.png)
![system-6](https://user-images.githubusercontent.com/20697325/29160404-b654eb50-7dcf-11e7-9a63-4bc951dc00e6.png)

**Comment by larshesel** [comment] 2017-08-10 09:54
You wrote above that the test, if spread over 6 hours, passes. This suggest you're not experiencing a memory leak, but an overload situation that gets out of hand.

It is possible to try to identify why the overload situation happens and if there is something that can be done to improve it. It could be as basic as congestion in the network between the nodes or too small tcp buffers for the connections between the nodes. Or it could be a bottleneck somewhere in the code or a problem in a plugin (indirectly) causing issues. The point is finding out and improving this is not a trivial task (and not really the purpose of this forum) I would recommend getting in touch with us for commercial support.

**Comment by KnolBee** [comment] 2017-08-10 11:21
Thanks, "Problem in plugin"? you mean the custom plugin? I can disable that and rerun the test.

**Comment by ioolkos** [comment] 2017-08-10 16:06
@KnolBee the crash analysis shows that there is 1 process using a lot of heap+stack memory.
1469226048 words are about 11GB. We have to find what that process is. It's probably the one causing the aggressive heap_allocation.

It's not about full process message queues, as the crash analyzer shows.
I'd observe the system and try to find out what process starts to claim the most memory while setting up the connections.

**Comment by KnolBee** [comment] 2017-08-10 17:25
Thanks  @ioolkos How can i find the one process? i guess its erlang process, so linux ps would not help, Do i need to get into erlang shell? any pointers?

**Comment by sureshcostrategix** [comment] 2017-08-11 08:55
Hi i introduced delays in my test scripts and could reach 1.8 million connections. however, After 1 hour, without sending any new connections to the server, one of the system crashed. There was no new connections sent in that one hour. Logs below. Does it sound like memory leaks?

```
root@ip-172-31-13-97:/var/log/vernemq# tail erlang.log.1 
===== ALIVE Fri Aug 11 06:56:21 UTC 2017

===== Fri Aug 11 07:05:38 UTC 2017
eheap_alloc: Cannot allocate 11753808384 bytes of memory (of type "heap").

Crash dump is being written to: /var/log/vernemq/erl_crash.dump...
===== ALIVE Fri Aug 11 07:20:41 UTC 2017
done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

```

**Crash dump**

```
root@ip-172-31-13-97:/var/log/vernemq# /data/downloads/erl_crashdump_analyzer.sh erl_crash.dump
analyzing erl_crash.dump, generated on:  Fri Aug 11 07:05:42 2017 

Slogan: eheap_alloc: Cannot allocate 11753808384 bytes of memory (of type "heap").

Memory:
===
  processes: 14821 Mb
  processes_used: 14821 Mb
  system: 4296 Mb
  atom: 0 Mb
  atom_used: 0 Mb
  binary: 3037 Mb
  code: 10 Mb
  ets: 467 Mb
  ---
  total: 19117 Mb

Different message queue lengths (5 largest different):
===
      1 16
 702158 0

Error logger queue length:
===
0

File descriptors open:
===
  UDP:  0
  TCP:  350950
  Files:  5
  ---
  Total:  350955

Number of processes:
===
702159

Processes Heap+Stack memory sizes (words) used in the VM (5 largest different):
===
      1 1224355040
      1 5157867
      2 196650
      2 75113
     13 17731

Processes OldHeap memory sizes (words) used in the VM (5 largest different):
===
 702159 OldHeap unused: 0
 702159 0

Process States when crashing (sum): 
===
      1 Current Process Garbing
      1 Current Process Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
      1 Garbing
      3 Internal ACT_PRIO_LOW | USR_PRIO_LOW | PRQ_PRIO_LOW | TRAP_EXIT | ON_HEAP_MSGQ
      6 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | ON_HEAP_MSGQ
      2 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | TRAP_EXIT | ON_HEAP_MSGQ
      1 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
 352006 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ON_HEAP_MSGQ
 350141 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | TRAP_EXIT | ON_HEAP_MSGQ
 702158 Waiting

```

**Comment by larshesel** [comment] 2017-08-11 09:06
Hi @sureshcostrategix are you working with @KnolBee or is this a different project? If it is please open up a separate issue as where you describe your setup (nodes, servers, memory usage, vernemq version etc) so we don't get facts mixed up - the symptoms might look similar but the causes can be wildly different and we need as much information about your setup as possible to have any chance of finding out what's going on. Thanks.

**Comment by KnolBee** [comment] 2017-08-11 09:08
Hi, Its for same evaluation. Just replied from different id :-)

**Comment by larshesel** [comment] 2017-08-15 08:25
Hi @KnolBee, see the response I gave over here: https://github.com/erlio/vernemq/issues/486#issuecomment-322408092

This could explain the high memory usage and maybe your nodes gets into a conflict with memory needed and the memory used/tied up in the eleveldb/leveldb cache - which may not be freed fast enough to prevent an OOM error. So one option is to try and set the `leveldb.maximum_memory.percent` to some lower value, say 40% or 50% (or even as low as 20%) or so to see if that makes a difference and allow the rest of the system to function normally.

**Comment by larshesel** [comment] 2017-08-17 13:35
Hi @KnolBee did you have time to look into this? We would be very interested to hear if this helped your testing efforts.

**Comment by sureshcostrategix** [comment] 2017-08-18 06:45
Hi @larshesel Yes i tried with setting `leveldb.maximum_memory.percent = 20`. Setup is as below

1 HAProxy
5 VerneMQ System
4 Test clients

Reached total of ~1.8M. Each VerneMQ system had around 350K clients connected. At the end of the connection setup each system memory consumption was **~13G/32G** however **over night(12-16 hours) later**  memory consumption reached to **17.7G/32G**. However there are improvements Before there used to be crash within 2 hours of connection setup. Now only its memory increase only. I will continue the testing to one more day and see if memory consumption increases more. 

Thanks.

**Comment by KnolBee** [comment] 2017-08-21 11:03
Hi @larshesel I had kept it over weekend for testing and memory consumption stabilized at 17.7G/32G. Each system had 355K connections. Guess your solution of setting the memory limit to 20% fixes the issue. 

Is 17.7G memory for 355K a good number? or can i optimize the memory consumption further?

**Comment by larshesel** [comment] 2017-08-21 11:09
Glad to hear it helped - getting almost any system to handle 1.8M stateful connections is a non-trivial task!

To bring that number down you'd have to figure out what exactly is using the memory. I suppose you've already tuned the TCP Socket size? These can by default be pretty large and that quickly amounts to a lot of memory when having hundreds of thousands of connections - and most connections don't need such large buffers as they won't be handling large throughputs.

**Comment by larshesel** [comment] 2017-08-25 13:23
Hi @KnolBee how is your testing progressing? We're always interested in hearing about projects at the scale you're testing at :) I'll go ahead and close this issue as I think the original questions have been answered.

**Closed by larshesel** 2017-08-25 13:23 UTC
