### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by cc19941109** [erlio/vernemq#617] opened 2018-02-26 07:31 UTC
### Environment

- VerneMQ Version:1.3.0
- OS： CentOS 7.4 64    

### Actual behaviour

1. first , i configured  ip:  ```listener.tcp.default = 47.97.xxx.xxx:1883```

2.  ```service vernemq start```, it return ```Starting vernemq (via systemctl):  [  OK  ]```

3. ```vernemq ping ```, it return ```pong ``` 

4. then , i use java to connect mqtt server , it runs on an other machine.

    > return :
    >
    > Unable to connect to server (32103) - java.net.ConnectException: Connection refused

5. ```vmq-admin listener show```  

    it return : 

```
+----+-------+---------+-----+----------+---------+
|type|status |   ip    |port |mountpoint|max_conns|
+----+-------+---------+-----+----------+---------+
|http|running|127.0.0.1|8888 |          |  10000  |
|vmq |running| 0.0.0.0 |44053|          |  10000  |
+----+-------+---------+-----+----------+---------+
```    

i am not found mqtt. but  i don't know why .

6.  and i also use mosquitto 

    it works perfectly.

so, how i fix it

**Comment by ioolkos** [comment] 2018-02-26 08:12
@cc19941109 Hi, thanks for asking!
Obviously, there is no listener started on port 1883 and you try to connect to that with the MQTT client.
Investigate the reason. The most probable is that the port is already taken when you start VerneMQ... is it taken by Mosquitto ;)?

**Comment by cc19941109** [comment] 2018-02-26 14:39
Thank you for your reply  @ioolkos 

i uninstall vernemq. And install it again .

then 

1. ``` lsof -i:1883```   ->  return nothing 

2.  ``` vernemq start ``` -> return : ```Node is already running!```

      this is the first i start vernemq. i don't know why 

3.  ```lsof -i:1883```  -> return nothing 

i  did not modify any configuration

4. ```vernemq config effective ```

    ```
    allow_anonymous = off
     ......

    listener.tcp.default = 127.0.0.1:1883
listener.tcp.default.max_connections = -1
listener.tcp.default.mountpoint = 
listener.tcp.default.nr_of_acceptors = -1
listener.tcp.max_connections = -1
listener.tcp.mountpoint = 
listener.tcp.nr_of_acceptors = -1
listener.tcp.proxy_protocol = off
listener.tcp.proxy_protocol_use_cn_as_username = on

    ```

**Comment by larshesel** [comment] 2018-02-26 15:04
The error `Node is already running!` means VerneMQ was already running because it wasn't stopped before it was uninstalled. To kill the old instance find the `beam.smp` process and kill it. Then try to restart VerneMQ.

Watch the logs for warnings about the listener - it will log something if it is not possible to start the listener when starting VerneMQ.

**Comment by cc19941109** [comment] 2018-02-26 15:47
i can't kill beam.smp with ```kill -9 pid```  @larshesel 

```
-> ps aux| grep beam.smp
root      1588  0.0  0.0 112676   996 pts/0    S+   23:39   0:00 grep --color=auto beam.smp
```

there are some error logs  when vernemq started

```
[error] <0.353.0> Failed to start Ranch listener {{47,97,xxx,xxx},1883} in ranch_tcp:listen([{ip,{47,97,xxx,xxx}},{port,1883},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,true}]) for reason eaddrnotavail (can't assign requested address)

[error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: {listen_error,{{47,97,xxx,xxx},1883},eaddrnotavail} in gen_server:init_it/6 line 352

[error] <0.351.0> Supervisor {<0.351.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link({{47,97,xxx,xxx},1883}, 10, ranch_tcp, [{ip,{47,97,xxx,xxx}},{port,1883},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,...}]) at undefined exit with reason {listen_error,{{47,97,xxx,xxx},1883},eaddrnotavail} in context start_error

[error] <0.237.0>@vmq_ranch_config:reconfigure_listeners_for_type:187 can't reconfigure mqtt listener({47,97,xxx,xxx}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{proxy_protocol,false}] due to {{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,{{47,97,xxx,xxx},1883},eaddrnotavail}}},{child,undefined,{ranch_listener_sup,{{47,97,xxx,xxx},1883}},{ranch_listener_sup,start_link,[{{47,97,xxx,xxx},1883},10,ranch_tcp,[{ip,{47,97,xxx,xxx}},{port,1883},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,true}],vmq_ranch,[{mountpoint,[]}]]},permanent,infinity,supervisor,[ranch_listener_sup]}}
```

**Comment by larshesel** [comment] 2018-02-26 16:03
`eaddrnotavail` is a POSIX error meaning that the machine doesn't have that IP address (the one you specify beginning with the prefix `47.97.`) or the interface is not available.

**Comment by cc19941109** [comment] 2018-02-26 16:39
i want to connect mqtt-server on another machine , How should I configure 

there are some ip information

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:d0:a5:f4:33  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.246.170  netmask 255.255.240.0  broadcast 172.16.255.255
        ether 00:16:3e:0c:b5:35  txqueuelen 1000  (Ethernet)
        RX packets 7068  bytes 626580 (611.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4747  bytes 1050035 (1.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 5254  bytes 478269 (467.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5254  bytes 478269 (467.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@iZbp193yy46icaga1srlt6Z ~]# curl ifconfig.me
47.97.xxx.xxx
```

**Comment by larshesel** [comment] 2018-02-26 16:43
It's not clear what you're trying to achieve. 

If you're trying to set up a cluster please consult the documentation over here : http://vernemq.com/docs/clustering/

If you want to bridge to another MQTT broker you can take a look at http://vernemq.com/docs/configuration/bridge.html

I hope that helps. I'm closing this as this is not a bug report or feature request. Feel free to join our community on slack: https://slack-invite.vernemq.com/

**Closed by larshesel** 2018-02-26 16:43 UTC

**Comment by Kemwal1** [comment] 2018-11-11 10:32
Thank you for your quick reply
can you show me how to see if there is another process owning the port ? please 
ps : i've installed the broker in a new machine (only vernemq is intalled on it no other broker is installed)

**Comment by Kemwal1** [comment] 2018-11-11 11:12
@ioolkos 

![sans titre 1](https://user-images.githubusercontent.com/44786944/48312167-01f80580-e5ab-11e8-9736-6cf0aed963d9.jpg)
