### ISSUE TITLE
Shared subscriptions again: message not delivered to any subscriber

### ISSUE THREAD

**Issue by oakad** [erlio/vernemq#420] opened 2017-06-22 02:54 UTC
This problem was already mentioned in the past, but I suppose a clean sheet will make no harm.

Problem description:
When publishing to shared topic (`$share/<pool>/<topic>`) around 20% of the messages get lost (not delivered to any of the shared subscribers).

The problem manifests itself sporadically, and can be resolved by repeated restarts of vmq service (sometimes the db has to be deleted too). When VMQ starts in a proper mood everything works as expected.

When the problem is in effect, client tracing shows that message is received (RECV PUBLISH) and passed through the auth hooks (returning ok). Then, around 20% of the time message simply disappears (no further trace events nor log messages either on VMQ or test subscriber); ~80% of the time the client trace will show a proper reply from my test subscriber.

**Comment by larshesel** [comment] 2017-06-22 06:04
Hi - when this happens do you see any errors or warnings in the logs? Particularly logs about dropped messages? How many shared subscribers do you have? Are you connected directly to VerneMQ or are you going through firewalls, load balancers etc? Can you reproduce this directly with VerneMQ? What is your shared subscription policy? Are you running in a cluster? What are the message rates etc? Which QoS?

We've never ourselves experienced this problem and we do have tests covering shared subscription in place where we test that it works, so we're quite confident that it does. Of course our tests may be incomplete in some way and you're experiencing something they don't cover, so any information you can share would be helpful.

**Comment by ioolkos** [comment] 2017-06-22 08:09
adding my 2 cents: thanks for re-opening/bumping this! & apologies if I missed one of your previous issues.
This is really interesting :)
I'm particularly interested in what client lib you use and how I could setup any test that could verify/falsify the problem.

**Comment by oakad** [comment] 2017-06-22 08:23
I'm using a custom client based on netty/mqtt (java 8). The connection goes directly to vmq (using TLS makes no difference), QoS 0 only. There is nothing unusual in the logs, even at debug log level. No clustering is enabled, just a single node.

When vmq starts in "bad" mood it is broken for any number of clients. Even runs as small as 2 shared + 10 non shared clients readily and quickly exhibit the problem and it appears that all non-shared clients are affected equally and randomly.

When vmq starts in "good" mood, we were able to run 24 shared subscribers serving 100k+ non shared at 30kRPS message rates with only minor log noise.

Thus, the problem is not load related, but some effect happening when vmq is initializing the virtual shared subscriber.

I can try to trigger the issue and ship you all the relevant files (logs + db). It's around 200MB as of right now, but I can store those on AWS s3 bucket.

**Comment by larshesel** [comment] 2017-06-22 08:33
If you can reproduce it with just a few shared subscribers and a few non-shared clients (I suppose these are the producers?) then it would be much easier to look a the logs instead of having to go through 200MB of logs

**Comment by oakad** [comment] 2017-06-23 01:43
Indeed, it happens on a completely empty db as well.
[vernemq-db.tar.gz](https://github.com/erlio/vernemq/files/1096580/vernemq-db.tar.gz)
[vernemq-logs.tar.gz](https://github.com/erlio/vernemq/files/1096581/vernemq-logs.tar.gz)

**Comment by larshesel** [comment] 2017-06-23 05:17
Hi @oakad it looks like you added a comment with some files and then deleted them again? I don't see them here?

**Comment by oakad** [comment] 2017-06-23 05:26
Yes, I managed to trigger the issue, but the logs file were not the correct ones. Then the issue stopped triggering and I could not get a new set of those. I will try again later.

**Comment by larshesel** [comment] 2017-06-23 05:44
Ok, thanks, appreciate it. When you can reproduce it could you please tell us as precisely as possible the steps you took to do it, number of clients, which subscribed to what which shared subscriptions do they have and which are publishing etc?

**Comment by larshesel** [comment] 2017-06-26 18:26
Hi @oakad - do you have any updates on this?

**Comment by oakad** [comment] 2017-06-27 01:34
Unfortunately no - the issue would not trigger on the low load test anymore, and my ability to test at scale is limited, as we may not use mqtt in the near future after all.

**Comment by larshesel** [comment] 2017-06-27 06:22
ok - sorry to hear that. Since we haven't been able to reproduce this I'll close this for now - but if you happen to find out more we'll be happy to learn more about it. And if you should decide to use MQTT we of course hope you'll still consider VerneMQ - we'd be happy to help!

**Closed by larshesel** 2017-06-27 06:22 UTC

**Comment by navado** [comment] 2018-08-15 08:40
We're experiencing the same problem at pretty low scale (~600 messages per second)
In our case the setup as following:
- using paho mqtt client (python)
- shared clients subscribing to $share/tt/topic
- non-shared clients receive all the messages
- shared clients don't receive part of the messages, but not shared clients receive those messages just fine at the same time (means message is in the broker
-there is nothing suspicious in the logs

The config: [vernemq.conf.txt](https://github.com/erlio/vernemq/files/2289677/vernemq.conf.txt)
The configuration of queue ballansing there in the attempt to solve the problem with different type of the balansing

Appreciate any help

**Comment by ioolkos** [comment] 2018-08-15 08:56
@navado thanks for your report.
This is a single node broker, not a cluster, right?

Do you use different client IDs for the shared clients subscribing? (shared subscriptions being not the same as allowing and balancing multiple sessions with the same ClientID)

@larshesel any further ideas on this?

**Comment by navado** [comment] 2018-08-15 09:03
It's single node broker.
Shared clients use different IDs and all of them receive messages, but part of them definitely lost.

**Comment by larshesel** [comment] 2018-08-15 09:04
@navado I see you're also allowing multiple sessions. Most uses cases are better served using just shared subscriptions (which is a standard feature and is able to scale better). To simplify things I would therefore set `allow_multiple_session=off` and see how things then behave.

**Comment by ioolkos** [comment] 2018-08-15 09:12
How many subscribers are you sharing? are the subsribers online all the time? 

(if you have a subscriber configured with clean_session false, and it's offline, messages will still be delivered to its offline queue, and not to others)

**Comment by navado** [comment] 2018-08-15 13:02
Usually it's 5-6 subscribers per share. They're migrating from time to time and reconnect with different IDs

**Comment by ioolkos** [comment] 2018-08-15 14:00
@navado thanks for your effort! I'll try to test & reproduce this, but it'll take me some time. I'll see what I can find out.

**Comment by navado** [comment] 2018-08-16 20:49
@larshesel You see there multiple sessions allowed because I found this thread exactly when tried to do load balancing with multiple sessions. This configuration works now and seems that the loss stopped. The previous configuration was differ on this value only.

@ioolkos That's might be a problem. We have a cluster of subscribers (usually 5-7) per share depending on the load on the topic. The subscribers "breath" dynamically and might be replaced from time to time using dynamic mechanisms (like CPU load balancing on the cluster). Cleanup after unsubscribe and disconnect implemented too. Consumers have unique and dynamic names in case of the balancing using shares. With the clean_session=True we might have seen some loss too, though there was no extensive testing prior moving to balancing secessions instead shares.

After this discussion I have 2 main questions regarding the topic:
What is a disadvantage of using sessions balancing over shares balancing? Do these mechanisms utilize different code?
Another question, is there any rationale of using not clean sessions when subscribing to a share?

**Comment by larshesel** [comment] 2018-08-17 09:42
The disadvantage of allowing multiple sessions is 1) it's non-standard - so you may not find this feature on other brokers 2) that on each broker node where the clients with shared client-ids are connected a queue will be created for those clients will be created - this means there'll be a load balancing happening between the clients with the same client-id connected to each node, not cluster-wide (this can result in duplicates) 3) the load-balancing is limited by the number of messages which can be handled by a single queue (each session is connected to a queue process). 

Shared subscriptions are a completely different concept, at least from an implementation standpoint: each client has it's own queue process (assuming different client-ids and not allowing multiple sessions) and the messages are distributed between these queue processes - this is basically like normal clients that are subscribed to the same topic, but internally in VerneMQ only one of the subscribers are chosen to received the message. 

The mechanisms use completely different code paths: session balancing happens inside the queue process, while shared subscriptions logic is done in the routing layer.

Regarding clean_session=false, then if a client which is part of a shared subscription is offline, then the logic will always first try to deliver the message to one of the online clients before delivering to an offline client. This is also documented here: http://vernemq.com/docs/configuration/shared_subscriptions.html

About using clean_session=true|false I don't think there's a right/wrong choice. It depends on the use case. If you're using cs=false and all your subscribers are offline then the broker will continue distributing the messages between the subscribers until the `max_offline_queue` limit is reached whereafter it will start to drop messages. Note, messages are not distributed perfectly random, so it can happen that one queue is full and the message is then dropped, while another of the offline clients still has room in its queue - so it's not perfect and the queues have to be 'large enough' depending on what kind of time frames the clients are offline and which message rates are expected.

**Comment by Abhimanyu6676** [comment] 2020-10-12 18:29
Hello, 
Does anyone has resolved this issue or a work around. 
I am running vernemq inside a docker container,
`shared_subscription_policy = random`
But none of the subscribers getting any msg

I have 4 client with different id's subscribing to '$share/group/product/#'
And multiple devices publishing on topic 'product/....'
But none of the client is getting any msg, 
However if I connect new client and subscribe to topic 'product/#' I receive 4 copies of each msg

**Comment by ioolkos** [comment] 2020-10-12 19:24
@Abhimanyu6676 can you please setup the shared subscription with a command line MQTT tool like `mosquitto_sub` using the `-d` debug flag?
-> can they connect? -> can they subscribe? (what SUBACK response code do they get?) are they authorized to read from those topics, from your auth config?
Also, please check the VerneMQ logs for any clues about this.
