### ISSUE TITLE
Defining more than one bridge fails parsing the config

### ISSUE THREAD

**Issue by gokr** [erlio/vernemq#269] opened 2017-02-07 20:47 UTC
### Environment

- VerneMQ Version: 0.15.3-f73cc2a0-1
- OS: Ubuntu 14.04.5 LTS
- Erlang/OTP version (if building from source):

### Expected behavior

No failure in parsing config. :)

### Actual behaviour
Define first a br0, then a br1 - it will fail parsing the config when second bridge added.

**Comment by larshesel** [comment] 2017-02-08 07:30
Hi @gokr I just confirmed this. We'll start figuring out the reason and fixing it shortly.

**Comment by larshesel** [comment] 2017-02-08 09:15
I narrowed it down to our usage of `lists:usort/1` for some bridge options and not for others which causes a badmatch in the `TCPIPs` variable. See https://github.com/erlio/vernemq/blob/master/apps/vmq_bridge/priv/vmq_bridge.schema#L346.

@dergraf do you remember why `lists:usort/1` was applied there? For the uniqueness property? If so I don't see why we'd need that, but I might be missing something. I'd propose removing the `lists:usort/1` calls (which makes it work).

**Comment by dergraf** [comment] 2017-02-15 19:43
fixed in #271

**Closed by dergraf** 2017-02-15 19:43 UTC
