### ISSUE TITLE
VerneMQ HTTP API - doesn't work

### ISSUE THREAD

**Issue by ulutomaz** [erlio/vernemq#391] opened 2017-05-22 08:17 UTC
### Environment

- VerneMQ Version: 1.0.1-1
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

I have a cluster of 2 nodes. VMQ-ADMIN returns responses ok. Cluster status ok. 

### Expected behavior

I followed the documentation on HTTP API. I've created a key, was able to list it. But when I try to use it... there is no response from API. 

I have configuration for http in verne.conf just on first node. I assume this is ok as long I only do requests towards this node. 

### Actual behaviour

I've tried on localhost and from remote host. (Firewall configured correctly)

curl http://<api key>@localhost:8888/api/v1/session/show

returns nothing. I've tried some other commands as well. 

Best,
Tomaz

**Comment by larshesel** [comment] 2017-05-24 04:49
Hi @ulutomaz

In your curl command above the api key is missing. It should look something like this:

    curl http://JxctXkZ1OTVnlwvguSCE9KtujacMkOLF@localhost:8888/api/v1/session/show

Of course using your API key.

**Comment by ulutomaz** [comment] 2017-05-24 06:00
Well, this was my mistake whale pasting proper command. I did use api key.

**Comment by larshesel** [comment] 2017-05-24 13:40
I know it's frustrating when things don't work, but to help us help you, could you please try to be very explicit and show an exact sequence of commands that leads to this problem - to make it simple and to avoid other issues influencing diagnosing the problem, please do it locally on the vernemq node. Also check which HTTP return code that is being returned (if a connection can be made).

One possible issue could be that you have something else running on port 8888 which prevents the vernemq http listener from starting.

**Comment by ulutomaz** [comment] 2017-05-24 18:29
Nothing else is running on port 8888 - did double check again. AWS firewall is properly configured for outside connections. I did check all scenarios a) from localhost - localy from vernemq node, b) from remote with curl, c) from remote with proper GUI like Paw.

**Comment by dergraf** [comment] 2017-05-24 22:17
Please share the output of `sudo vernemq config effective | grep listener` here.

**Comment by dergraf** [comment] 2017-05-24 22:18
@ulutomaz  I think you have a general issue with your networking setup which also affects #392

**Comment by larshesel** [comment] 2017-05-28 06:20
FWIW I just followed *exactly* the procedure mentioned on the documentation:

```
$ vmq-admin api-key create
lwaBlzSzEZKi8JEetOtOkguBq4voFSEK
$ curl http://lwaBlzSzEZKi8JEetOtOkguBq4voFSEK@localhost:8888/api/v1/session/show
{"table":[],"type":"table"}
```

and got an empty table - so it works just fine. So as @dergraf says you probable have some general issue with your setup. Can you do the above and show us *exactly* the steps you do? If you don't get anything from curl - can you run it with `-I` so we can see the HTTP status code returned?

**Comment by larshesel** [comment] 2017-06-03 17:23
Closing this as we can't reproduce it and there is too little concrete information to conclude anything.

**Closed by larshesel** 2017-06-03 17:23 UTC

**Comment by Shadab-Factana** [comment] 2023-01-12 03:39
Hi, can anyone help me to solve the below problem?
I am using verneMQ and I am trying the use verneMQ status API. http://0.0.0.0:8888/status even though clients are connected but status API is showing 0 online. I don't know what to check.
If someone can give some hints that would be very useful.

**Comment by ioolkos** [comment] 2023-01-16 09:52
@Shadab-Factana The status page reloads every 10 seconds only. Maybe that's confusing?

You can also check with `vmq-admin session show` and check the `online` status of the clients.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
