### ISSUE TITLE
Subscriptions stop working after plumtree_metadata_manager crashes in cluster environment

### ISSUE THREAD

**Issue by victorkendy** [erlio/vernemq#547] opened 2017-11-28 13:04 UTC
### Environment

- VerneMQ Version: 1.2.0
- OS: docker container using Ubuntu 16.04 (Xenial)
- Erlang/OTP version (if building from source):

### Expected behavior

- Subscriptions should work after a plumtree_metadata_manager crash.

### Actual behaviour

- When there is an error in the plumtree_metadata_manager the vernemq server stops accepting new subscriptions even when the manager process is restarted by the supervisor.

We had a cluster with 2 vernemq instances. Everything worked fine until there was a match error inside the plumtree_metadata_manager, these are the log entries for this error:

```
CRASH REPORT Process <0.21109.810> with 0 neighbours exited with reason: {{{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...},...} in gen_fsm:terminate/7 line 559

CRASH REPORT Process plumtree_metadata_manager with 0 neighbours exited with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in gen_server:terminate/7 line 812

CRASH REPORT Process plumtree_broadcast with 0 neighbours exited with reason: {{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...} in gen_server2:terminate/3 line 995

CRASH REPORT Process plumtree_metadata_manager with 0 neighbours exited with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in gen_server:terminate/7 line 812
```

After the error, the server continues to accept connection e publish messages, but subscriptions do not work (`router_subscriptions` metric remains constant and messages are not sent to subscribers).

**Comment by larshesel** [comment] 2017-11-28 15:35
I don't think we've seen this crash before - is this something you can reproduce somehow?

**Comment by victorkendy** [comment] 2017-11-29 16:04
This crash happens randomly in our production environment after about a week of stable execution. I could not reproduce it locally.

**Comment by larshesel** [comment] 2017-11-29 16:10
Are there any previous errors or crash reports before this happens?

**Comment by victorkendy** [comment] 2017-11-29 16:50
These are the log entries related to the plumtree:

```
gen_server plumtree_metadata_manager terminated with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472

CRASH REPORT Process plumtree_metadata_manager with 0 neighbours exited with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in gen_server:terminate/7 line 812

Supervisor plumtree_sup had child plumtree_metadata_manager started with plumtree_metadata_manager:start_link() at <0.287.0> exit with reason no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in context child_terminated

gen_server plumtree_broadcast terminated with reason: {{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...}

CRASH REPORT Process plumtree_broadcast with 0 neighbours exited with reason: {{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...} in gen_server2:terminate/3 line 995

Supervisor plumtree_sup had child plumtree_broadcast started with plumtree_broadcast:start_link() at <0.286.0> exit with reason {{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...} in context child_terminated

gen_server plumtree_metadata_manager terminated with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472

CRASH REPORT Process plumtree_metadata_manager with 0 neighbours exited with reason: no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in gen_server:terminate/7 line 812

Supervisor plumtree_sup had child plumtree_metadata_manager started with plumtree_metadata_manager:start_link() at <0.24336.799> exit with reason no case clause matching [] in plumtree_metadata_manager:store/2 line 472 in context child_terminated

Supervisor plumtree_sup had child plumtree_metadata_hashtree started with plumtree_metadata_hashtree:start_link() at <0.288.0> exit with reason {{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...} in context child_terminated

gen_fsm <0.21109.810> in state exchange terminated with reason: {{{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...},...}

CRASH REPORT Process <0.21109.810> with 0 neighbours exited with reason: {{{{case_clause,[]},[{plumtree_metadata_manager,store,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,472}]},{plumtree_metadata_manager,read_merge_write,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,457}]},{plumtree_metadata_manager,handle_call,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata_manager.erl"},{line,316}]},{gen_server,try_handle_call,...},...]},...},...} in gen_fsm:terminate/7 line 559
``` 
The rest of the error log relates to the websocket handshake that happens sometimes during the day.

Maybe related to the problem, during the weekend we had some network issues and the cluster was partitioned for about one hour but it was working fine afterwards.

**Comment by larshesel** [comment] 2017-11-29 17:20
@dergraf any ideas?

**Comment by larshesel** [comment] 2017-12-05 09:28
@victorkendy could you try to upgrade to 1.2.2 and see if you can reproduce it with that? We did a fix regarding cleaning state when a node is restarted/cluster leave/join  (which I'm not sure really applies to your netsplit situation). Not sure if it's related, but since I have no idea how to reproduce this I guess it's worth a shot.

**Comment by victorkendy** [comment] 2017-12-06 09:41
Sorry for the delay.

I will try the new version but it might take a while for the problem to happen (last time it took almost two weeks)

Thanks for help @larshesel

**Comment by victorkendy** [comment] 2017-12-15 09:12
The same problem happened in version 1.2.2

I think the problem may be related with the way we use the clientid in our app. To avoid disk issues, we created a plugin that uses the username as the client id for the connection. 

I'll modify the plugin to test for this hypothesis.

**Comment by larshesel** [comment] 2018-01-03 06:33
Hi @victorkendy did you find out more about what could be causing this?

**Comment by victorkendy** [comment] 2018-01-10 09:09
Hi @larshesel 

We didn't have any more issues after modifying our client id management.

It feels like there is some corner case on the replication algorithm when shared client ids are used.

**Comment by larshesel** [comment] 2018-01-10 10:25
Could you describe a bit what you were doing regarding client id management and what you changed that made the problem go away? Also, what do you mean by 'shared client ids'? It would be great if we could understand what was actually happening!

**Comment by victorkendy** [comment] 2018-01-11 09:28
Surely @larshesel

At first our application was using random client-ids to connect to the vernemq broker, but we ran into this issue https://github.com/erlio/vernemq/issues/423, the disk usage on the machine was growing without limits.

Our first approach to solve the issue was to use a fixed client id per username, for example, if the client connected to the broker using the username `the-user` we used that as the client id, we also changed the `queue_deliver_mode` to `fanout` in case the same user connected more than once. It worked fine when the machines were not in a clustered environment (we had 3 machines behind a load balancer on aws but they were not using vernemq's clustering).

After a while we decided to use the clustering with this setup and stumbled upon the problem described on this issue, if the `plumtree_metadata_manager` crashed the broker would not deliver messages to the subscribers.

After opening the issue, we suspected that this policy of using the username as the client-id of the mqtt protocol was the cause of the issue, so we used a different strategy. Each username would have a fixed pool of client-ids, say `the-user-1` to `the-user-100`, on connect, the authentication plugin would choose one of the client-ids available for that username and assign it to the connection. With this approach we are running the vernemq broker for almost a month without any issues.

**Comment by larshesel** [comment] 2018-02-21 06:50
Hi @victorkendy thanks for the information and taking the time to write it down for us, it'll be very helpful when we get time to look closer into this. I'll close this issue for now.

**Closed by larshesel** 2018-02-21 06:50 UTC
Labels: need more data

**Comment by larshesel** [comment] 2018-09-21 12:47
Hi @victorkendy I hope it's ok I revive this old issue - we've had some other cases of this problem and I just wanted to ask for a bit more information if you remember it.

did you use `allow_multiple_session=on` when you had the problem? What were the netsplit settings - the `allow_xxx_during_netsplit`?
