### ISSUE TITLE
vmq takes too much CPU

### ISSUE THREAD

**Issue by Yongke** [erlio/vernemq#154] opened 2016-06-16 11:27 UTC
Hi,

We plan to take the excellent vernemq to production, and our scenario needs vernemq to support as many subscribers as possible.

During the testing on a VPS with 4 core(E5-2680 v3 @ 2.50GHz), 8G RAM, it uses a lot of CPU.

 800 subscribers takes 107.8%, almost 1 core
`20   0 3446116  98272   4804 S 107.8  1.2   0:20.65 beam.smp`

Seems that vmq_exo is the most busy process? (it has biggest reductions)
Can I just stop it via some configurations? And we don't need the stats on every nodes. ;-)

**Comment by ioolkos** [comment] 2016-06-16 11:54
Hi,
you can't stop the vmq_exo process. Making the exo metrics more configurable (also to save CPU) is definitely on our TODO list.

If you absolutely need to have exo totally disabled right now, you need to re-compile.

1. Create a  `_checkouts` directory in the vernemq root dir
2. copy (not move) vmq_server dir from `_build/default/lib` into the `_checkouts` dir
3. edit the incr_item function in `vmq_exo.erl` (in the vmq_server version in _checkouts):

incr_item(_Entry, _Val) ->
ok.

instead of:
incr_item(Entry, Val) ->
    exometer:update_or_create(Entry ++ ['last_sec'], Val).

This should disable most of the overhead of vmq_exo. You need to build a new release though. (You might want to copy your `vernemq.conf` file before doing that)

**Comment by ioolkos** [comment] 2016-06-18 08:19
Currently testing PR https://github.com/erlio/vmq_server/pull/64 related to exo performance.

**Comment by Yongke** [comment] 2016-06-20 02:20
Thanks for the patch. I'll try it.

**Comment by Yongke** [comment] 2016-06-22 12:10
Hi, @ioolkos 

Under low pressure, 800 subscribers same as above, disable the stats improve a lot, which decreased to 40%. 
But if 40k subscribers(max for vernemq), there seems no difference. 

And comparing with emqttd(max 240k subscribers), it's still too much. Any more suggestions?

**Comment by ioolkos** [comment] 2016-06-22 12:18
Hi,
thanks for testing! :)
could you share exactly what you are trying to achieve? that is: could you describe your load test scenario?
(how do you reach 40k max? messages rates and QoS?)

If not possibly publicly, please send a mail to 'info' at vernemq.com

**Comment by Yongke** [comment] 2016-06-23 04:19
Hi, 
We want to at least supporting 300k subscribers, and push qos1 messages to some of them or even all of them.

So I wrote a very simple client in Go to simulate the subscriber to find out how many concurrent subscribers support every one node.


some system parameters
```
sysctl -w fs.file-max=2097152
sysctl -w fs.nr_open=2097152
echo 2097152 > /proc/sys/fs/nr_open
ulimit -n 1048576

sysctl -w net.ipv4.tcp_rmem='1024 4096 65535'
sysctl -w net.ipv4.tcp_wmem='1024 4096 65535'

sysctl -w net.ipv4.ip_local_port_range="1000 65535"
```

Command to starting 40k subscriber
```
./fake 40000 tnode
```

a) This is the top result after all connections established with emqttd 
![image](https://cloud.githubusercontent.com/assets/1893075/16291489/24f8f834-393a-11e6-9e5a-1b3a7fabc202.png)

b) This is for vernemq after all connections established
![image](https://cloud.githubusercontent.com/assets/1893075/16291654/e768f40e-393b-11e6-98c6-08f5b1178ce0.png)

Code below is the fake client,
```go
package main

import (
	"github.com/eclipse/paho.mqtt.golang"
	"time"
	"fmt"
	"strconv"
	"sync"
	"os"
)

var mutex = sync.RWMutex{}
var count = 0

func onConnect(c mqtt.Client) {
	token := c.Subscribe("mgmt/router/multicast/#", byte(1), onMessageReceived);
	if token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
}

func onMessageReceived(c mqtt.Client, msg mqtt.Message) {
	mutex.Lock()
	defer mutex.Unlock()
	count = count + 1
}

func main() {
	node := os.Args[2]
	n, _ := strconv.Atoi(os.Args[1])

	options := mqtt.NewClientOptions()
	options.AddBroker("tcp://100.114.47.27:1883")
	options.SetAutoReconnect(true)
	options.SetCleanSession(false)
	options.SetConnectTimeout(5 * time.Second)
	options.SetUsername("vmq")
	options.SetPassword("vmq")
	options.SetOnConnectHandler(onConnect)

	c := make(chan string)
	for i := 1; i <= n; i++ {
		go func() {
			id := "fakeroutersn" + node + strconv.FormatInt(int64(i), 10)
			fmt.Println(id)
			options.SetClientID(id)
			cli := mqtt.NewClient(options)
			token := cli.Connect()
			if token.Wait() && token.Error() != nil {
				panic(token.Error())
			}
			c <- "ok"
		}()
		<-c
	}

	for {
		time.Sleep(1 * time.Second)
		fmt.Println(count)
	}
}
```

**Comment by dergraf** [comment] 2016-06-23 06:19
thanks for sharing the details! The current queue implementation emits stats every second, even if the queue is inactive. This is unfortunate as it is consumes quite some CPU. We're going to fix this soon and hope that it will resolve your issue. I'll keep you posted so you could start a second round of benchmarks :)

**Comment by ioolkos** [comment] 2016-06-23 12:14
BTW: what shows you that 40k connections is "max" in your setup? how do you determine that?

Thanks! :)

**Comment by Yongke** [comment] 2016-06-23 13:01
Because after 40k(around 42k), new connection is likely timeout and panic ;-). And from the print log of client, I can see new connection become slower( means server side less responsive?) ;-)

**Comment by ioolkos** [comment] 2016-06-23 18:56
OK, thanks for your info.
I don't think the 40k problem is CPU performance related. If it is, you should see the Erlang schedulers maxed out. 

If you have Erlang installed on your system, you can observe VerneMQ with the Observer tool. Start it like this in a shell. This will show you the actual scheduler load and behaviour.

```
erl -name obs@127.0.0.1 -setcookie vmq -s observer
```

**Comment by Yongke** [comment] 2016-06-24 02:39
hi @dergraf 

this is result vmq with root
![image](https://cloud.githubusercontent.com/assets/1893075/16325886/a51719a0-39f4-11e6-931a-200f293c880f.png)

**Comment by Yongke** [comment] 2016-06-24 03:41
hi, @ioolkos 

This is the result of observer, hope it helps

![image](https://cloud.githubusercontent.com/assets/1893075/16327296/2d835564-3a00-11e6-9c6f-92b373348f05.png)

![image](https://cloud.githubusercontent.com/assets/1893075/16327326/6a3fe062-3a00-11e6-92ac-3b4165b91f88.png)

**Comment by Yongke** [comment] 2016-06-24 03:54
And I also found a strange problem. I run `vernemq stop` first, then client quit(crtl+c) ,  then server start, then client start(with same client ids as previous), there's 80388 processes.

In my understanding it should be 40000+, am I correct?

**Comment by Yongke** [comment] 2016-06-24 04:04
Hi, @dergraf 

Is it possible to have a quick fix to disable queue_stats as you mentioned above, I want to see the difference to check if it matters or not. 

I tried simply to comment lines below, but vmq became not working... :-(
`erlang:send_after(1000, self(), report_queue_stats)`

**Comment by ioolkos** [comment] 2016-06-24 04:45
1) As you see in Observer, schedulers are at 20%. So, it's not a CPU performance problem.

2) 80k processes are correct. (1 queue, 1 session per client).

3) You could extend the send_after timeout for `report_queue_stats`. It doesn't lower CPU usage though, so no need to do it.

When you reach 40k, is VerneMQ logging anything?

**Comment by Yongke** [comment] 2016-06-24 06:50
Hi, @ioolkos, thanks for your answer. 

This time I finally got a 60k connection.  
When it became 'slow', there are lots of log below

```
2016-06-24 06:39:29.659 [warning] <0.15559.4>@vmq_mqtt_fsm:connected:389 [<0.15559.4>] stop due to keepalive expired
2016-06-24 06:39:29.659 [warning] <0.15816.4>@vmq_mqtt_fsm:connected:389 [<0.15816.4>] stop due to keepalive expired
2016-06-24 06:39:29.659 [warning] <0.15552.4>@vmq_mqtt_fsm:connected:389 [<0.15552.4>] stop due to keepalive expired
```

And I also found the run queue some time more than 10000 ... (17186, 20008, and one time 40000+ with no screenshot), it still high even 
![lalot3kaisyszqgv_431_172](https://cloud.githubusercontent.com/assets/1893075/16330221/2ab35608-3a1a-11e6-9a89-adea37306180.png)
![lalot3mjasyozqfg_352_168](https://cloud.githubusercontent.com/assets/1893075/16330222/2ab449be-3a1a-11e6-8b38-a11a2c304cfd.png)

I think this high run queue number is the typical signal that some process is very busy at that time, and block the system.

**Comment by ioolkos** [comment] 2016-06-24 07:17
Well, there it is: stop due to keepalive_expired is exactly what it tells it is. Your connections time out & the server disconnects them. 

The Run Queue is then overloaded due to lots of connections coming down at the same time. It is very probably that this will slow down re-connects.

Fix/change your keepalive_timeout settings from the client_side.

Thanks for testing & patience :)

**Comment by Yongke** [comment] 2016-06-24 08:08
Changed the keepalive timeout from 30s (default) to 60s and 90s, it's does not help the situation.

**Comment by ioolkos** [comment] 2016-06-24 08:14
How long does it take to setup the 40k connections?

**Comment by Yongke** [comment] 2016-06-24 08:22
Just have a try, the timeline below:

10k --> 47
20k --> 1:36
30k --> 2:37
40k --> 4:21

this time, 'stop due to keepalive expired' did not happen. But's new connection get slower and slower

**Comment by Yongke** [comment] 2016-06-24 08:38
BTW, with a new round of test, I just disable
`erlang:send_after(1000, self(), report_queue_stats)`

CPU for maintaining the queue decrease a lot.  (only queue process exist, all connections quit)

![image](https://cloud.githubusercontent.com/assets/1893075/16332705/ef647cd4-3a29-11e6-9ff1-1168c05504b5.png)

**Comment by ioolkos** [comment] 2016-06-24 08:58
Great :)
We're currently looking if we can reproce the slowing down behaviour with the go client.

**Comment by Yongke** [comment] 2016-06-24 09:10
Thanks very much for your help. 
And one more question, what's the meaning of the CPU usage peak about every 10 seconds?

**Comment by ioolkos** [comment] 2016-06-24 09:15
There's a couple of options configured for 10 seconds in `vernemq.conf` (systree for example). You can set this to something else, of course.

BTW: what is your `listener.nr_of_acceptors` value there? can you set it higher as a test? (to 200 let's say)

**Comment by Yongke** [comment] 2016-06-24 09:21
Indeed, sys_interval=10 affect. 

And listener.nr_of_acceptors is currently 100, and this is my config for testing, I'll increase this.

```
allow_anonymous = off
trade_consistency = on
allow_multiple_sessions = on
queue_deliver_mode = balance
retry_interval = 20
max_client_id_size = 128
#persistent_client means clean_session=false
persistent_client_expiration = 1d
max_inflight_messages = 20
max_online_messages = 512
max_offline_messages = 512
message_size_limit = 0
upgrade_outgoing_qos = off
listener.max_connections = 100000
listener.nr_of_acceptors = 100
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 10.25.69.63:44053
listener.mountpoint = off

acl_file = /etc/vernemq/vmq.acl
acl_reload_interval = 10
password_file = /etc/vernemq/vmq.passwd
password_reload_interval = 10

sys_interval = 10

#graphite.interval = 15000
#graphite.port = 2003
#graphite.host = 172.30.40.2
#graphite.prefix =
#graphite.api_key = vernemq

log.console = file
log.console.level = info
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
leveldb.maximum_memory.percent = 70
nodename = vernemq@10.25.69.63
distributed_cookie = vmq
erlang.async_threads = 128
erlang.max_ports = 262144
erlang.schedulers.force_wakeup_interval = 500
erlang.schedulers.compaction_of_load = false
erlang.schedulers.utilization_balancing = true
```

**Comment by ioolkos** [comment] 2016-06-24 09:53
Just saw that you're over 60k connection now. But that's nearing the limit for 1 client and 1 server with 1 configured listener anyway, no?

Do you start the go script from different client machines to go over 60k?

**Comment by Yongke** [comment] 2016-06-24 09:54
Changed listener.nr_of_acceptors to 1024, almost the same result

10k --> 0:46
20k --> 1:36
30k --> 2:34
40k --> 4:16

**Comment by Yongke** [comment] 2016-06-24 10:02
Did not try different client machine, I will try it maybe next Monday.

**Comment by ioolkos** [comment] 2016-06-24 12:56
OK, thank you very much @Yongke !
Tremendous help  & effort from your side.

I'm looking forward to your further results & wish you the best weekend! :)

**Comment by Yongke** [comment] 2016-06-27 05:43
Tried today with different machine as client, same problem. 
And also tried 30k on machine1 and another 30k on machine2(after first 30k finished), the same

**Comment by ioolkos** [comment] 2016-06-27 06:58
OK, thanks!

In the shell where you start VerneMQ, what is your `ulimit -n` ?
Is it actually set to something reasonable? Just want to make sure.

**Comment by Yongke** [comment] 2016-06-27 07:36
I have posted this;-) it's big enough.
```
ulimit -n 1048576
```

**Comment by ioolkos** [comment] 2016-06-27 08:15
OK, thanks, just be a 100% sure it's in effect ;)

(and apologies for asking repetitive questions...)!

**Comment by ioolkos** [comment] 2016-06-27 19:30
Is there any more information to provide about this situation? What do the logs say at the point of break? how is CPU at that point? memory?

As the client appears to be synchronous, the setup rate for the first connect with clean session false is very slow. Following setups are fast. So the rate up to 60k should be fast, as you already have the sessions up to that point.  After that, session setup gets slower again. There is some sort of contention in effect that slows down register operations, and any of those delays is synchronously given back to your client.

So, we have to find the reason for that.

**Comment by Yongke** [comment] 2016-06-28 04:14
Hi, @ioolkos 

Sorry for that I did not find anything interesting new, except "stop due to keepalive expired".
Can you somehow reproduce this at your side? I am wondering if it's a generic problem or just for my specific env.

**Comment by ioolkos** [comment] 2016-06-28 07:41
I somehow confirmed this.
I see connection setup latency spike at around 60k clean session false connections for an Amazon 4 core.

I do not understand the issue right now. But it seems to me that it's not your environment or client.

**Comment by ioolkos** [comment] 2016-06-28 08:48
OK, we're rate limiting us to starvation here:
 `{plumtree_jobs_opts, [{regulators, [{counter,[{limit, 20}]}]}]}`, in `vmq_server.app.src`

I set this to 200 and can make 100k clean session subs on a 4 core. It's a setting that needs a recompile unfortunately.

**Comment by Yongke** [comment] 2016-06-28 09:00
Really really good news ;-) Thanks very much. 
So will you make it configurable?
As well as disable 'report_queue_stats' via configuration to get the ultimate performance.  ;-)

And when the next release coming?

**Comment by ioolkos** [comment] 2016-06-28 10:03
Thanks for finding this issue.

We have to think a little about the `plumtree_jobs_opts` as it basically protects plumtree performance. So opening this up might allow to shoot oneself in the foot in other ways...
But yeah, might end up making it configurable.

We have this PR in progress on more exo stuff: https://github.com/erlio/vmq_server/pull/64

Thanks again for your suggestions & patience overall ;)

**Comment by ioolkos** [comment] 2016-06-28 12:55
Here's a little secret:

If you place a file called `advanced.config` in the `etc` folder (same place where your `vernemq.conf` is), 
you can override app settings directly.

these are not recommended values, just an example:
```erlang
[{vmq_server, [

{plumtree_jobs_opts, [{regulators,
		     [{counter,[{limit, 200}]}]}]},
{tcp_listen_options, [		   
            {nodelay, true},
            {linger, {true, 0}}, 
            {send_timeout, 30000}, 
            {send_timeout_close, true},
	    {sndbuf, 64000},
	    {recbuf, 64000}
        ]}]}].
```

**Comment by dergraf** [comment] 2016-07-15 06:57
@Yongke what is the status on this issue?

**Comment by larshesel** [comment] 2016-07-22 06:48
Hi @Yongke please try out the VerneMQ 0.13.1 release where we've fixed the 'idle cpu' problem as well as a number of other issues including some performance optimizations for QoS 1 and 2 messages. We'll be looking forward to hear if that works better for you.

Closing this issue for now. Feel free to re-open or file a new issue if needed!

**Closed by larshesel** 2016-07-22 06:48 UTC

**Comment by Yongke** [comment] 2016-07-23 01:06
Thanks again for all of you ;-) I will try the new version.

**Comment by larshesel** [comment] 2016-07-23 07:05
Thank you for using VerneMQ and reporting issues like these. You're helping making VerneMQ better :)
