### ISSUE TITLE
can't auth publish due to chain_exhausted

### ISSUE THREAD

**Issue by piyushgupta27** [erlio/vernemq#789] opened 2018-08-07 09:47 UTC
### Environment
- VerneMQ Version:1.4.1
- OS: Ubuntu 16.04.4 LTS
- Erlang/OTP version (if building from source): 18

Getting following error while publishing from node:
```2018-08-07 08:30:09.729 [error] <0.762.0>@vmq_mqtt_fsm:auth_on_publish:702 can't auth publish [undefined,{[],<<"Piyushs-MacBook-Pro.local36">>},0,[<<"test">>],<<"\e[A\n">>,false] due to chain_exhausted
2018-08-07 08:30:09.729 [warning] <0.762.0>@vmq_ranch:teardown:138 session stopped abnormally due to 'publish_not_authorized_3_1_1'
```

Following are the relevant vernemq.conf settings:
`allow_anonymous = on`
`plugins.vmq_passwd = off`
`plugins.vmq_acl = on`
`vmq_acl.acl_file = /etc/vernemq/vmq.acl`
`vmq_acl.acl_reload_interval = 10`
`erlang.distribution.port_range.minimum = 6000`
`erlang.distribution.port_range.maximum = 7999`

**Comment by larshesel** [comment] 2018-08-07 10:00
Hi @piyushgupta27 

This happens because there is no plugin which can authorize the publication. The plugin systems works such that different plugins can form a chain for validating, for example, publish actions. In this case none of the plugins (in particular the `vmq_acl` plugin) were able to ok the publish and the plugin system returns `chain_exhausted`. 

It's likely an issue with the acl rules for the client in question.

**Comment by larshesel** [comment] 2018-08-07 10:25
what is the output of `vmq-admin plugin show`? Are there other errors interesting things in the logs?

**Comment by piyushgupta27** [comment] 2018-08-07 10:30
```
root@ip-10-6-16-197:/home/ubuntu# vmq-admin plugin show
+------------+-----------+-----------------+---------------------------+
|   Plugin   |   Type    |     Hook(s)     |           M:F/A           |
+------------+-----------+-----------------+---------------------------+
|vmq_plumtree|application|                 |                           |
|  vmq_acl   |application| auth_on_publish | vmq_acl:auth_on_publish/6 |
|            |           |auth_on_subscribe|vmq_acl:auth_on_subscribe/3|
+------------+-----------+-----------------+---------------------------+
```
The only errors logged in error.log files as same as:
```
can't auth publish [undefined,{[],<<"Piyushs-MacBook-Pro.local36">>},0,[<<"test">>],<<"\e[A\n">>,false] due to chain_exhausted
```

**Comment by larshesel** [comment] 2018-08-07 10:53
That's strange, it's not something I can reproduce. @dergraf you have an idea what could be going on here?

**Comment by larshesel** [comment] 2018-08-07 11:04
Could you maybe have two instances of VerneMQ running on the same machine?

**Comment by piyushgupta27** [comment] 2018-08-07 11:08
I dont think so this is the case but is there a way to identify this?

**Comment by larshesel** [comment] 2018-08-07 11:13
You can check with `ps -ef | grep beam.smp` to see if there are multiple vernemq processes running. The console.log and error.log files would be helpful. It would be great if you could stop the broker, remove any logs, restart it and reproduce the issues. Then the logs should be minimal to look through for any issues.

**Comment by piyushgupta27** [comment] 2018-08-07 11:35
`ps -ef | grep beam.smp` command shows only one instance of beam running. 

```vernemq  17344 17341  0 11:13 pts/2    00:00:06 /usr/lib/vernemq/erts-8.3.5.3/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /usr/lib/vernemq -progname vernemq -- -home /var/lib/vernemq -- -boot /usr/lib/vernemq/releases/1.4.1/vernemq -config /var/lib/vernemq/generated.configs/app.2018.08.07.11.13.17.config -setcookie vmq -name VerneMQ@127.0.0.1 -smp enable -vm_args /var/lib/vernemq/generated.configs/vm.2018.08.07.11.13.17.args -pa /usr/lib/vernemq/lib/erlio-patches -- console
root     18308 14436  0 11:32 pts/4    00:00:00 grep --color=auto beam.smp
```

For the logs and the relevant config files, should i share them here or over some support email?

**Comment by larshesel** [comment] 2018-08-07 12:28
Here would be great. Just make sure to anonymize them if they contain any sensitive information.

**Comment by piyushgupta27** [comment] 2018-08-07 12:54
Following settings resolved these errors as well. Not sure what was the actual root cause of the issue. Might be worth debugging?

## Overidden Settings
nodename=VerneMQ2@<MachineIP>
allow_anonymous=on
plugins.vmq_passwd = off
plugins.vmq_acl = on
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10

# Logging
log.console=console

# Port Ranges
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999

# Listener IPs
listener.tcp.default = <MachineIP>:1883
listener.ws.default = <MachineIP>:8080
listener.vmq.clustering = <MachineIP>:44053
listener.http.metrics = <MachineIP>:8888

**Comment by larshesel** [comment] 2018-08-14 08:52
Hi @piyushgupta27 , were you already running vernemq as a cluster? In that case if cluster communication wasn't working correctly then this is seen as a netsplit and vernemq by default chooses consistency over availability which means it has to reject clients when they're connecting. See the `allow_xxx_during_netsplit` configs in the `vernemq.conf` file as well as http://vernemq.com/docs/clustering/netsplits.html.

Could that be it?

**Comment by larshesel** [comment] 2018-08-17 08:20
Closing this - if you have more information it would be great to understand what caused this to begin with - feel free to add more comments or reopen.

**Closed by larshesel** 2018-08-17 08:20 UTC
