### ISSUE TITLE
failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by mao2080** [erlio/vernemq#534] opened 2017-10-31 03:57 UTC
### Environment

vernemq's config as:

allow_anonymous = on
listener.ws.default = 0.0.0.0:8882

javasrcipt code:

var websocket;
			var path = "ip:8882";
			var uid = "client-001";
			if ('WebSocket' in window) {
				websocket = new WebSocket("ws://" + path);
			} else if ('MozWebSocket' in window) {
				websocket = new MozWebSocket("ws://" + path + "/ws"+uid);
			} else {
				websocket = new SockJS("http://" + path + "/ws/sockjs"+uid);
			}
			websocket.onopen = function(event) {
				console.log("WebSocket:connection");
				console.log(event);
			};
			websocket.onmessage = function(event) {
				var data=JSON.parse(event.data);
				console.log("WebSocket:rev",data);
				var textCss=data.from==-1?"sfmsg_text":"fmsg_text";
				$("#content").append("<div class='fmsg'><label class='name'>"+data.fromName+"&nbsp;"+data.date+"</label><div class='"+textCss+"'>"+data.text+"</div></div>");
				scrollToBottom();
			};
			websocket.onerror = function(event) {
				console.log("WebSocket:error ");
				console.log(event);
			};
			websocket.onclose = function(event) {
				console.log("WebSocket:closed");
				console.log(event);
			}
#```
## Expected behavior

connection success

### Actual behaviour

connection fail

If you know how to deal with it, please help me, thank you！

**Comment by larshesel** [comment] 2017-10-31 07:16
Hi,

It's hard to say what the issue could be, so I can only recommend you to try to gather more information and that way maybe find a lead to the cause. My guess is some kind of connectivity and or client issue. Can you test with another websocket client? Can you verify connectivity to the broker from your client machine with a non-websocket client that you can connect to a non-websocket listener?

For me the Paho JS client has worked well (https://eclipse.org/paho/clients/js/).

**Comment by mao2080** [comment] 2017-10-31 07:53
@larshesel  Thank you!
I've tried  mqttws31.js.
But there was an error，The chrome console log is :
979 WebSocket connection to 'ws://ip:8882/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by larshesel** [comment] 2017-10-31 08:37
This means there's a connectivity issue. This could be due to a number of different issues, either you really cannot reach the specified port over the network or you have configured VerneMQ incorrectly.

Try to check with telnet or some other tool that you really can connect (on a TCP level) to the websocket port of VerneMQ.

As the github tracker is to report errors, bugs and defects and not support, I'm closing this. For these kind of questions I'd recommend the slack channel https://slack-invite.vernemq.com/.

**Closed by larshesel** 2017-10-31 08:37 UTC

**Comment by mao2080** [comment] 2017-10-31 11:03
@larshesel 
Thank you,I've solved this problem. But there's another problem.
Java and javascript both subscribe the same topic "a/b/c",when use Java publish a message(tcp://172.24.24.67:1883), Java can receive, but the javascript(ws://172.24.24.67:8882) cannot receive the message.Can you help me?

**Comment by larshesel** [comment] 2017-10-31 11:57
You should consult the documentation for the specific clients you're using to figure out how they work and should be used or ask in the forums for those clients for help.

**Comment by mao2080** [comment] 2017-11-07 03:51
@larshesel Thank you,I've solved this problem.
