### ISSUE TITLE
[warning] got unknown message reconnect for node?

### ISSUE THREAD

**Issue by bayuemu** [erlio/vernemq#35] opened 2015-08-17 07:56 UTC
Cluster  print   got unknown message reconnect for node , [warning] terminate due to remote_node_not_available 
why??

**Comment by dergraf** [comment] 2015-08-17 08:58
my guess is that your clustering setup is messed up. what is the result of ``vmq-admin cluster show``?

**Comment by bayuemu** [comment] 2015-08-17 10:08
if i set listener.vmq.clustering = 192.168.1.121:2222 everything is ok,but i set listener.vmq.clustering = 0.0.0.0:2222  there is error will happen

**Comment by dergraf** [comment] 2015-08-17 10:11
ah ok, then it is a duplicate of issue https://github.com/erlio/vernemq/issues/32?

Are you by chance running on a virtualized setup?

**Comment by dergraf** [comment] 2015-09-01 15:02
@bayuemu what is the state of this issue? Can you close it?

**Comment by dergraf** [comment] 2015-09-07 12:52
I close it, feel free to open it again, once you have some inputs. thanks!

**Closed by dergraf** 2015-09-07 12:52 UTC

**Comment by testark** [comment] 2015-10-29 18:20
@dergraf I'm having this same issue in a two-node setup running in a virtualized environment. Setting `listener.vmq.clustering` to `<ip-address>:44053` on both nodes solved the problem, but I'd prefer not to do this. Is there any other solution? How impact does the environment being virtualized have on this?

**Comment by dergraf** [comment] 2015-10-29 21:08
I understand. I think the problem comes from the virtualized network stack.

**Comment by funwun** [comment] 2017-04-13 08:54
I get this issue in vmware
