### ISSUE TITLE
Sessions vanish from `vmq-admin session show` with `--peer_host`

### ISSUE THREAD

**Issue by trehn** [erlio/vernemq#542] opened 2017-11-21 12:59 UTC
### Environment

- VerneMQ Version: 1.2.1, 1.2.2, 1.2.3
- OS: Docker

### Steps to reproduce

Using `--client_id --is_online --peer_host` I just get a few offline sessions. But I have a client connected! Where is it?

```
$ docker exec -it vernemq vmq-admin session show --client_id --is_online --peer_host
+--------------------------------+---------+---------+
|           client_id            |is_online|peer_host|
+--------------------------------+---------+---------+
|d4ac947cfa0fe5e8fae8e7a10cecd6e1|  false  |  null   |
|cf7ab0caba1cc99cde217634f68826c8|  false  |  null   |
|6055bd62e7100c1566d2aa74149d2fa3|  false  |  null   |
|848c54637ad78c4add73479edaf8da94|  false  |  null   |
|258e04ed88f6398abe703d12c5a35d2e|  false  |  null   |
|957bbf3feee5cd3b0bbdfbdc37cce42b|  false  |  null   |
+--------------------------------+---------+---------+
```

As soon as I remove `--peer_host`, I can see my connected client ("beancounter"):

```
$ docker exec -it vernemq vmq-admin session show --client_id --is_online
+--------------------------------+---------+
|           client_id            |is_online|
+--------------------------------+---------+
|d4ac947cfa0fe5e8fae8e7a10cecd6e1|  false  |
|cf7ab0caba1cc99cde217634f68826c8|  false  |
|          beancounter           |  true   |
|6055bd62e7100c1566d2aa74149d2fa3|  false  |
|848c54637ad78c4add73479edaf8da94|  false  |
|258e04ed88f6398abe703d12c5a35d2e|  false  |
|957bbf3feee5cd3b0bbdfbdc37cce42b|  false  |
+--------------------------------+---------+
```

The client is connecting from another container in the same docker network (created by docker-compose).

**Comment by trehn** [comment] 2017-11-21 17:32
console.log says
```
[warning] <0.722.0>@vmq_ql_query:select:199 Subquery failed due to timeout
```
Every time I run `vmq-admin session show --client_id --is_online --peer_host`.
Nothing in the others.

**Comment by larshesel** [comment] 2017-11-28 19:45
Haven't figured out what this is caused by exactly - but we did a number of fixes to the `vmq-admin session show` command (especially in the filters) which we'll hopefully release with VerneMQ 1.2.2 one of the next days.

I wonder if your issue could be somehow dns related. I have a suspicion that vernemq (erlang) will try to look up the dns record of the client peer_host when we ask the socket for it. If this blocks this would block the query mechanism and a timeout would happen...

**Comment by dergraf** [comment] 2017-11-28 20:31
@larshesel peer_host should be extracted at connection time and is storef inside the session fsm state... so query shouldnt trigger a dns lookup

**Comment by larshesel** [comment] 2017-12-05 09:24
@dergraf we do call `inet:gethostbyaddr/1` when fetching the info from `vmq_mqtt_fsm` which can result in a dns lookup. We should move this into the initialization of the fsm instead.

@trehn could you try and run your command with a higher timeout value (like 1000ms) as in the example below? 

```
vmq-admin session show --client_id --is_online --peer_host --rowtimeout=1000
```

**Comment by trehn** [comment] 2017-12-05 09:40
@larshesel No change, even with `--rowtimeout=10000`.

**Comment by larshesel** [comment] 2017-12-05 18:19
As we're quite sure the issue is indeed related to the `gethostbyaddr/1` call we've made a fix for that and no longer try to translate IP-addresses into hostnames. This will be part of the next vernemq release. Let us know if you still have issues when it comes out.

**Comment by trehn** [comment] 2018-01-10 15:03
@larshesel Unfortunately, the issue persists after updating to 1.2.3. Same symptoms.

**Comment by larshesel** [comment] 2018-02-21 06:52
Hi @trehn I guess this is still an issue... When you tested 1.2.3 were all nodes upgrade to 1.2.3 or were some of the cluster nodes still earlier versions?

**Comment by trehn** [comment] 2018-02-21 06:53
@larshesel I only run a single node.

**Comment by larshesel** [comment] 2018-02-21 06:57
And it only happens for the client which you connect from another docker instance? Which MQTT client is used? Are there any other differences between the clients which is missing and the ones that aren't except that the one that's missing is coming from a specific docker instance? What happens if that client connects from somewhere else, does it work then?

**Comment by trehn** [comment] 2018-02-21 09:28
It happens to all clients, from within Docker and from outside. These are the connections:

```
root@2839697331e3:/# netstat -atvpn | grep 8080
tcp        0      0 172.18.0.7:8080         0.0.0.0:*               LISTEN      -
tcp        0      0 172.18.0.7:8080         172.18.0.1:50052        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:60212        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:39812        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:39708        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:39892        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:41838        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:44896        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:41886        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:35060        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:48842        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:46630        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:35806        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.3:34500        ESTABLISHED -  # THIS ONE IS FROM ANOTHER CONTAINER
tcp        0      0 172.18.0.7:8080         172.18.0.1:39696        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:48148        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:40532        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:37974        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:41868        ESTABLISHED -
tcp        0      0 172.18.0.7:8080         172.18.0.1:39692        ESTABLISHED -
```

Using `dig`, I get a PTR record for 172.18.0.3 (automatically provided by Docker), but not 172.18.0.1. The query for 172.18.0.1 fails without blocking for any significant amount of time:

```
root@2839697331e3:/# dig -x 172.18.0.1

; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> -x 172.18.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52885
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;1.0.18.172.in-addr.arpa.	IN	PTR

;; Query time: 14 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Wed Feb 21 09:24:04 UTC 2018
;; MSG SIZE  rcvd: 52
```

Clients affected are the Paho ones for Python, JavaScript and Java.

Note that the clients that were visible in the OP were offline sessions. We don't use these anymore, so by now I either get an empty list (with `--peer_host`) or the correct list of all clients (without `--peer_host`). 

Also note the time it takes the commands to complete:
```
root@2839697331e3:/# time vmq-admin session show --client_id --is_online --peer_host

real	0m2.322s
user	0m0.216s
sys	0m0.140s

root@2839697331e3:/# time vmq-admin session show --client_id --is_online
+--------------------------------+---------+
|           client_id            |is_online|
+--------------------------------+---------+
|a0106f05972b1361e8605dbd651d0d31|  true   |
|be30590ff9575fa93d13e6c289b11de4|  true   |
|bef002b698d127af74298358c3e77ba3|  true   |
|541fc67e054ba0296c73e8d33f6b02dc|  true   |
|b7d7f16f92ed2b6891fa40c2ad6f76c8|  true   |
|8c6d01eb961f595276ca00ec58197afa|  true   |
|3299ebd44949cb71cee8315175494f10|  true   |
|          beancounter           |  true   |
|557c14cc14da2174503ebfd969129472|  true   |
|3cbf7da6967f84df91813e18e6cc40a0|  true   |
|e8812df876595455dfc7b89acd9f0599|  true   |
|49c0143f6ccedf217d0ca83921e72796|  true   |
|f37ac69abf9f06ae5f7f8eeebf89aacd|  true   |
|7ffc988bb3eb16179036887756938c56|  true   |
|24d41034b04af1a5aa746df219f7edb6|  true   |
|415a0a08701e61177a5460504e600d3a|  true   |
|d31a2e3c243af5df540822b2c7ccde73|  true   |
|bfaae40a34387378b6cee60215c6b9f8|  true   |
|43cdaace865b0550d6a816ea7cc9f2ab|  true   |
+--------------------------------+---------+


real	0m0.399s
user	0m0.236s
sys	0m0.120s
```

I get one line of "Subquery failed due to timeout" for each connected client, nothing else in logs.

**Comment by larshesel** [comment] 2018-02-21 12:47
Ok, let's see if we can get a bit closer and see what the actual errors is when the `peer_host` lookup is done. First we need to obtain the session process id of one the sessions where the `peer_host` doesn't work like this:

```
vmq-admin session show --session_pid --client_id
+-----------+-----------+
| client_id |session_pid|
+-----------+-----------+
|test-client| <0.404.0> |
+-----------+-----------+
```

Afterwards attach to VerneMQ using `vernemq attach` command and in the shell try the following (replacing the actual pid into command):
```
(VerneMQ@127.0.0.1)1> vmq_mqtt_fsm:info(c:pid(0,404,0), [peer_host]).
{ok,[{peer_host,<<"127.0.0.1">>}]}
```

What happens when you do this?

To quit the Erlang shell press "Ctrl-g q".

**Comment by larshesel** [comment] 2018-02-21 12:49
To be completely certain of the VerneMQ version, could you output what `vernemq version` returns?

**Comment by trehn** [comment] 2018-02-21 12:56
```
root@2839697331e3:/# vernemq version
1.2.3
```

The `vmq_mqtt_fsm:info` call just hangs and doesn't return (I aborted it after ~70 seconds). Happens for both the Docker-internal connections (which do have a PTR as noted earlier) and external connections (which do not).

Nothing in logs.

**Comment by larshesel** [comment] 2018-02-21 13:15
Another experiment, can you in the erlang shell do

```
> rp(sys:get_state(c:pid(0,402,0)).
```

With the correct session pid inserted?

For my process it returns something like:

```
{st,#Port<0.9138>,<<>>,vmq_mqtt_fsm,
    {connected,{state,1,
                      {[],<<"test-client">>},
                      undefined,#{},[],
                      {{127,0,0,1},32940},
                      <<"test-user">>,60,undefined,
                      {[],[]},
                      true,3,<0.405.0>,
                      {1519,218778,690843},
                      {1519,218658,536484},
                      true,100,prefer_local,20,0,20000,false,vmq_reg_trie,
                      {cap_settings,false,false,false,false},
                      undefined}},
    {tcp,tcp_closed,tcp_error},
    [],false,<0.351.0>}
ok
```

From which I can see the peer IP and port: `{{127,0,0,1},32940}`. Can you then do take the IP part and do the following in the shell:

```
> inet:ntoa({127,0,0,1}).
"127.0.0.1"
```

How does that look in your case?

**Comment by trehn** [comment] 2018-02-21 13:20
```
(VerneMQ@172.18.0.7)1> rp(sys:get_state(c:pid(0,791,0))).
** exception exit: {timeout,{sys,get_state,[<0.791.0>]}}
     in function  sys:send_system_msg/2 (sys.erl, line 303)
     in call from sys:get_state/1 (sys.erl, line 112)

(VerneMQ@172.18.0.7)2> inet:ntoa({172,18,0,1}).  # just guessing that would've been the result
"172.18.0.1"
```

**Comment by larshesel** [comment] 2018-02-21 13:25
This is an indication that the session process is not responsive anymore and is blocked for some reason. What does the following return?:

```
> process_info(c:pid(0,791,0)).
```

**Comment by trehn** [comment] 2018-02-21 13:28
```
(VerneMQ@172.18.0.7)1> process_info(c:pid(0,791,0)).
[{current_function,{cowboy_websocket,handler_loop,4}},
 {initial_call,{cowboy_protocol,init,4}},
 {status,waiting},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.477.0>,#Port<0.10108>]},
 {dictionary,[{socket_open,<<>>},
              {max_msg_size,524288},
              {mqtt_publish_sent,<<>>},
              {mqtt_pingresp_sent,<<>>},
              {mqtt_pingreq_received,<<>>},
              {mqtt_suback_sent,<<>>},
              {mqtt_subscribe_received,<<>>},
              {bytes_sent,<<>>},
              {mqtt_connack_accepted_sent,<<>>},
              {mqtt_connect_received,<<>>},
              {bytes_received,<<>>},
              {rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,
                            type => exsplus,uniform => #Fun<rand.9.41921595>,
                            uniform_n => #Fun<rand.10.41921595>},
                          [68127008860634340|219891682082609665]}},
              {mqtt_publish_received,<<>>},
              {mqtt_pubcomp_sent,<<>>},
              {mqtt_pubrel_received,<<>>},
              {mqtt_pubrec_sent,<<>>},
              {guid,{{...},...}}]},
 {trap_exit,false},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.68.0>},
 {total_heap_size,2595},
 {heap_size,2586},
 {stack_size,14},
 {reductions,9749363},
 {garbage_collection,[{max_heap_size,#{error_logger => true,kill => true,size => 0}},
                      {min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,0},
                      {minor_gcs,0}]},
 {suspending,[]}]
```

**Comment by larshesel** [comment] 2018-02-21 13:31
Ah, I  think the websocket processes doesn't support the sys:get_state/1 call, so that's probably fine. I suppose `vmq_mqtt_fsm:info(c:pid(0,791,0), [peer_port]).` works?

**Comment by trehn** [comment] 2018-02-21 13:32
No, that one just blocks indefinitely.

**Comment by larshesel** [comment] 2018-02-21 13:36
ok - thanks - I'm now able to reproduce this here, it seems to be an issue with websockets - until now I'd just focused on normal tcp connections where I couldn't reproduce this issue. I'm looking into it.

**Comment by trehn** [comment] 2018-02-21 13:37
Cool, thanks!

**Comment by larshesel** [comment] 2018-02-21 13:58
I created a fix in #614 - it'll be included in 1.4.0 and perhaps in 1.3.1 if we decide to do a bugfix release.

**Comment by trehn** [comment] 2018-02-21 14:05
Thank you very much!

**Comment by larshesel** [comment] 2018-02-21 14:08
Thank you for the help - and I apologize for the low priority this have had. But I'm pretty sure we found the root cause this time!

**Closed** 2018-02-22 07:34 UTC
