### ISSUE TITLE
unable to receive published messages

### ISSUE THREAD

**Issue by jeremylink** [erlio/vernemq#376] opened 2017-05-03 22:48 UTC
I'm using VMQ inside the official Docker container and am having issues with receiving published messages.

I've had this working in the past, so am unclear why it has stopped working on multiple environments.

I'm not sure if:
- there is a mystery setting in the conf file that matters
- the version matters (have both the latest and version before that running)
- there is something wrong with my webhook authorization response

I'm running webhooks for authentication/authorization:
- my auth server receives the auth_on_register and the client is able to connect
- my auth server receives the auth_on_publish and auth_on_subscribe and things "seem" to work
- none of the published messages are received by my subscriber

These are samples of the messages my auth server sends back to the broker:
**auth_on_register** response:
 {"result":"ok","modifiers":{"mountpoint":"newmountpoint","client_id":"1391f03a529f46c386aa09139698da1e","clean_session":true,"max_message_size":65535,"max_message_rate":100,"max_inflight_messages":100,"retry_interval":100,"upgrade_qos":false}}
-> this works fine, this also logs a line in the broker log file
**auth_on_subscribe** response:
{"result":"ok","modifiers":{"topics":[{"topic":"foo/bar/#","qos":1}],"payload":"rewritten payload","retain":true,"reg_view":"reg_view","mountpoint":"newmountpoint"}}
**auth_on_publish** response:
{"result":"ok","modifiers":{"topic":"foo/bar/blah","qos":1,"payload":"rewritten payload","retain":true,"reg_view":"reg_view","mountpoint":"newmountpoint"}}

Part of my concern is that there is no documentation on what the response messages should look like.
Which fields are required and what do they do.
I've tried various values for the response field to no avail.

These are some of the settings I have in my conf file:
allow_anonymous = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on

vmq_webhooks.webhook_auth_on_register.hook = auth_on_register
vmq_webhooks.webhook_auth_on_register.endpoint = http://127.0.0.1:1884/app/micro-service/
vmq_webhooks.webhook_auth_on_publish.hook = auth_on_publish
vmq_webhooks.webhook_auth_on_publish.endpoint = http://127.0.0.1:1884/app/micro-service/
vmq_webhooks.webhook_auth_on_subscribe.hook = auth_on_subscribe
vmq_webhooks.webhook_auth_on_subscribe.endpoint = http://127.0.0.1:1884/app/micro-service/

In some instances I set these in the file. In other cases I pass them as environment variables to the container at startup:
########## Start ##########
vmq_webhooks.webhook_auth_on_publish.hook=auth_on_publish
plugins.vmq_webhooks=on
vmq_webhooks.webhook_auth_on_register.hook=auth_on_register
vmq_webhooks.webhook_auth_on_subscribe.hook=auth_on_subscribe
vmq_webhooks.webhook_auth_on_register.endpoint=http://blah.com:1884/app/micro-service
vmq_webhooks.webhook_wakeup.hook=on_client_wakeup
vmq_webhooks.webhook_auth_on_subscribe.endpoint=http://blah.com:1884/app/micro-service
plugins.vmq_acl=off
plugins.vmq_passwd=off
log.console.level=debug
vmq_webhooks.webhook_wakeup.endpoint=http://blah.com:1884/app/micro-service
allow_anonymous=off
vmq_webhooks.webhook_auth_on_publish.endpoint=http://blah.com:1884/app/micro-service
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.17.0.2:1883
listener.ws.default = 172.17.0.2:8080
listener.vmq.clustering = 172.17.0.2:44053
listener.http.metrics = 172.17.0.2:8888

**Comment by ioolkos** [comment] 2017-05-04 06:58
Thanks for documenting this @jeremylink.

@larshesel, @dergraf could you look here if the webhook response format looks valid? note newmountpoint and retain true.

Futhermore
- Is this a cluster? 
- is the cluster state OK? (unpartitioned)
- does it work if subscriber and publisher are connected to the same node?
- Verne logging anything special?

In general I'd start looking into this from the subscriber end. Most of the time when a message is not delivered, there is either no subscription, or possibly some synchronisation delay in the subscriber store. Are you able to trace that your clients receive SUBACKS?

**Comment by jeremylink** [comment] 2017-05-04 07:05
This is a single node broker.

The only log I see in console.log (debug level) is:
2017-05-04 07:04:16.328 [debug] <0.4021.0>@vmq_queue:state_change:898 transition from offline --> online because of add_session

I do not see log messages for the publish or subscribe authorization.

**Comment by larshesel** [comment] 2017-05-04 09:21
Hi @jeremylink could I get you to do a `vmq-admin trace client client-id=<the client id>`? That would show what happens internally in VerneMQ for that client session. Maybe that can reveal the problem.

**Comment by EnCl** [comment] 2017-05-04 10:20
Hi
I'm facing a similar problem. I'm using the same configuration as above.
For me the result of **docker exec vernemq1 vmq-admin trace client client-id=JavaSample2s**
is the following:

New session with PID <7244.477.0> found for client "JavaSample2s"
<7244.477.0> MQTT RECV: CID: "JavaSample2s" CONNECT(clientid: JavaSample2s ver: 4, user: abcd230, pass: ab, cs: 1, ka: 60)
<7244.477.0> Calling auth_on_register({{172,17,0,1},39646},{[],
                                                            <<"JavaSample2s">>},abcd230,ab,true)
<7244.477.0> Hook returned "ok" with modifiers:
    upgrade_qos: false
    retry_interval: 100ms
    max_inflight_messages: 100 msgs
    max_message_rate: 100 msgs/s
    max_message_size: 65535 bytes
    clean_session: true
    {client_id,<<"JavaSample2s">>}
    {mountpoint,"newmountpoint"}
<7244.477.0> MQTT SEND: CID: "JavaSample2s" CONNACK(sp: 0, rc: 0)
RPC to 'VerneMQ@172.17.0.2' failed: {'EXIT',
                                     {function_clause,
                                      [{vmq_tracer,f,
                                        [0],
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,557}]},
                                       {vmq_tracer,format_mqtt_,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,512}]},
                                       {vmq_tracer,format_mqtt,5,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,486}]},
                                       {vmq_tracer,format_trace,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,442}]},
                                       {vmq_tracer,handle_info,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,216}]},
                                       {gen_server,try_dispatch,4,
                                        [{file,"gen_server.erl"},{line,601}]},
                                       {gen_server,handle_msg,5,
                                        [{file,"gen_server.erl"},{line,667}]},
                                       {proc_lib,init_p_do_apply,3,
                                        [{file,"proc_lib.erl"},{line,247}]}]}}

I see that something failed, but I don't see the cause and solution.

**Comment by ioolkos** [comment] 2017-05-04 10:28
Thanks! Can you try with a retry higher than 100ms? like 20 seconds or so?

Cf. https://github.com/erlio/vernemq/issues/298

**Comment by EnCl** [comment] 2017-05-04 11:02
I changed the retry to 20 seconds. The result is the same;

New session with PID <7244.807.0> found for client "JavaSample2s"
<7244.807.0> MQTT RECV: CID: "JavaSample2s" CONNECT(clientid: JavaSample2s ver: 4, user: abcd230, pass: ab, cs: 1, ka: 60)
<7244.807.0> Calling auth_on_register({{172,17,0,1},39652},{[],
                                                            <<"JavaSample2s">>},abcd230,ab,true)
<7244.807.0> Hook returned "ok" with modifiers:
    upgrade_qos: false
    retry_interval: 20000ms
    max_inflight_messages: 100 msgs
    max_message_rate: 100 msgs/s
    max_message_size: 65535 bytes
    clean_session: true
    {client_id,<<"JavaSample2s">>}
    {mountpoint,"newmountpoint"}
<7244.807.0> MQTT SEND: CID: "JavaSample2s" CONNACK(sp: 0, rc: 0)
RPC to 'VerneMQ@172.17.0.2' failed: {'EXIT',
                                     {function_clause,
                                      [{vmq_tracer,f,
                                        [0],
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,557}]},
                                       {vmq_tracer,format_mqtt_,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,512}]},
                                       {vmq_tracer,format_mqtt,5,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,486}]},
                                       {vmq_tracer,format_trace,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,442}]},
                                       {vmq_tracer,handle_info,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,216}]},
                                       {gen_server,try_dispatch,4,
                                        [{file,"gen_server.erl"},{line,601}]},
                                       {gen_server,handle_msg,5,
                                        [{file,"gen_server.erl"},{line,667}]},
                                       {proc_lib,init_p_do_apply,3,
                                        [{file,"proc_lib.erl"},{line,247}]}]}}

**Comment by larshesel** [comment] 2017-05-04 11:24
I can see you're overriding the mountpoint. Unless you're sure you need that remove that override and retryOn 4 May 2017 13:02, EnCl <notifications@github.com> wrote:I changed the retry to 20 seconds. The result is the same;
New session with PID <7244.807.0> found for client "JavaSample2s"
<7244.807.0> MQTT RECV: CID: "JavaSample2s" CONNECT(clientid: JavaSample2s ver: 4, user: abcd230, pass: ab, cs: 1, ka: 60)
<7244.807.0> Calling auth_on_register({{172,17,0,1},39652},{[],
<<"JavaSample2s">>},abcd230,ab,true)
<7244.807.0> Hook returned "ok" with modifiers:
upgrade_qos: false
retry_interval: 20000ms
max_inflight_messages: 100 msgs
max_message_rate: 100 msgs/s
max_message_size: 65535 bytes
clean_session: true
{client_id,<<"JavaSample2s">>}
{mountpoint,"newmountpoint"}
<7244.807.0> MQTT SEND: CID: "JavaSample2s" CONNACK(sp: 0, rc: 0)
RPC to 'VerneMQ@172.17.0.2' failed: {'EXIT',
{function_clause,
[{vmq_tracer,f,
[0],
[{file,
"/opt/vernemq/distdir/1.0.0/build/default/lib/vmq_server/src/vmq_tracer.erl"},
{line,557}]},
{vmq_tracer,format_mqtt,2,
[{file,
"/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
{line,512}]},
{vmq_tracer,format_mqtt,5,
[{file,
"/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
{line,486}]},
{vmq_tracer,format_trace,2,
[{file,
"/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
{line,442}]},
{vmq_tracer,handle_info,2,
[{file,
"/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
{line,216}]},
{gen_server,try_dispatch,4,
[{file,"gen_server.erl"},{line,601}]},
{gen_server,handle_msg,5,
[{file,"gen_server.erl"},{line,667}]},
{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,247}]}]}}

**Comment by EnCl** [comment] 2017-05-04 11:33
New session with PID <7244.612.0> found for client "JavaSample2s"
<7244.612.0> MQTT RECV: CID: "JavaSample2s" CONNECT(clientid: JavaSample2s ver: 4, user: abcd230, pass: ab, cs: 1, ka: 60)
<7244.612.0> Calling auth_on_register({{172,17,0,1},39676},{[],
                                                            <<"JavaSample2s">>},abcd230,ab,true)
<7244.612.0> Hook returned "ok" with modifiers:
    upgrade_qos: false
    retry_interval: 26000ms
    max_inflight_messages: 100 msgs
    max_message_rate: 100 msgs/s
    max_message_size: 65535 bytes
    clean_session: true
    {client_id,<<"JavaSample2s">>}
<7244.612.0> MQTT SEND: CID: "JavaSample2s" CONNACK(sp: 0, rc: 0)
RPC to 'VerneMQ@172.17.0.2' failed: {'EXIT',
                                     {function_clause,
                                      [{vmq_tracer,f,
                                        [0],
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,557}]},
                                       {vmq_tracer,format_mqtt_,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,512}]},
                                       {vmq_tracer,format_mqtt,5,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,486}]},
                                       {vmq_tracer,format_trace,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,442}]},
                                       {vmq_tracer,handle_info,2,
                                        [{file,
                                          "/opt/vernemq/distdir/1.0.0/_build/default/lib/vmq_server/src/vmq_tracer.erl"},
                                         {line,216}]},
                                       {gen_server,try_dispatch,4,
                                        [{file,"gen_server.erl"},{line,601}]},
                                       {gen_server,handle_msg,5,
                                        [{file,"gen_server.erl"},{line,667}]},
                                       {proc_lib,init_p_do_apply,3,
                                        [{file,"proc_lib.erl"},{line,247}]}]}}

**Comment by ioolkos** [comment] 2017-05-04 11:45
Thanks. Does the message arrive, even if the tracer crashes?
(The tracer is crashing here, because it seems to want to call into another cluster node, which is currently not possible I think.)

**Comment by EnCl** [comment] 2017-05-04 11:50
I have a client which subscribed and is listening for received messages, but nothing is received. The client which sends the message says that the delivery of the message has been completed.

**Comment by larshesel** [comment] 2017-05-04 12:21
@ioolkos the tracer cannot influence the sending of messages. The tracer issue that's seen should not be present in 1.0.1 (see the changelog for details)On 4 May 2017 1:50 p.m., EnCl <notifications@github.com> wrote:I have a client which subscribed and is listening for received messages, but nothing is received. The client which sends the message says that the delivery of the message has been completed.

**Comment by jeremylink** [comment] 2017-05-04 14:09
You say version 1.0.1? Is there a Docker image with that version? I'm assuming not since the latest tag is 1.0.0. Is there a list of Docker image tags that I can reference?
Should I try out using one of the binaries or building/deploying the latest code instead of using the Docker image?

Also you mention that the 'mountpoint' should not be overwridden; is there a document that list the return options and what each of them means along with valid values?

**Comment by ioolkos** [comment] 2017-05-04 14:38
Current documentation for Webhook plugins is here: https://vernemq.com/docs/plugindevelopment/webhookplugins.html
Unfortunately yes, the docker-image is not yet updated with 1.0.1. Apologies! 
I guess this explains the tracer crash. But not the non-receiving of messages.

@larshesel that mountpoint thing...maybe publisher and subscriber are ending up on different mountpoints here!?

**Comment by larshesel** [comment] 2017-05-04 15:20
Hi @jeremylink @ioolkos please excuse my brevity before - I was answering on my phone. Are you overriding the mountpoint because you need it or because that's what was done in the examples - maybe we need to provide better examples with more explanation? Anyway, I would remove any modifiers I don't explicitly need, including rewriting the mountpoint, to have less moving parts and try to see if we can localize where the problem occurs.

The webhooks functionally supports the same modifiers as described in the plugin development docs: http://vernemq.com/docs/plugindevelopment/ - but we haven't documented them very well - so I guess that's great feedback for us for our backlog.

**Comment by dergraf** [comment] 2017-05-04 15:25
@jeremylink you're right, the docker images are still on `1.0.0` building and pushing `1.0.1` now.

**Comment by dergraf** [comment] 2017-05-04 15:31
Done!

**Comment by jeremylink** [comment] 2017-05-04 15:44
Do the Docker images have anything other than 'latest'? Is there a list of available tags?

**Comment by jeremylink** [comment] 2017-05-04 15:47
Most of the values returned are modeled after the example - no real understanding on my part as to what they do.
The regular plugin documentation does list all of the available options, but there doesn't appear to be any description for actual purpose.

**Comment by jeremylink** [comment] 2017-05-04 16:06
I pulled the latest Docker image and initial tests show things working. Much better!

I will experiment around with different response options, but still would be good some documentation around what each of them means.

**Comment by jeremylink** [comment] 2017-05-04 16:17
And yes, I needed to remove the response options to get it to work (mountpoint et al found in the examples).

**Comment by dergraf** [comment] 2017-05-04 17:12
@jeremylink you can see the available tags on https://hub.docker.com/r/erlio/docker-vernemq/tags/

**Comment by dergraf** [comment] 2017-05-05 15:01
How are you publishing?

**Comment by EnCl** [comment] 2017-05-05 18:14
The publish uses a webhook.

I've got this working by setting all options for the auth_on_register response which is also enabled on my system.

**Comment by larshesel** [comment] 2017-05-09 12:33
If I understood it correctly it is working for you @jeremylink, right? I'll close this, then. @EnCl if you still have a problem, please open a separate issue. It's very hard to try to solve and diagnose two issues in the same thread (even though they may be related).

**Closed by larshesel** 2017-05-09 12:33 UTC
