### ISSUE TITLE
node down and leave node problem

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#193] opened 2016-08-29 07:17 UTC
Hi!

1. Is it right when i use ```./bin/vernemq stop``` to stop one node of cluster, and every client can not login? 
the VerneMQ log ```2016-08-29 14:53:35.394 [warning] <0.2751.0>@vmq_mqtt_fsm:check_user:532 can't register client {[],<<"2">>} due to reason not_ready```

1. When one node down, my client can not login, so i want to remove the down node from cluster,
    ```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster leave node='VerneMQ@192.168.3.82'
RPC to 'VerneMQ@192.168.3.83' failed: {'EXIT',
                                       {function_clause,
                                        [{vmq_reg,fix_dead_queue,
                                          [{[],<<"2">>},
                                           [{[<<"hello">>],
                                             1,'VerneMQ@192.168.3.83'}],
                                           {['VerneMQ@192.168.3.82'],[],0}],
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_reg.erl"},
                                           {line,374}]},
                                         {plumtree_metadata,fold_it,3,
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/plumtree/src/plumtree_metadata.erl"},
                                           {line,130}]},
                                         {vmq_reg,fix_dead_queues,2,
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_reg.erl"},
                                           {line,371}]},
                                         {vmq_server_cli,
                                          '-vmq_cluster_leave_cmd/0-fun-4-',3,
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_server_cli.erl"},
                                           {line,196}]},
                                         {clique_command,run,1,
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/clique/src/clique_command.erl"},
                                           {line,87}]},
                                         {clique,run,1,
                                          [{file,
                                            "/root/hisir/vernemq/_build/default/lib/clique/src/clique.erl"},
                                           {line,130}]},
                                         {rpc,'-handle_call_call/6-fun-0-',5,
                                          [{file,"rpc.erl"},{line,206}]}]}}
```
Here is the problem: Because one node down, my clients can not login and i can not remove the down node correctly.

1. After above, in order to remove the down node correctly, i start the down node, and execute ```leave node``` command
    ```
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.82| true  |
+--------------------+-------+
root@ubuntu:~/hisir/vernemq/_build/default/rel/vernemq# ./bin/vmq-admin cluster status
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@192.168.3.83| true  |
+--------------------+-------+
```
    But the VerneMQ@192.168.3.82 log:
    ```
2016-08-29 15:09:39.386 [warning] <0.351.0>@vmq_reg:publish:303 can't publish to remote node 'VerneMQ@192.168.3.83' due to 'not_found'
```
    The VerneMQ@192.168.3.83 log:
    ```
2016-08-29 15:09:38.099 [info] <0.4067.0>@plumtree_metadata_exchange_fsm:exchange:160 completed metadata exchange with 'VerneMQ@192.168.3.82'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
```

**Comment by dcy** [comment] 2016-08-29 08:06
Hi!
The first question i found it in https://github.com/erlio/vernemq/issues/32

**Comment by larshesel** [comment] 2016-08-30 08:10
Hi @dcy - I can reproduce step 2 on our current master - we're looking into it - thank you for reporting. About issue 3 I'm not sure it's important as you shouldn't have gotten into this situation after step 2.

**Comment by dcy** [comment] 2016-08-30 08:25
@larshesel  Thanks!
By the way, about step 1, If the node1 of Cluster's computer is power off and the computer can not power on. What should i do when the rest nodes can not login?

**Comment by larshesel** [comment] 2016-08-30 08:39
The behaviour of not allowing clients to connect when a node ungracefully leaves the cluster (this is the same as a netsplit) is due to the way the MQTT spec is written (which requires that a client can only have one session) - either the node needs to come back or the node needs to be kicked out of the cluster (see http://vernemq.com/docs/clustering/ detailed cluster leave, case B - and in particular the warnings and what that means).

This default behaviour can be changed in the vernemq configuration as described here: http://vernemq.com/docs/clustering/netsplits.html.

**Comment by larshesel** [comment] 2016-08-30 14:27
Hi @dcy. We just pushed a fix for this issue to master - let us know if you're still having any difficulties after upgrading. Thanks a lot for reporting this!

**Closed by larshesel** 2016-08-30 14:27 UTC

**Comment by dcy** [comment] 2016-08-30 16:30
@larshesel Thanks!
By the way, As you said "The behaviour of not allowing clients to connect when a node ungracefully leaves the cluster (this is the same as a netsplit) is due to the way the MQTT spec is written (which requires that a client can only have one session) ". Because can not generate another session in another node, so not allow clients to connect rest nodes. But in another situation, There will be more than one session like https://github.com/erlio/vernemq/issues/180, I think after you fix this https://github.com/erlio/vernemq/issues/180, you should allow the client to connect rest nodes when one node down. And when the node restart or client reconnect, VerneMQ will handle the "migrating queue" like https://github.com/erlio/vernemq/issues/180.
Is it possible?
