### ISSUE TITLE
every version (>=1.0.1) broken on arch linux kernel >4.14

### ISSUE THREAD

**Issue by chopmann** [erlio/vernemq#611] opened 2018-02-16 01:04 UTC
I know it's arch and not supported but docker images are affected too.
### Environment

- VerneMQ Version: source
- OS: arch linux 
- Erlang/OTP version (if building from source):
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [hipe] [kernel-poll:true]
### Expected behavior
app starts
### Actual behaviour
tries to start then crashes

use latest 4.15.x kernel
reproducible with docker ( re-installed docker) every image I found
from source
```
2018-02-16 01:13:18 =CRASH REPORT====
  crasher:
    initial call: plumtree_metadata_leveldb_instance:init/1
    pid: <0.204.0>
    registered_name: []
    exception exit: {{db_open,"IO error: ./data/meta/meta/0/MANIFEST-000001: No such file or directory"},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,349}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [plumtree_metadata_leveldb_instance_sup,plumtree_sup,<0.199.0>]
    message_queue_len: 0
    messages: []
    links: [<0.203.0>]
    dictionary: [{rand_seed,{#{jump => #Fun<rand.16.15449617>,max => 288230376151711743,next => #Fun<rand.15.15449617>,type => exsplus},[146502457060216277|644192836212027]}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 9753
  neighbours:
```
with 4.14.15-1-ARCH it's working.

the error is so obscure it took me hours to finally do the last thing (should have done that the minute i though of it....) kernel downgrade.

Downgraded packages (4.14.15-1):
linux linux-headers acpi_call

**Comment by larshesel** [comment] 2018-02-16 06:24
Hi, thanks for reporting. As this happens when plumtree is starting it is likely an issue with the leveldb code, but it's strange it gets reported as an IO error (that it can't find leveldb files).

As we don't really support arch and none of us are using arch we can't immediately try to help you with this. I've added the 'help wanted' label, maybe someone else will jump in and can help with this.

Sorry to not be of more help right now.

**Comment by chopmann** [comment] 2018-02-16 08:22
Got it working with a previous kernel version for now. Just wanted to let you folks know.
It could be the new Spectre, Meltdown patch series that's breaking things. I'll look what I can do next week.  
Btw great work with the broker! (cheers from cybus)

**Comment by larshesel** [comment] 2018-03-06 10:15
I'm afraid I don't have any really good ideas. The only thing that comes to mind is to check if some step of the compilation silently fails for some reason or maybe check on some other distribution with a newer kernel if it's also reproducible there to get a feeling for if it's a kernel or a distribution issue.

**Comment by ioolkos** [comment] 2018-03-07 10:44
@chopmann @larshesel is it an issue that should go to the OTP team?
or is the MANIFEST file actually not there?

**Comment by troyanov** [comment] 2018-03-08 15:31
Same error with [VerneMQ Vagrantfile](https://github.com/erlio/vernemq/blob/master/Vagrantfile) 

Here is a kernel version:
```
vagrant@vagrant-ubuntu-trusty-64:~$ uname -r 
3.13.0-142-generic
```

**Comment by larshesel** [comment] 2018-03-08 15:51
Ok, so it's likely not related to the kernel version. Can you check as suggested by @ioolkos  if the `MANIFEST-000001` file exists or not and if it does if the user starting VerneMQ has can access and write to those files?

**Comment by chopmann** [comment] 2018-03-08 16:01
@larshesel @ioolkos The file does not exist. I tried "touch MANIFEST-000001" to see if it was just 'forgot to   create' bug, but that did not help either. I'm still pointing at the kernel, maybe not version, but how it was compiled. **I can safely reproduce this bug on ALL Docker Images available** (yours and the community-made ones) as stated on the bug report.

**Comment by larshesel** [comment] 2018-03-08 16:09
I just tried to install the 1.3.0 version:

```
$ docker run --name vernemq1 -d erlio/docker-vernemq:1.3.0
Unable to find image 'erlio/docker-vernemq:1.3.0' locally
1.3.0: Pulling from erlio/docker-vernemq
<removed>
d91a574071835942272744318dd6471b05954cf2df82745005fbd2444cdf623a
$ docker exec -it d91a574071835942272744318dd6471b05954cf2df82745005fbd2444cdf623a bash
# root@d91a57407183:/# ps -ef | grep beam
vernemq    165   162  3 16:04 pts/0    00:00:01 /usr/lib/vernemq/erts-8.3.5.3/bin/beam.smp -P 256000 -A 64 -K true -W w -zdbbl 32768 -- -root /usr/lib/vernemq -progname vernemq -- -home /var/lib/vernemq -- -boot /usr/lib/vernemq/releases/1.3.0/vernemq -config /var/lib/vernemq/generated.configs/app.2018.03.08.16.04.43.config -setcookie vmq -name VerneMQ@172.17.0.2 -smp enable -vm_args /etc/vernemq/vm.args -pa /usr/lib/vernemq/lib/erlio-patches -- console
```

So VerneMQ is running and I don't see any errors in the logs. What am I doing differently? I'm running on Debian 9.3 with kernel `Linux algol 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`.

**Comment by chopmann** [comment] 2018-03-08 16:16
```
$ docker run --name vernemq1 erlio/docker-vernemq:1.3.0                                                                                                                                                                          master  
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
2018-03-08 16:14:27.591 [info] <0.31.0> Application lager started on node 'VerneMQ@172.17.0.2'
2018-03-08 16:14:27.606 [info] <0.195.0>@plumtree_peer_service_manager:write_state_to_disk:100 writing state {[{[{actor,<<103,110,66,190,33,110,220,141,205,195,166,28,163,225,170,63,145,241,168,26>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[['VerneMQ@172.17.0.2',{[{actor,<<103,110,66,190,33,110,220,141,205,195,166,28,163,225,170,63,145,241,168,26>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}} to disk <<75,2,131,80,0,0,0,248,120,1,203,96,206,97,96,96,96,204,96,130,82,41,12,172,137,201,37,249,69,185,64,81,145,244,60,167,125,138,121,119,122,207,30,94,38,179,248,225,42,251,137,31,87,72,101,37,50,102,101,112,166,48,176,164,100,38,151,36,50,38,10,0,33,71,98,64,162,65,134,64,22,26,200,96,4,137,129,13,6,17,76,41,12,66,97,169,69,121,169,190,129,14,134,230,70,122,134,230,122,6,122,70,164,217,140,106,3,194,29,12,132,221,129,170,21,0,152,196,79,147>>
2018-03-08 16:14:27.640 [info] <0.200.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir /var/lib/vernemq/meta/meta/0 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,33826123}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-03-08 16:14:27.646 [error] <0.200.0> CRASH REPORT Process <0.200.0> with 0 neighbours exited with reason: {db_open,"IO error: /var/lib/vernemq/meta/meta/0/MANIFEST-000001: No such file or directory"} in gen_server:init_it/6 line 344
2018-03-08 16:14:27.646 [error] <0.199.0> Supervisor plumtree_metadata_leveldb_instance_sup had child plmtrlvld_0 started with plumtree_metadata_leveldb_instance:start_link(0, [{sync,false},{total_leveldb_mem_percent,6},{use_bloomfilter,true}]) at undefined exit with reason {db_open,"IO error: /var/lib/vernemq/meta/meta/0/MANIFEST-000001: No such file or directory"} in context start_error
2018-03-08 16:14:27.647 [error] <0.197.0> Supervisor plumtree_sup had child plumtree_metadata_leveldb_instance_sup started with plumtree_metadata_leveldb_instance_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,plmtrlvld_0,{db_open,"IO error: /var/lib/vernemq/meta/meta/0/MANIFEST-000001: No such file or directory"}}} in context start_error
2018-03-08 16:14:27.647 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: {{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plmtrlvld_0,{db_open,"IO error: /var/lib/vernemq/meta/meta/0/MANIFEST-000001: No such file or directory"}}}}}},{plumtree_app,start,[normal,[]]}} in application_master:init/4 line 134


$ uname -a
Linux sirmonkey-laptop 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
```

**Comment by troyanov** [comment] 2018-03-08 16:17
@larshesel I don't have any problems running as Docker container as well.

Just discovered the same error running in Vagrant.

1. https://github.com/erlio/vernemq.git
2. vagrant up
3. make rel
4. vernemq start

**Comment by larshesel** [comment] 2018-03-08 16:44
@chopmann could this be because you're running docker on a 4.15 kernel?

**Comment by chopmann** [comment] 2018-03-08 16:57
With vagrant is running for me.
```
vagrant@vagrant-ubuntu-trusty-64:~/vernemq/_build/default/rel/vernemq/bin$ ./vernemq console
16:53:01.890 [warning] message_size_limit is deprecated and has no effect, use max_message_size instead                                                                                                                                                                         
config is OK                                                                                                                                                                                                                                                                    
-config /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2018.03.08.16.53.01.config -args_file /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.16.53.01.args -vm_args /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.16.53.01.args                                                                                                                                                                                                                      
!!!!                                                                                                                                                                                                                                                                            
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.                                                                                                                                                                                                              
!!!!                                                                                                                                                                                                                                                                            
Exec:  /home/vagrant/vernemq/_build/default/rel/vernemq/bin/../erts-8.3/bin/erlexec -boot /home/vagrant/vernemq/_build/default/rel/vernemq/bin/../releases/1.3.0/vernemq               -config /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2018.03.08.16.53.01.config -args_file /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.16.53.01.args -vm_args /home/vagrant/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.16.53.01.args              -pa /home/vagrant/vernemq/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console                                                                                                                                                                                                         
Root: /home/vagrant/vernemq/_build/default/rel/vernemq/bin/..                                                                                                                                                                                                                   
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:1:1] [async-threads:64] [hipe] [kernel-poll:true]                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
=INFO REPORT==== 8-Mar-2018::16:53:02 ===                                                                                                                                                                                                                                       
    alarm_handler: {set,{system_memory_high_watermark,[]}}                                                                                                                                                                                                                      
Eshell V8.3  (abort with ^G)                                                                                                                                                                                                                                                    
(VerneMQ@127.0.0.1)1>
```

@larshesel I dont know If I fully understand you. I'm running docker on a 4.15 Kernel. I also tried building vernemq from source ("....maybe it's docker...") but I get the same error.
I purged docker from my system and reinstalled it again. Same result.
I thought it may be me using btrfs but then again it works if I downgrade the Kernel and the Headers to 4.14 - the docker version does not change.

**Comment by troyanov** [comment] 2018-03-08 17:37
@chopmann thats interesting...  here is my output
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/_build/default/rel/vernemq$ bin/vernemq console
17:33:42.807 [warning] message_size_limit is deprecated and has no effect, use max_message_size instead
config is OK
-config /vagrant/_build/default/rel/vernemq/data/generated.configs/app.2018.03.08.17.33.42.config -args_file /vagrant/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.17.33.42.args -vm_args /vagrant/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.17.33.42.args
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
Exec:  /vagrant/_build/default/rel/vernemq/bin/../erts-8.3/bin/erlexec -boot /vagrant/_build/default/rel/vernemq/bin/../releases/1.3.0/vernemq               -config /vagrant/_build/default/rel/vernemq/data/generated.configs/app.2018.03.08.17.33.42.config -args_file /vagrant/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.17.33.42.args -vm_args /vagrant/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.08.17.33.42.args              -pa /vagrant/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console
Root: /vagrant/_build/default/rel/vernemq/bin/..
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:1:1] [async-threads:64] [hipe] [kernel-poll:true]

[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plmtrlvld_0,{db_open,\"IO error: ./data/meta/meta/0/MANIFEST-000001: Invalid argument\"}}}}}},{plumtree_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plm

Crash dump is being written to: ./log/erl_crash.dump...        
done

```

P.S. If I do `touch data/meta/meta/0/MANIFEST-000001` it is deleted after unsuccessful vernemq start

**Comment by chopmann** [comment] 2018-03-08 17:43
@larshesel I dont know if it's relevant but 
```
[ds:4:4:10] is present on my system but not on vagrant
PREEMPT is also present on my system but not on vagrant
```

A colleague used the following kernel and it worked.  Missing ds and PREEEMPT.
```
Linux T60 4.15.6-300.fc27.x86_64 #1 SMP Mon Feb 26 18:43:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
```

**Comment by troyanov** [comment] 2018-03-09 13:36
@chopmann @larshesel maybe that will help somehow:

https://github.com/google/leveldb/issues/281

Looks like my issue in Vagrant because of https://www.virtualbox.org/ticket/819

**Comment by chopmann** [comment] 2018-03-09 13:57
@larshesel @troyanov It's related. Well now I know it's not the kernel, but btrfs. I moved the source of vernemq to an usb formated with ext4 ( just plain cp) and ran vernemq console and this time I stayed up.
```
14:53:57.012 [warning] message_size_limit is deprecated and has no effect, use max_message_size instead
config is OK
-config /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2018.03.09.14.53.56.config -args_file /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.09.14.53.56.args -vm_args /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.09.14.53.56.args
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
Exec:  /mnt/vernemq/_build/default/rel/vernemq/bin/../erts-9.2/bin/erlexec -boot /mnt/vernemq/_build/default/rel/vernemq/bin/../releases/1.3.0/vernemq               -config /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2018.03.09.14.53.56.config -args_file /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.09.14.53.56.args -vm_args /mnt/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2018.03.09.14.53.56.args              -pa /mnt/vernemq/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console
Root: /mnt/vernemq/_build/default/rel/vernemq/bin/..
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [hipe] [kernel-poll:true]


=INFO REPORT==== 9-Mar-2018::14:53:57 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
Eshell V9.2  (abort with ^G)
(VerneMQ@127.0.0.1)1> 
```

Should I close this ticket and report to the leveldb issue?

**Comment by larshesel** [comment] 2018-03-09 14:12
Great you found out what it was - I think we can close this issue. Regarding reporting it upstream I guess it makes sense to report it, though, we're using the basho fork at the moment: https://github.com/basho/leveldb/ not the google version. Even though Basho doesn't exist more as a company I think it would still be good to report it to document the problem exists.

**Comment by troyanov** [comment] 2018-03-09 18:05
Regarding Vagrant issue, the easiest way would be switch to nfs.

Simply add two lines to your Vagrantfile
```
config.vm.network "private_network", type: "dhcp"
config.vm.synced_folder ".", "/vagrant", type: "nfs"
``` 

So the overall should look something like this:
```
Vagrant.configure(2) do |config|
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    $configs.each do |dist, dist_config|
    ...
```

**Closed** 2018-03-26 12:48 UTC
Labels: help wanted
