### ISSUE TITLE
rebar3_cuttlefish not available error

### ISSUE THREAD

**Issue by kwakak** [erlio/vernemq#89] opened 2016-02-23 09:15 UTC
Hi, 
While trying to build the latest version with otp 17.5, I get the plugin not available error. I've seen that the rebar3_cuttlefish had some updates last couple of days, could that be causing problems?

```
[root@vernemq-vm vernemq]# DEBUG=1 make rel
/home/vernemq/rebar3 release --overlay_vars vars.config
===> Error loading registry: {read_error,
                                     {file_error,
                                      "/root/.cache/rebar3/hex/com/amazonaws/s3/s3.hex.pm/tarballs/packages/registry",
                                      enoent}}
===> throw {error,
                      {rebar_prv_install_deps,
                          {load_registry_fail,<<"cuttlefish">>}}} [{rebar_prv_install_deps,
                                                                    get_package,
                                                                    2,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      677}]},
                                                                   {rebar_prv_install_deps,
                                                                    parse_dep,
                                                                    5,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      526}]},
                                                                   {lists,
                                                                    foldl,3,
                                                                    [{file,
                                                                      "lists.erl"},
                                                                     {line,
                                                                      1261}]},
                                                                   {rebar_prv_install_deps,
                                                                    handle_dep,
                                                                    5,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      412}]},
                                                                   {rebar_prv_install_deps,
                                                                    handle_dep,
                                                                    8,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      381}]},
                                                                   {rebar_prv_install_deps,
                                                                    update_unseen_src_dep,
                                                                    10,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      357}]},
                                                                   {lists,
                                                                    foldl,3,
                                                                    [{file,
                                                                      "lists.erl"},
                                                                     {line,
                                                                      1261}]},
                                                                   {rebar_prv_install_deps,
                                                                    update_src_deps,
                                                                    9,
                                                                    [{file,
                                                                      "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                     {line,
                                                                      293}]}]
===> Plugin {rebar3_cuttlefish,
                       {git,
                           "git://github.com/tsloughter/rebar3_cuttlefish.git",
                           {branch,"master"}}} not available. It will not be used.

```

**Comment by ioolkos** [comment] 2016-02-23 10:42
Thank you for reporting!
@tsloughter could you advise on this?

**Comment by tsloughter** [comment] 2016-02-23 15:28
Crap, my bad. @ferd we definitely should add plugin locking soon :)

@ioolkos @kwakak the cuttlefish plugin has changed a lot in the recent days and has been published to hex. See the readme for how to use it. You should simply add `{project_plugins, [rebar3_cuttlefish]}.` to the `rebar.config` (you'll need the most recent rebar3 nightly) and run `rebar3 release`. No need for `rebar3 cuttlefish` commands anymore.

**Comment by ferd** [comment] 2016-02-23 16:01
Yeah. Plugin locking is gonna be a pretty big requirement, agreed. Pre 3.0.0 or post 3.0.0 ?

**Comment by ioolkos** [comment] 2016-02-23 17:51
Thanks for the suggestions!
@tsloughter I quickly tried them and still failed. @dergraf more ideas?

````
➜  vernemq git:(master) ✗ make rel
/home/afa/Erlang/ioolkos/vernemq/rebar3 release --overlay_vars vars.config
===> Plugin rebar3_cuttlefish not available. It will not be used.
===> Verifying dependencies...
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/afa/Erlang/ioolkos/vernemq/_build/default/lib
          /usr/local/lib/erlang/lib
          /home/afa/Erlang/ioolkos/vernemq/_build/default/rel
===> Resolved vernemq-0.12.4
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
escript: exception error: no function clause matching 
                 rlx_prv_release:format_error({error,
                                               {rebar_hooks,
                                                {bad_provider,post,release,
                                                 cuttlefish}}}) (/home/travis/build/rebar/rebar3/_build/default/lib/relx/src/rlx_prv_release.erl, line 53)
  in function  rebar3:handle_error/1 (/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar3.erl, line 272)
  in call from escript:run/2 (escript.erl, line 752)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1 
  in call from init:start_em/1 
Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 127
````

**Comment by dergraf** [comment] 2016-02-23 19:30
have a different error on `rebar 3.0.0-alpha-2 on Erlang/OTP 17 Erts 6.3`
this is on a fresh clone with the suggested changes by @tsloughter 

    ===> Uncaught error: {'EXIT',
                             {function_clause,
                              [{rebar_digraph,'-cull_deps/2-fun-0-',
                                [<<"neotoma">>,
                                 {dict,0,16,16,8,80,48,
                                  {[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                   [],[]},
                                  {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                    [],[]}}}],
                                [{file,"src/rebar_digraph.erl"},{line,75}]},
                               {lists,foldl,3,
                                [{file,"lists.erl"},{line,1261}]},
                               {rebar_digraph,cull_deps,2,
                                [{file,"src/rebar_digraph.erl"},{line,75}]},
                               {rebar_prv_install_deps,update_pkg_deps,7,
                                [{file,"src/rebar_prv_install_deps.erl"},
                                 {line,188}]},
                               {rebar_prv_install_deps,handle_deps,5,
                                [{file,"src/rebar_prv_install_deps.erl"},
                                 {line,144}]},
                               {rebar_prv_install_deps,deps_per_profile,2,
                                [{file,"src/rebar_prv_install_deps.erl"},
                                 {line,163}]},
                               {lists,foldl,3,
                                [{file,"lists.erl"},{line,1261}]},
                               {rebar_prv_install_deps,do,1,
                                [{file,"src/rebar_prv_install_deps.erl"},
                                 {line,77}]}]}}

**Comment by tsloughter** [comment] 2016-02-23 19:31
A fresh clone of rebar3? That is a very old version of rebar3.

**Comment by dergraf** [comment] 2016-02-23 19:31
nope sorry, that's the nightly download from rebar3.org

**Comment by ioolkos** [comment] 2016-02-23 21:29
OK, new version cloned & built from github
````
➜  vernemq git:(master) ✗ ./rebar3 -v     
rebar 3.0.0-beta.4+build.3316.ref2d2b8a7 on Erlang/OTP 17 Erts 6.4
````
`make rel` fails like this:
````
➜  vernemq git:(master) ✗ make rel
/home/afa/Erlang/ioolkos/vernemq/rebar3 release --overlay_vars vars.config
===> Invalid option --overlay_vars on task release
Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
````
`./rebar3 release` fails like this:
````
➜  vernemq git:(master) ✗ ./rebar3 release
===> Verifying dependencies...
===> Running cuttlefish schema generator
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
````

**Comment by tsloughter** [comment] 2016-02-23 21:34
Ah options is something I forgot. I'll get those added to the provider.

Can you run with DEBUG=1 so we can see what the error is.

**Comment by ioolkos** [comment] 2016-02-23 21:41
Running with DEBUG=1 gives me:
````
===> Running cuttlefish schema generator
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: badarg
===> Stack trace to the error location: [{erlang,atom_to_list,
                                                 ["vernemq"],
                                                 []},
                                                {rebar3_cuttlefish_release,
                                                 do,1,
                                                 [{file,
                                                   "/home/afa/Erlang/ioolkos/vernemq/_build/default/plugins/rebar3_cuttlefish/src/rebar3_cuttlefish_release.erl"},
                                                  {line,64}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/afa/Erlang/rebar/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar3,main,1,
                                                 [{file,
                                                   "/home/afa/Erlang/rebar/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
                                                  {line,56}]},
                                                {escript,run,2,
                                                 [{file,"escript.erl"},
                                                  {line,752}]},
                                                {escript,start,1,
                                                 [{file,"escript.erl"},
                                                  {line,276}]},
                                                {init,start_it,1,[]},
                                                {init,start_em,1,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
````

**Comment by tsloughter** [comment] 2016-02-23 21:42
The args like `--overlay_vars` should work with the latest commit to master.

**Comment by tsloughter** [comment] 2016-02-23 21:43
Hm, weird, that line number doesn't line up for me but I'm guessing it is when this is run:

```
ConfFile = filename:join("config", atom_to_list(Name)++".conf"),
```

The `Name` from relx config should be an atom, not a string.

**Comment by ioolkos** [comment] 2016-02-23 21:52
Is this fetching the correct packages? cause  `--overlay_vars` still seems to be an invalid option.

````
➜  vernemq git:(master) ✗ make rel
/home/afa/Erlang/ioolkos/vernemq/rebar3 release --overlay_vars vars.config
===> Fetching rebar3_cuttlefish ({pkg,<<"rebar3_cuttlefish">>,
                                         <<"0.6.0">>})
===> Downloaded package, caching at /home/afa/.cache/rebar3/hex/default/packages/rebar3_cuttlefish-0.6.0.tar
===> Fetching cuttlefish ({pkg,<<"cuttlefish">>,<<"2.0.7">>})
===> Version cached at /home/afa/.cache/rebar3/hex/default/packages/cuttlefish-2.0.7.tar is up to date, reusing it
===> Fetching getopt ({pkg,<<"getopt">>,<<"0.8.2">>})
===> Version cached at /home/afa/.cache/rebar3/hex/default/packages/getopt-0.8.2.tar is up to date, reusing it
===> Fetching lager ({pkg,<<"lager">>,<<"3.0.2">>})
===> Version cached at /home/afa/.cache/rebar3/hex/default/packages/lager-3.0.2.tar is up to date, reusing it
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.7">>})
===> Version cached at /home/afa/.cache/rebar3/hex/default/packages/goldrush-0.1.7.tar is up to date, reusing it
===> Compiling goldrush
===> Compiling lager
===> Compiling getopt
===> Compiling cuttlefish
===> Building escript...
===> Compiling rebar3_cuttlefish
===> Invalid option --overlay_vars on task release
Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
````

**Comment by tsloughter** [comment] 2016-02-23 21:55
oh sorry, no, use the git repo for now. I wnat to get bugs worked out before continuing to publish to hex.

**Comment by ioolkos** [comment] 2016-02-23 22:07
I can't seem to make this work today. More lookin' into it tomorrow.

**Comment by tsloughter** [comment] 2016-02-23 22:13
Ok. I went ahead and published the latest 0.7.0, to hex so you can try that tomorrow.

**Comment by dergraf** [comment] 2016-02-24 07:17
checked this morning with `rebar 3.0.0-beta.4+build.3316.ref2d2b8a7 on Erlang/OTP 17 Erts 6.3` (latest from github) can reproduce the problem with `===> Invalid option --overlay_vars on task release`

**Comment by ioolkos** [comment] 2016-02-24 08:15
I added `{rebar3_cuttlefish, "0.7.1"}.` to rebar.config, to get the new hex package.

Running `rebar3 release` results in:

````
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/afa/Erlang/ioolkos/vernemq/_build/default/lib
          /usr/local/lib/erlang/lib
          /home/afa/Erlang/ioolkos/vernemq/_build/default/rel
===> Resolved vernemq-0.12.4
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
===> Unable to run post hooks for 'release', command 'cuttlefish' not found.
{"init terminating in do_boot",{function_clause,[{rlx_prv_release,format_error,[{error,{rebar_hooks,{bad_provider,post,release,cuttlefish}}}],[{file,"/home/travis/build/rebar/rebar3/_build/default/lib/relx/src/rlx_prv_release.erl"},{line,53}]},{rebar3,handle_error,1,[{file,"/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar3.erl"},{line,272}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
````

**Comment by ioolkos** [comment] 2016-02-24 09:34
Switched to a known working commit for rebar3_cuttlefish for now, to allow building.
@kwakak it be great, if you could retest building. Thanks!

**Comment by kwakak** [comment] 2016-02-24 10:24
Retested, this time build was successful.
Thank you all for the effort!

**Comment by ioolkos** [comment] 2016-02-24 10:35
@kwakak great to hear, thanks for taking the time to test!

We'll test the new shiny Rebar3 goodness elsewhere in the meantime :)

**Comment by tsloughter** [comment] 2016-02-24 15:29
I'll use vernemq to test against later today :) so I don't have to keep asking you to try my changes.

**Comment by ioolkos** [comment] 2016-02-24 18:55
Hey @tsloughter thanks for looking into it! appreciated :)

**Comment by larshesel** [comment] 2016-03-18 15:21
fixed via #100

**Closed by larshesel** 2016-03-18 15:21 UTC

**Comment by suiluj** [comment] 2018-03-18 20:49
Hello,
i have the same problem with the latest vernemq git clone when building for my raspberry pi 3 with the `make rpi32` command. i have installed erlang 18.3 because of [this tweet by vernemq](https://twitter.com/vernemq/status/766557478788096000?lang=de).

i do not know how to "switch to a known working commit for rebar3_cuttlefish" like @ioolkos wrote [on 24 Feb 2016](https://github.com/erlio/vernemq/issues/89#issuecomment-188161883)

Do you guys have some tips or a solution?
Thank you very much.

here is my debug output when i execute `DEBUG=1 make rpi32`:
```pi@raspberrypi:~/vernemq $ DEBUG=1 make rpi32
/home/pi/vernemq/rebar3 as rpi32 release --overlay_vars vars.config
===> 18.3 satisfies the requirement for minimum OTP version 18.0
===> 18.3 satisfies the requirement for minimum OTP version R16
===> error undef [{rebar3_cuttlefish,module_info,[exports],[]},
                         {rebar_plugins,validate_plugin,1,
                             [{file,
                                  "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                              {line,144}]},
                         {rebar_plugins,handle_plugin,4,
                             [{file,
                                  "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                              {line,113}]},
                         {rebar_plugins,'-handle_plugins/4-fun-0-',4,
                             [{file,
                                  "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                              {line,83}]},
                         {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
                         {rebar_plugins,handle_plugins,4,
                             [{file,
                                  "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                              {line,82}]},
                         {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
                         {rebar_plugins,project_plugins_install,1,
                             [{file,
                                  "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                              {line,23}]}]
===> Plugin {rebar3_cuttlefish,
                       {git,"git://github.com/larshesel/rebar3_cuttlefish",
                           {branch,"use-otp20-compatibly-cuttlefish"}}} not available. It will not be used.

=ERROR REPORT==== 18-Mar-2018::19:24:07 ===
Loading of /home/pi/vernemq/_build/default/plugins/rebar3_cuttlefish/ebin/rebar3_cuttlefish.beam failed: badfile

=ERROR REPORT==== 18-Mar-2018::19:24:07 ===
beam/beam_load.c(1189): Error loading module rebar3_cuttlefish:
  mandatory chunk of type 'Atom' not found


===> Expanded command sequence to be run: [{default,as}]
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile},
                                                  {default,release}]

=ERROR REPORT==== 18-Mar-2018::19:24:07 ===
beam/beam_load.c(1189): Error loading module getopt:
  mandatory chunk of type 'Atom' not found



=ERROR REPORT==== 18-Mar-2018::19:24:07 ===
Loading of /home/pi/vernemq/_build/default/plugins/getopt/ebin/getopt.beam failed: badfile
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: undef
===> Stack trace to the error location:
[{getopt,parse,
         [[{relname,110,"relname",string,
                    "Specify the name for the release that will be generated"},
           {relvsn,118,"relvsn",string,"Specify the version for the release"},
           {goal,103,"goal",string,
                 "Specify a target constraint on the system. These are usually the OTP"},
           {upfrom,117,"upfrom",string,
                   "Only valid with relup target, specify the release to upgrade from"},
           {output_dir,111,"output-dir",string,
                       "The output directory for the release. This is `./` by default."},
           {help,104,"help",undefined,"Print usage"},
           {lib_dir,108,"lib-dir",string,
                    "Additional dir that should be searched for OTP Apps"},
           {path,112,"path",string,"Additional dir to add to the code path"},
           {default_libs,undefined,"default-libs",boolean,
                         "Whether to use the default system added lib dirs (means you must add them all manually). Default is true"},
           {log_level,86,"verbose",
                      {integer,2},
                      "Verbosity level, maybe between 0 and 3"},
           {dev_mode,100,"dev-mode",boolean,
                     "Symlink the applications and configuration into the release instead of copying"},
           {include_erts,105,"include-erts",string,
                         "If true include a copy of erts used to build with, if a path include erts at that path. If false, do not include erts"},
           {override,97,"override",string,
                     "Provide an app name and a directory to override in the form <appname>:<app directory>"},
           {config,99,"config",{string,[]},"The path to a config file"},
           {overlay_vars,undefined,"overlay_vars",string,
                         "Path to a file of overlay variables"},
           {vm_args,undefined,"vm_args",string,
                    "Path to a file to use for vm.args"},
           {sys_config,undefined,"sys_config",string,
                       "Path to a file to use for sys.config"},
           {system_libs,undefined,"system_libs",string,
                        "Path to dir of Erlang system libs"},
           {version,undefined,"version",undefined,"Print relx version"},
           {root_dir,114,"root",string,"The project root directory"},
           {help,104,"help",undefined,"Print this help."},
           {version,118,"version",undefined,"Show version information."},
           {task,undefined,undefined,string,"Task to run."}],
          ["--overlay_vars","vars.config"]],
         []},
 {rebar_core,process_command,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,117}]},
 {rebar_prv_do,do_tasks,2,
               [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                {line,57}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,153}]},
 {rebar3,main,1,
         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
          {line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,757}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_it,1,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
pi@raspberrypi:~/vernemq $ 
```

**Comment by ioolkos** [comment] 2018-03-18 21:04
@suiluj thanks for giving a try to the RPI version which doesn't get the attention it deserves. (otoh it *should* work once one gets LevelDB to compile).

I can't answer your specific question from the top of my head. I'll see what I can find out tomorrow.

@larshesel I noticed we use this rebar3_cuttlefish version, but I guess this is not related to the issue here anyway?

```erlang
{project_plugins, [
                   {rebar3_cuttlefish, {git, "git://github.com/larshesel/rebar3_cuttlefish",
{branch, "use-otp20-compatibly-cuttlefish"}}}]}.
```

**Comment by larshesel** [comment] 2018-03-19 07:08
Hi - try this branch https://github.com/larshesel/vernemq/tree/fix-rpi32-build - that branch builds for me on an rpi3 using OTP 20.2.

**Comment by suiluj** [comment] 2018-03-19 16:01
@ioolkos thanks for your quick reply.

@larshesel i tried your branch with otp 20.2 installed (i deleted all previous erlang before to have it clean)
it built many parts successfully and looked promising but it stuck at the following part (last output from `make rpi32`):

```
===> Compiling epgsql
_build/default/lib/epgsql/src/epgsql_fdatetime.erl:110: Warning: ambiguous call of overridden auto-imported BIF floor/1
 - use erlang:floor/1 or "-compile({no_auto_import,[floor/1]})." to resolve name clash

===> Compiling eredis
===> Compiling vmq_ql
===> Running neotoma...
ln: target '_build/default/lib/' is not a directory: No such file or directory
===> Hook for compile failed!

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
pi@raspberrypi:~/vernemq $ 
```
i googled some things but to be honest i have no clue how to solve these kinds of errors.
neotoma seems to have something to do with the `rebar3_neotoma_plugin`

Any advice?
Thank you for your support.

**Comment by larshesel** [comment] 2018-03-20 06:16
hi - could you try to first do `make rel` and then `make rpi32`.

**Comment by suiluj** [comment] 2018-03-20 15:25
oh i found my mistake:
i accidentally cloned your fork but not the specific "fix-rpi32-build" branch.
I am so sorry that was my fault.

it now worked without `make rel` before just like you suggested in the first place.
so for everybody with a raspberry pi just do:

```
git clone -b fix-rpi32-build https://github.com/larshesel/vernemq.git
cd vernemq/
make rpi32
```
after succesfull building the correct path is:
`/home/pi/vernemq/_build/rpi32/rel/vernemq/bin`

so the following commands start the vernemq broker in console mode:
```
cd /home/pi/vernemq/_build/rpi32/rel/vernemq/bin
./vernemq console
```

@larshesel thank you very much for your raspberrypi fix and your help.
