### ISSUE TITLE
SSL/TLS not working

### ISSUE THREAD

**Issue by nik736** [erlio/vernemq#610] opened 2018-02-14 09:14 UTC
### Environment

- VerneMQ Version: 1.3.0
- OS: Ubuntu 16.04

### Expected behavior

When adding:
listener.ssl.default = public_ip:8883
listener.ssl.cafile = /etc/letsencrypt/live/domain.com/chain.pem
listener.ssl.certfile = /etc/letsencrypt/live/domain.com/cert.pem
listener.ssl.keyfile = /etc/letsencrypt/live/domain.com/privkey.pem

I am expecting a connection to port 8883 via TLS would be working. Cert files were generated using Let's Encrypt.

### Actual behaviour

Adding those lines to the config and restarting VerneMQ won't help. I've tried moving the cert files around, for example to the /etc/vernemq directory, adjusting permissions on those files but nothing seems to be helping. I also found some test cert files in some other Issue which I tried, sadly without success.

There were a lot of errors on the way, the last one in the crash log:
`SSL: certify: ssl_connection.erl:484:Fatal error: handshake failure`

error_log:
`2018-02-14 09:06:49.492 [error] <0.512.0> SSL: certify: ssl_connection.erl:484:Fatal error: handshake failure`

I am not really sure what handshake failure is supposed to mean, for me it looks like this could be anything related to TLS, I can't find any more detailed message.

Sadly I am not sure what to try anymore.

Thanks for your help.

**Comment by larshesel** [comment] 2018-02-14 09:23
Hi,

Getting TLS/SSL to work can be tricky.

Maybe you can take a look at this example: https://github.com/erlio/vernemq/issues/540#issuecomment-349316122 which works and compare to the files you use. Maybe there's something wrong with the files.

The certificates used in the above example are these: https://github.com/erlio/vernemq/tree/master/apps/vmq_server/test/ssl

**Comment by NickNeck** [comment] 2018-02-14 10:17
I have done the same in the last days. The article [SSL/TLS Client Certs to Secure MQTT](http://rockingdlabs.dunmire.org/exercises-experiments/ssl-client-certs-to-secure-mqtt) has helped me.

**Comment by nik736** [comment] 2018-02-14 14:50
@NickNeck Thanks for the URL, but since I got a Lets Encrypt cert I am not sure if I need to create client certs additionally (?)

@larshesel Sadly this isn't helping, I tried so many things already but nothing seems to be working.

I also found this URL:
https://evothings.com/evothings-does-mqtt-with-vernemq-or-emqtt/

And he is doing the exact same thing as me, but still no success.

Any more ideas?

Thank you.

**Comment by larshesel** [comment] 2018-02-14 15:17
Did you try with the certificates we ship with VerneMQ? If they work then you know the problem is either with your certificates, the location (access issues, potentially an SELinux policy issue) or plain permission issues.

**Comment by larshesel** [comment] 2018-02-16 10:56
Hi @nik736 did you get it to work? I'll close this issue as this does not look like a VerneMQ bug.

**Closed by larshesel** 2018-02-16 10:56 UTC

**Comment by uiue** [comment] 2018-05-11 11:10
This url maybe help you.
[https://www.cnblogs.com/Anker/p/6018032.html](url)

**Comment by dhaval1983** [comment] 2018-05-30 20:48
I am getting this error
WebSocket connection to 'wss://domainname.com:8443/mqtt' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID in chrome developer console
can you please help
[vernemq.txt](https://github.com/erlio/vernemq/files/2055608/vernemq.txt)
