### ISSUE TITLE
 auth_on_register hook is not called

### ISSUE THREAD

**Issue by EnCl** [erlio/vernemq#304] opened 2017-03-13 22:54 UTC
### Environment

- VerneMQ Version: 1.0.0rc2
- OS:Linux Docker container

### Expected behavior
Registered hook auth_on_register triggers when a new client connects

### Actual behaviour

auth_on_register is not triggered

### Details

I want to trigger the **auth_on_register** hook when a new client connects to VerneMQ. I implemented an HTTP Server and used this do define the hook's endpoint in the **etc/vernemq/vernemq.conf** file . I expected an HTTP Post call to reach the endpoint but nothing happens.

In the **etc/vernemq/vernemq.conf** I set:

**plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on
vmq_webhooks.webhook1.hook = auth_on_register
vmq_webhooks.webhook1.endpoint = http://192.168.5.26:8080/app/micro-service/
vmq_webhooks.webhook2.hook = on_client_wakeup
vmq_webhooks.webhook2.endpoint = http://192.168.5.26:8080/app/micro-service/**

When my client connects to the VerneMQ I'm getting a POST request from **on_client_wakeup**, but nothing from  **auth_on_register**.

In the logs I can see:
[debug] <0.2960.0>@vmq_queue:state_change:898 [<0.2960.0>] transition from offline --> online because of add_session
[debug] <0.2957.0>@vmq_ranch:teardown:123 [<0.2957.0>] session normally stopped

I added the **on_client_wakeup** just to see if another hook can be triggered and it did.
If I remove the **on_client_wakeup** settings from  **etc/vernemq/vernemq.conf**  then no POST message is sent.

Running:_**docker exec vernemq1 vmq-admin webhooks status**_ I see:
+----------------+-------------------------------------------+-------------+
|      hook      |                 endpoint                  |base64payload|
+----------------+-------------------------------------------+-------------+
|on_client_wakeup|http://192.168.5.26:8080/app/micro-service/|    true     |
|auth_on_register|http://192.168.5.26:8080/app/micro-service/|    true     |
+----------------+-------------------------------------------+-------------+

Also running: **_docker exec vernemq1 vmq-admin plugin show --internal_** I see:

``|      Plugin       |   Type    |    Hook(s)     |                M:F/A                 |
+-------------------+-----------+----------------+--------------------------------------+
|    vmq_config     |  module   | change_config  |      vmq_config:change_config/1      |
|  vmq_lvldb_store  |  module   |msg_store_write |  vmq_lvldb_store:msg_store_write/2   |
|  vmq_lvldb_store  |  module   |msg_store_delete|  vmq_lvldb_store:msg_store_delete/2  |
|  vmq_lvldb_store  |  module   | msg_store_find |   vmq_lvldb_store:msg_store_find/1   |
|  vmq_lvldb_store  |  module   | msg_store_read |   vmq_lvldb_store:msg_store_read/2   |
|   vmq_webhooks    |application|                |                                      |
|vmq_webhooks_plugin|  module   |auth_on_register|vmq_webhooks_plugin:auth_on_register/5|
|vmq_webhooks_plugin|  module   |on_client_wakeup|vmq_webhooks_plugin:on_client_wakeup/1|

Is there something missing in my configuration ?

**Comment by larshesel** [comment] 2017-03-14 07:01
Hi @EnCl ,

Since the clients can trigger the `on_client_wakeup` hook it means that the clients can actually connect. Since your `auth_on_register` hook isn't called that probably means that the config setting `allow_anonymous` has been set to `on`.

Can you check that? If that doesn't help could you send us the entire `vernemq.conf` file?

**Comment by EnCl** [comment] 2017-03-14 12:52
Hi @larshesel ,

You were right. Setting the allow_anonymous = off triggered the auth_on_register hook.

I do have one question. In case the HTTP response is not a JSON then I'm receiving 2 POST requests from auth_on_register hook. Is this normal behaviour ? It can be prevented somehow ?

**Comment by larshesel** [comment] 2017-03-15 08:31
Hi @EnCl 

The posts from the webhooks to your endpoint is driven by the client connecting, so no, this is not normal behaviour. However, testing this (by returning invalid json in the `auth_on_register` hook) I could not reproduce this. Could it be that your client is automatically trying to connect a second time?

**Comment by larshesel** [comment] 2017-03-17 11:37
Closing this - feel free to reopen out if you still have the problem.

**Closed by larshesel** 2017-03-17 11:37 UTC
