### ISSUE TITLE
Vernemq restart fails for the first time

### ISSUE THREAD

**Issue by KnolBee** [erlio/vernemq#389] opened 2017-05-19 08:22 UTC
### Environment

- VerneMQ Version: 1.0.1
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Expected behavior

- Vernemq should restart without error

### Actual behavior

- Vernemq fails to restart for the first time when below command is issued

```
 service Verne MQ restart
Job for vernemq.service failed because the control process exited with an error code. See "systemctl status vernemq.service" and "journalctl -xe" for details.
```

But when rerun the command, it works fine.

```
crash.log
2017-05-19 07:53:02 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_diversity_sup}
     Context:    shutdown_error
     Reason:     killed
     Offender:   [{pid,<0.395.0>},{id,vmq_diversity_plugin},{mfargs,{vmq_diversity_plugin,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

error.log
2017-05-19 07:53:02.194 [error] <0.394.0> Supervisor vmq_diversity_sup had child vmq_diversity_plugin started with vmq_diversity_plugin:start_link() at <0.395.0> exit with reason killed in context shutdown_error
[loadtestjs.zip](https://github.com/erlio/vernemq/files/1013568/loadtestjs.zip)


```

- Procedure to test

1. Generate and Load test id's to MongoDB

```
echo hello | awk '{for(i=0;i<100000;i++){print "{\"mountpoint\" : \"\", \"client_id\" : \""i"\", \"username\" : \"myconnector\", \"passhash\" : \"$2a$06$nV2TRXCc/1AJYVGrAzuO7.ODHzF7jEXdqPLM6oziPif5cOM2rm8wO\", \"publish_acl\" : [ { \"pattern\" : \"#\" } ], \"subscribe_acl\" : [ { \"pattern\" : \"#\" } ] }"}}' > sample.ids

mongoimport -d vernemq -c vmq_acl_auth --type json --file sample.ids
```
2. Run the test code to create 50k connections,

`node index.js <serverip>`

3. Once the test script completes 50k connection, then keeping the test code running, try to restart the server

Thanks

**Comment by dergraf** [comment] 2017-05-19 18:02
Thanks for reporting!
Can you share your `console.log` with us?

**Comment by KnolBee** [comment] 2017-05-22 06:30
@dergraf  have attached all the logs
[logs.zip](https://github.com/erlio/vernemq/files/1017931/logs.zip)

**Comment by KnolBee** [comment] 2017-05-24 05:30
@degraf any pointers here?

**Comment by dergraf** [comment] 2017-05-24 16:30
Haven't had time to investigate. As it is vmq_diversity/Lua/mongodb related I would also run the same test with no auth and see how it goes.

**Comment by dergraf** [comment] 2017-05-24 22:39
@KnolBee just went through the logs.

In your console.log the `vmq_diversity` application isn't started when you have restarted the node or is the log incomplete? I am not sure if the shutdown_error of vmq_diversity_sup is related to the Node shutdown or the restart at this point. @larshesel any idea?

what happens if you don't immediately restart the node and wait e.g. 30secs?

**Comment by larshesel** [comment] 2017-05-25 05:28
I believe the `shutdown_error` is related to stopping the `vmq_diversity_plugin` child and is caused by the supervisor killing the child because it's timed out waiting for it to stop gracefully. This fits with the logs:

```
2017-05-22 06:01:54.297 [info] <0.3937.6> Administrative stop
2017-05-22 06:02:00.549 [error] <0.346.0> Supervisor vmq_diversity_sup had child vmq_diversity_plugin started with vmq_diversity_plugin:start_link() at <0.347.0> exit with reason killed in context shutdown_error
```

Which are 5 seconds apart. (Though, I don't know where the 'Administrative stop` message comes from - not sure it's logged by VerneMQ).  Maybe something is blocking the `vmq_diversity_plugin` process?

I don't know what prevents VerneMQ from being started thereafter. Could you maybe paste the output as suggested by systemd: `See "systemctl status vernemq.service" and "journalctl -xe" for details.`? Maybe there are some leads there?

**Comment by KnolBee** [comment] 2017-05-25 06:03
@larshesel Logs from those commands are attached.
[logs.txt](https://github.com/erlio/vernemq/files/1028091/logs.txt)

**Comment by KnolBee** [comment] 2017-05-25 06:25
@dergraf 

> what happens if you don't immediately restart the node and wait e.g. 30secs?

Same behavior, I stopped VerneMQ, waited for 5 minutes, and then tried starting it, but ended up with the same issue.

**Comment by larshesel** [comment] 2017-05-25 06:52
Could you do an experiment and start vernemq using `vernemq console` as the vernemq user instead of the system scripts after having stopped it? It would be interesting to see what output that produces.

**Comment by KnolBee** [comment] 2017-05-29 05:21
I tried vernemq console, here is the output

vernemq@Latitude-3450:~$ /usr/sbin/vernemq console
config is OK
-config /var/lib/vernemq/generated.configs/app.2017.05.29.10.47.47.config -args_file /var/lib/vernemq/generated.configs/vm.2017.05.29.10.47.47.args -vm_args /var/lib/vernemq/generated.configs/vm.2017.05.29.10.47.47.args
Exec:  /usr/lib/vernemq/erts-8.2/bin/erlexec -boot /usr/lib/vernemq/releases/1.0.1/vernemq               -config /var/lib/vernemq/generated.configs/app.2017.05.29.10.47.47.config -args_file /var/lib/vernemq/generated.configs/vm.2017.05.29.10.47.47.args -vm_args /var/lib/vernemq/generated.configs/vm.2017.05.29.10.47.47.args              -pa /usr/lib/vernemq/lib/erlio-patches -- console
Root: /usr/lib/vernemq
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true]

 __      ____  __  ____         _____ _______      ________ _____   _____ _____ _________     __ 
 \ \    / /  \/  |/ __ \       |  __ \_   _\ \    / /  ____|  __ \ / ____|_   _|__   __\ \   / / 
  \ \  / /| \  / | |  | |______| |  | || |  \ \  / /| |__  | |__) | (___   | |    | |   \ \_/ /  
   \ \/ / | |\/| | |  | |______| |  | || |   \ \/ / |  __| |  _  / \___ \  | |    | |    \   /   
    \  /  | |  | | |__| |      | |__| || |_   \  /  | |____| | \ \ ____) |_| |_   | |     | |    
     \/   |_|  |_|\___\_\      |_____/_____|   \/   |______|_|  \_\_____/|_____|  |_|     |_|    
                                                                                                 
Eshell V8.2  (abort with ^G)
(VerneMQ@127.0.0.1)1>


However i get following errors in the console.log

2017-05-29 10:48:38.513 [error] <0.818.0> Ranch listener {{0,0,0,0},1883} terminated with reason: {timeout,{gen_server,call,[<0.340.0>,{call_function,auth_on_register,[{addr,<<"127.0.0.1">>},{port,19194},{mountpoint,<<>>},{client_id,<<"1583">>},{username,<<"myconnector">>},{password,<<"12345678">>},{clean_session,true}]}]}}

Ne idea what might be going wrong?

**Comment by KnolBee** [comment] 2017-06-01 10:36
@larshesel Can you help in this? We see similar problem in restart on production systems too :-(

**Comment by degraf** [comment] 2017-06-01 11:29
Hi! I`m got near 5 letters about this thread but I don`t subscribed on it) Whats going on? Is this github bug or your mistake? 

Last letter theme:
Re: [erlio/vernemq] Vernemq restart fails for the first time (#389)

**Comment by degraf** [comment] 2017-06-01 11:31
Haha lol, sorry now I see that KnolBee call me by typing mistake) Get luck, guys!

**Comment by ioolkos** [comment] 2017-06-01 13:16
just assigned @degraf to this problem. you now have to solve it! :)

**Comment by degraf** [comment] 2017-06-01 14:03
I`m just russian commercial PHP badass monkey. Balalaika bryn bryn, vodka drink drink, bear (my sub-monkey) friendly, and how all russians I`m hacker but you dont heared and dont seen this because Putin is my friend. Thug life.

Really sorry guys but I can`t help you, this is not my native programming language.

**Comment by degraf** [comment] 2017-06-01 14:19
And yes I`m really born in Siberia (live in St.Petersburg), near Baikal (haha near, ~1000 km ) and we havent bears in cities, but in Siberia we have really friendly peoples and perfect nature. If any of you guys will be in St.Petersburg - call @degraf again and I`ll show you true russian soul.

Sorry for out-trade talkings

**Comment by ioolkos** [comment] 2017-06-01 15:20
Will do! :)

**Comment by KnolBee** [comment] 2017-06-02 04:42
Sure :-) not clear how you got tagged though :-)

**Comment by dergraf** [comment] 2017-06-15 09:08
I guess we found the root cause of this issue. Our current mongodb Lua wrapper uses bcrypt to hash the password. The bcrypt hashing function takes 600ms to complete on my laptop. As the current implementation of vmq_diversity uses a single synchronized Lua state (one per loaded script) to handle the plugin hooks, your reconnects (and all the required hook calls) where queued up in this process which then pretty soon run into a timeout (think 1000connections=1000hookcalls=1000*600ms=10minutes) 
While we cant change the bcrypt performance (well you can with lower hashing iterations) we have to come up with a solution to load balance this single Lua state bottleneck. Whick luckily we did in https://github.com/erlio/vernemq/pull/404. Our database integrations now allow to load balance the hook calls over multiple Lua states, the default is 10 states, which is tunable if you'd run into further timeouts again.

The PR is already in master, we plan to release it as part of 1.1.0 soon. It would be great if you can do a testrun with current master.

**Comment by larshesel** [comment] 2017-06-23 05:48
The fixes has been released as part of the VerneMQ 1.1.0 release so I'm closing this - we'd of course appreciate any feedback you might have.

**Closed by larshesel** 2017-06-23 05:48 UTC

**Comment by KnolBee** [comment] 2017-06-27 10:13
thanks, @larshesel will test and give feedback.

**Comment by KnolBee** [comment] 2017-07-31 11:06
@larshesel Apologies for very late reply. The crash seems to be fixed. THanks.
