### ISSUE TITLE
Broker doesn't connect to mongo server

### ISSUE THREAD

**Issue by ig0r** [erlio/vernemq#305] opened 2017-03-14 15:03 UTC
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04LTS
- Mongo 3.4.x

### Expected behavior

Broker successfully connected to mongo

### Actual behaviour

1. `vernemq.conf` has all specified connectivity info.
2. `error.log` has the following errors:
```
2017-03-14 14:49:08.064 [error] <0.1384.0> CRASH REPORT Process <0.1384.0> with 0 neighbours crashed with reason: <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/4 line 41
2017-03-14 14:49:08.064 [error] <0.348.0> Supervisor {<0.348.0>,poolboy_sup} had child mc_worker started with {mc_worker,start_link,undefined} at <0.1384.0> exit with reason <<"Can't pass authentification">> in context child_terminated
2017-03-14 14:49:08.076 [error] <0.1385.0> CRASH REPORT Process <0.1385.0> with 0 neighbours crashed with reason: <<"Can't pass authentification">> in mc_auth_logic:scram_sha_1_auth/4 line 41
2017-03-14 14:49:08.076 [error] <0.348.0> Supervisor {<0.348.0>,poolboy_sup} had child mc_worker started with {mc_worker,start_link,undefined} at <0.1385.0> exit with reason <<"Can't pass authentification">> in context child_terminated
2017-03-14 14:49:13.080 [error] <0.339.0> Supervisor vmq_diversity_sup had child vmq_diversity_plugin started with vmq_diversity_plugin:start_link() at <0.340.0> exit with reason killed in context shutdown_error
```
3. The mongo db container logs has the following:
```
2017-03-14T14:48:53.556+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:50455 #554145 (5 connections now open)
2017-03-14T14:48:53.808+0000 I -        [conn554142] end connection xx.yy.xx.www:54521 (5 connections now open)
2017-03-14T14:48:53.811+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:57088 #554146 (5 connections now open)
2017-03-14T14:48:53.866+0000 I -        [conn554144] end connection xx.yy.xx.www:43492 (5 connections now open)
2017-03-14T14:48:53.873+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:39325 #554147 (5 connections now open)
2017-03-14T14:48:53.883+0000 I -        [conn554141] end connection xx.yy.xx.www:45047 (5 connections now open)
2017-03-14T14:48:53.887+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:45053 #554148 (5 connections now open)
2017-03-14T14:48:53.902+0000 I -        [conn554145] end connection xx.yy.xx.www:50455 (5 connections now open)
2017-03-14T14:48:53.905+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:41095 #554149 (5 connections now open)
2017-03-14T14:48:53.929+0000 I -        [conn554143] end connection xx.yy.xx.www:49594 (5 connections now open)
2017-03-14T14:48:53.929+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:57615 #554150 (5 connections now open)
2017-03-14T14:48:53.962+0000 I -        [conn554146] end connection xx.yy.xx.www:57088 (5 connections now open)
2017-03-14T14:48:53.967+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:56311 #554151 (5 connections now open)
2017-03-14T14:48:53.983+0000 I -        [conn554147] end connection xx.yy.xx.www:39325 (5 connections now open)
2017-03-14T14:48:53.989+0000 I NETWORK  [thread1] connection accepted from xx.yy.xx.www:57833 #554152 (5 connections now open)
2017-03-14T14:48:54.024+0000 I -        [conn554148] end connection xx.yy.xx.www:45053 (5 connections now open)
```

Having another broker with the same credentials, allows to connect to mongo successfully:
```
2017-03-14T14:28:48.218+0000 I ACCESS   [conn554133] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.218+0000 I ACCESS   [conn554134] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.220+0000 I ACCESS   [conn554135] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.223+0000 I ACCESS   [conn554137] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.225+0000 I ACCESS   [conn554138] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.227+0000 I ACCESS   [conn554136] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.230+0000 I ACCESS   [conn554140] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:28:48.235+0000 I ACCESS   [conn554139] Successfully authenticated as principal emqtt on mqtt
2017-03-14T14:29:22.342+0000 I -        [conn554139] end connection xx.yy.xx.www:36290 (8 connections now open)
2017-03-14T14:29:22.342+0000 I -        [conn554137] end connection xx.yy.xx.www:58476 (7 connections now open)
2017-03-14T14:29:22.342+0000 I -        [conn554134] end connection xx.yy.xx.www:57675 (6 connections now open)
2017-03-14T14:29:22.342+0000 I -        [conn554135] end connection xx.yy.xx.www:4320 (5 connections now open)
2017-03-14T14:29:22.342+0000 I -        [conn554140] end connection xx.yy.xx.www:64211 (4 connections now open)
2017-03-14T14:29:22.343+0000 I -        [conn554133] end connection xx.yy.xx.www:32175 (3 connections now open)
2017-03-14T14:29:22.343+0000 I -        [conn554136] end connection xx.yy.xx.www:23794 (2 connections now open)
2017-03-14T14:29:22.342+0000 I -        [conn554138] end connection xx.yy.xx.www:62338 (8 connections now open)
```

Guys, do you expect a plain text password in the `vmq_diversity.mongodb.password` property.

Thanks!

**Comment by larshesel** [comment] 2017-03-15 08:33
Hi @ig0r thanks for reporting - I'll try to investigate this.

**Comment by ig0r** [comment] 2017-03-15 08:35
@larshesel great, thanks!

**Comment by larshesel** [comment] 2017-03-15 09:39
Hi @ig0r 

I was easily able to reproduce this and it is due to the pbkdf2 library not being included in the VerneMQ release. The fix now has to be reviewed and if it passes it will be merged to master and included in the next release candidate.

Thanks again for reporting.

**Comment by ig0r** [comment] 2017-03-15 09:42
OK, great!

Any chance you could include it in a nightly build?

**Comment by larshesel** [comment] 2017-03-15 09:50
yes, of course - as soon as it's merged to master a nightly build will be started. I'll let you know.

**Comment by ig0r** [comment] 2017-03-15 09:55
great, thanks!

**Closed** 2017-03-15 13:13 UTC
Labels: in progress

**Comment by larshesel** [comment] 2017-03-15 14:28
The fix has been pushed to master and the nightly packages have been built and should be downloadable from the website.
