### ISSUE TITLE
WebSocket cant_parse_variable_header

### ISSUE THREAD

**Issue by rpavlovs** [erlio/vernemq#406] opened 2017-06-08 02:56 UTC
### Environment

- VerneMQ Version: 1.0.1
- OS: Ubuntu

### Expected behavior

1. Connect with [HiveMQ webclient](http://www.hivemq.com/demos/websocket-client/)
2. Publish a message to a topic with QoS 2.

### Actual behaviour

On step 2 client disconnects immediately. Happens with QoS 2 only.

**console.log**
```
2017-06-08 02:38:00.261 [warning] <0.13109.138>@vmq_websocket:handle_fsm_return:102 ws session stopped abnormally due to '{error,unexpected_message,{error,cant_parse_variable_header}}'
```

**Comment by ioolkos** [comment] 2017-06-08 07:18
@rpavlovs thanks, I confirmed this.
It's interesting, as it only happens after VerneMQ sent the PUBREC apparently. So it's either that or the following PUBREL.
Will try to investigate.

```erlang
➜  vernemq git:(master) ✗ _build/default/rel/vernemq/bin/vmq-admin trace client client-id=clientId-2IY7KHqulL
Starting trace for 1 existing sessions for client "clientId-2IY7KHqulL" with PIDs
    [<7251.455.0>]

<7251.455.0> MQTT RECV: CID: "clientId-2IY7KHqulL" PUBLISH(d0, q2, r0, m1, "testtopic/1") with payload:
    test
<7251.455.0> Calling auth_on_publish(undefined,{[],<<"clientId-2IY7KHqulL">>},2,testtopic/1,false) with payload:
    test
<7251.455.0> Hook returned "ok"
<7251.455.0> MQTT SEND: CID: "clientId-2IY7KHqulL" PUBREC(m1)
<7251.455.0> Trace session for clientId-2IY7KHqulL stopped
```

**Comment by larshesel** [comment] 2017-06-08 14:04
Since it happens with QoS2 only and websockets is only a transport (doesn't care what is sent) and VerneMQ otherwise works with QoS2 I'm thinking it's maybe a bug in the HiveMQ websocket MQTT client. Do you have a way to test with another websocket client or try the HiveMQ websocket client against another broker which supports websockets?

**Comment by larshesel** [comment] 2017-06-08 15:24
This is a duplicate of #31 and is because the HiveMQ client is not adhering to the MQT 3.1.1 spec.

**Closed by larshesel** 2017-06-08 15:24 UTC
