### ISSUE TITLE
vernemq

### ISSUE THREAD

**Issue by keepexploring** [erlio/vernemq#254] opened 2017-01-09 11:22 UTC
Hi,

I use vernemq regularly and really like it. However, I find it often crashes, for reasons which are not always clear. I set up monit to auto restart. e.g. it seems to be possible to crash it by a node trying to log on twice. This surprised me since it is written in Erlang. Is there a a way to auto restart/improve its robustness?

Thanks so much

Joel

**Comment by larshesel** [comment] 2017-01-09 11:52
Hi @keepexploring 

We're sorry to hear that you're experiencing crashes as VerneMQ is built to be very stable and for high availability, so we would love to hear more about the issues you are having and find the root cause. Could you provide some more details to reproduce and the output of the console.log, crash.log and error.log files? Are you using any custom plugins? Also, which version of VerneMQ are you using? The latest release is 0.15.2-1, but that one contains a bug in the retain mechanism, so until our next proper release it would be better to use the nightly builds. See http://vernemq.com/downloads/.

When you say it's possible to crash it by a client logging on twice, I suppose you mean with the same client-id? I can't seem to reproduce any crashes doing that. Are you experiencing this crash on a single node or in a cluster setup?

Best regards,
Lars

**Comment by keepexploring** [comment] 2017-01-09 21:22
Hi Lars,

Thanks so much for getting back to me. I will send you the output of the
logs for you to take a look at. Thanks so much.

Joel

**Comment by keepexploring** [comment] 2017-01-10 14:05
Hi Lars,

Is it secure to just send you all the log files on here? (I guess they
appear on the github issues page) or should I send to another email.

Thanks,

Joel

**Comment by larshesel** [comment] 2017-01-10 14:08
Hi,

Please send them to lars  at vernemq dot com.
1) a description of how you reproduce the issue
2) which version of VerneMQ you are using and if you are using any plugins please list them as well
3) the relevant log files

Then I'll take a look.

**Comment by larshesel** [comment] 2017-01-16 11:20
Hi @keepexploring 

As I haven't received anything from you, I just wanted to check up if you still have the issues you described? As it is very unusual for VerneMQ to behave in such an unstable way as you describe, we'd like to see if we can figure out what the root cause is.

**Comment by keepexploring** [comment] 2017-01-17 12:37
Hi Lars,

Sorry for slow response. When will the next release be? I'm thinking I'll
wait until then, and in the meantime, I have monit running and restarting
the vernemq script when required. If after the new release I am still
having the issues I will let you know. I just don't want to waste your time
if there will be a new release coming out soon which solves the issue.

Thanks so much,

Joel

**Comment by larshesel** [comment] 2017-01-17 13:41
0.15.3 was released last week - maybe you'd want to try that? In any case, let me know if you still have the issue after having upgraded. Closing this for now.

**Closed by larshesel** 2017-01-17 13:41 UTC
