### ISSUE TITLE
'metrics show' counters needs fix 

### ISSUE THREAD

**Issue by dramasamy** [erlio/vernemq#671] opened 2018-04-30 04:08 UTC
### Environment

- VerneMQ Version: 1.3.1
- OS: Ubuntu 16 
- Erlang/OTP version (if building from source):

### Expected behavior

The total number of publish/pub ack/ conn / connack counters needs to be exact. 

Please move this report to 'question' in case the behavior is expected. 

### Actual behavior

Steps:

1. reset metrics 
2. make sure no active/online clients 
3. start trace 
4. metrics how 
5. Subscribe to topic vmq  (client id 'consumer1')
6. Check trace 
7. metrics show --> unexpected conn received count and publish received 
8. publish message to topic vmq from client id 'device1'

Commands and logs:
---------------------

Subscribe:
-----------
mosquitto_sub -c -i consumer1 -h dragon -P mqtt-test -u mqtt-test -t vmq -q 1 -k 60

Trace after subscribe:
---------------------

No sessions found for client "consumer1"
New session with PID <7251.832.0> found for client "consumer1"
<7251.832.0> MQTT RECV: CID: "consumer1" CONNECT(c: consumer1, v: 3, u: mqtt-test, p: mqtt-test, cs: 0, ka: 60)
<7251.832.0> MQTT SEND: CID: "consumer1" CONNACK(sp: 1, rc: 0)
<7251.832.0> MQTT RECV: CID: "consumer1" SUBSCRIBE(m1) with topics:
    q:1, t: "vmq"
<7251.832.0> Calling auth_on_subscribe(mqtt-test,{[],<<"consumer1">>}) with topics:
    q:1, t: "vmq"
<7251.832.0> Hook returned "ok"
<7251.832.0> MQTT SEND: CID: "consumer1" SUBACK(m1, qt[1])

metrics after subscribe:
-----------------------

root@dragon:~# vmq-admin metrics show | grep mqtt
counter.mqtt_connect_received = 59
counter.mqtt_publish_received = 11
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 1
counter.mqtt_disconnect_received = 0
counter.mqtt_connack_accepted_sent = 1
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 1
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 1
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 0
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0

Publish:
-------

mosquitto_pub -h dragon -p 1883 -m "Data" -t vmq -u mqtt-test -P mqtt-test -q 1 -i device1 

Trace after publish:
-------------------

root@dragon:~# vmq-admin trace client client-id=consumer1
No sessions found for client "consumer1"
New session with PID <7251.832.0> found for client "consumer1"
<7251.832.0> MQTT RECV: CID: "consumer1" CONNECT(c: consumer1, v: 3, u: mqtt-test, p: mqtt-test, cs: 0, ka: 60)
<7251.832.0> MQTT SEND: CID: "consumer1" CONNACK(sp: 1, rc: 0)
<7251.832.0> MQTT RECV: CID: "consumer1" SUBSCRIBE(m1) with topics:
    q:1, t: "vmq"
<7251.832.0> Calling auth_on_subscribe(mqtt-test,{[],<<"consumer1">>}) with topics:
    q:1, t: "vmq"
<7251.832.0> Hook returned "ok"
<7251.832.0> MQTT SEND: CID: "consumer1" SUBACK(m1, qt[1])
<7251.832.0> MQTT RECV: CID: "consumer1" PINGREQ()
<7251.832.0> MQTT SEND: CID: "consumer1" PINGRESP()
<7251.832.0> MQTT RECV: CID: "consumer1" PINGREQ()
<7251.832.0> MQTT SEND: CID: "consumer1" PINGRESP()
<7251.832.0> MQTT SEND: CID: "consumer1" PUBLISH(d0, q1, r0, m1, "vmq") with payload:
    Data
<7251.832.0> MQTT RECV: CID: "consumer1" PUBACK(m1)

Metrics after Publish:
----------------------

root@dragon:~# vmq-admin metrics show | grep mqtt
counter.mqtt_connect_received = 67
counter.mqtt_publish_received = 12
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 1
counter.mqtt_disconnect_received = 2
counter.mqtt_connack_accepted_sent = 1
counter.mqtt_connack_unacceptable_protocol_sent = 1
counter.mqtt_connack_identifier_rejected_sent = 1
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 1
counter.mqtt_publish_auth_error = 1
counter.mqtt_subscribe_auth_error = 0
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0

**Comment by ioolkos** [comment] 2018-04-30 06:30
@dramasamy thanks for opening the issue!
I cannot reproduce your issue. What's weird is that at this point you also already have a couple of errors, like a pub-auth error, or unacceptable-protocol sent.

Do the metrics stay the same when you do not change anything more at this point?

**Comment by larshesel** [comment] 2018-05-07 10:52
Hi, since we weren't able to reproduce this I'm closing this issue for now.

**Closed by larshesel** 2018-05-07 10:52 UTC

**Comment by dramasamy** [comment] 2018-05-26 17:44
Hi Iarshesel, Sorry for the delayed response. I'm able to re-produce the issue. This time I ave installed the RPM pkg in centos and tried to publish one message and subscribed the same in localhost. 

gauge.queue_processes = 1
gauge.retain_memory = 21152
gauge.retain_messages = 0
gauge.router_memory = 12288
gauge.router_subscriptions = 1
gauge.system_utilization_scheduler_24 = 2
gauge.system_utilization_scheduler_23 = 2
gauge.system_utilization_scheduler_22 = 2
gauge.system_utilization_scheduler_21 = 3
gauge.system_utilization_scheduler_20 = 1
gauge.system_utilization_scheduler_19 = 2
gauge.system_utilization_scheduler_18 = 3
gauge.system_utilization_scheduler_17 = 1
gauge.system_utilization_scheduler_16 = 2
gauge.system_utilization_scheduler_15 = 4
gauge.system_utilization_scheduler_14 = 1
gauge.system_utilization_scheduler_13 = 5
gauge.system_utilization_scheduler_12 = 2
gauge.system_utilization_scheduler_11 = 4
gauge.system_utilization_scheduler_10 = 2
gauge.system_utilization_scheduler_9 = 2
gauge.system_utilization_scheduler_8 = 4
gauge.system_utilization_scheduler_7 = 1
gauge.system_utilization_scheduler_6 = 5
gauge.system_utilization_scheduler_5 = 4
gauge.system_utilization_scheduler_4 = 3
gauge.system_utilization_scheduler_3 = 16
gauge.system_utilization_scheduler_2 = 4
gauge.system_utilization_scheduler_1 = 1
gauge.system_utilization = 3
gauge.vm_memory_ets = 5835312
gauge.vm_memory_code = 10048342
gauge.vm_memory_binary = 1543312
gauge.vm_memory_atom_used = 460299
gauge.vm_memory_atom = 463465
gauge.vm_memory_system = 40071816
gauge.vm_memory_processes_used = 7632080
gauge.vm_memory_processes = 7632456
gauge.vm_memory_total = 47704272
counter.system_wallclock = 879775
counter.system_runtime = 4800
gauge.system_run_queue = 0
counter.system_reductions = 14890466
counter.system_io_out = 706938
counter.system_io_in = 8789377
counter.system_words_reclaimed_by_gc = 29220323
counter.system_gc_count = 11439
counter.system_exact_reductions = 14890297
counter.system_context_switches = 61538
counter.socket_open = 16
counter.socket_close = 3
counter.socket_error = 5
counter.bytes_received = 20
counter.bytes_sent = 82
counter.mqtt_connect_received = 72
counter.mqtt_publish_received = 56
counter.mqtt_puback_received = 7
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 1
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 8
counter.mqtt_disconnect_received = 22
counter.mqtt_connack_accepted_sent = 13
counter.mqtt_connack_unacceptable_protocol_sent = 3
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_connack_server_unavailable_sent = 1
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 1
counter.mqtt_pubrec_sent = 1
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 8
counter.mqtt_publish_auth_error = 22
counter.mqtt_subscribe_auth_error = 13
counter.mqtt_invalid_msg_size_error = 3
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 0
counter.queue_teardown = 0
counter.queue_message_drop = 1
counter.queue_message_unhandled = 0
counter.queue_message_in = 0
counter.queue_message_out = 0
counter.client_expired = 1
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 0
counter.cluster_bytes_dropped = 0

Config : Default Config with 0.0.0.0:1883 listener

**Comment by dramasamy** [comment] 2018-05-26 17:47
You can e-mail (dineshkumarr.ramasamy@gmail.com) me to get the server access if you like to see what is going on.

**Comment by ioolkos** [comment] 2018-05-26 20:08
Ok, thanks for re-opening. Does the client connect over a firewall? Ther is only the mosquitto_sub running as the only client?
Do you have VerneMQ or custom plugins running? What happens if you don't use 0.0.0.0 but specific IP interface only?

**Comment by dramasamy** [comment] 2018-05-26 23:49
Hi, Please find the details as follows. 

OS : CentOs 7 
Number of Sub : 1 
Number Of Pub : 1 

I have re-imaged the server with CentOs 7 and installed the RPM package. After the OS installation, I just executed following commands. 

    1  wget https://bintray.com/artifact/download/erlio/vernemq/rpm/centos7/vernemq-1.4.0-1.el7.centos.x86_64.rpm
    2  yum install vernemq-1.4.0-1.el7.centos.x86_64.rpm
    3  ifconfig
    4  vi /etc/vernemq/vernemq.conf
    5  service vernemq restart
    6  ifconfig
    7  vmq-passwd -h
    8  vmq-passwd -c /etc/vernemq/vernemq.passwd
    9  vmq-passwd -c /etc/vernemq/vernemq.passwd dinesh
   10  vi /etc/vernemq/vernemq.conf
   11  service vernemq restart
   12  vmq-admin metrics show
   13  history 

counter.mqtt_connect_received = 113
counter.mqtt_publish_received = 45
counter.mqtt_puback_received = 1
counter.mqtt_pubrec_received = 1
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 1
counter.mqtt_disconnect_received = 0
counter.mqtt_connack_accepted_sent = 1
counter.mqtt_connack_unacceptable_protocol_sent = 1
counter.mqtt_connack_identifier_rejected_sent = 1
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 1
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 1
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 1
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 0
counter.queue_teardown = 0
counter.queue_message_drop = 0
counter.queue_message_unhandled = 1
counter.queue_message_in = 0
counter.queue_message_out = 0
counter.client_expired = 0
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 0
counter.cluster_bytes_dropped = 0

I used following commands in my local laptop, 

mosquitto_sub -c -i bbioPlatformBhoruka1 -h <ServerIP> -P dinesh -u dinesh -t bbio/bhoruka/publish -q 1 -k 5
mosquitto_pub -h <ServerIP> -p 1883 -m "Data" -t bbio/bhoruka/publish -u dinesh -P dinesh -q 1

**Comment by ioolkos** [comment] 2018-05-27 07:00
At this point, please close the mosquitto_sub subscription. After that, do the metrics stay the same? in particular, do the `counter.mqtt_connect_received` and `counter.mqtt_publish_received` change?

**Comment by ioolkos** [comment] 2018-05-27 07:04
I'll get back to you via E-mail as suggested.
