### ISSUE TITLE
Shared subscribers

### ISSUE THREAD

**Issue by tomazbracic** [erlio/vernemq#278] opened 2017-02-17 13:37 UTC
### Environment

- VerneMQ Version: vernemq_0.15.3-1_amd64.deb
- OS: ubuntu 16.04
- Erlang/OTP version (if building from source): 

### Expected behavior

- Please describe the expected behaviour.

I thought that shared subscription should work in a way that all subscribers would get messages from shared topic in a way that messages are not duplicated, that if i have 2 subscribers messages would come to them in something like round robin fashion. BUT mainly, if 1 subscriber goes down... the other one would be processing all the messages. 

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

I started 2 subscribes (both subscribed to the same '$share/sharename/testshare' topic. After this i started to publish messages to this topic. While both subscribers were up... all was ok. Messages came in round robin. Then I took down one of the subscribers. Then tests were done with QoS 0 (messages) and later, since it didn't work as I suspected to, I published messages with QoS 1.
But in both cases... :

1.) remaining subscriber did not receive messages. I think it was that it got 2 out of 10 messages. Sometimes none. 

2.) if I brought up the second subscriber again... none of them received any messages.

**Comment by ioolkos** [comment] 2017-02-17 14:02
Hi @tomazbracic 

thanks for the writeup. We cannot reproduce this. How are you testing it? do you use mosquitto_sub? or another client? is it a single broker, or a clustered setup?
could you provide the exact way you're doing this? we should then be able to resolve this.

thanks for your help & patience :)

**Comment by tomazbracic** [comment] 2017-02-17 14:21
I have 2 node cluster. Both nodes are running on AWS. My test server is outside of AWS, but still in cloud. On this test server I have started 2 subscribers and 1 publisher. Yes, both subscribers and publisher are from mosquito project (mosquitto_pub, mosquitto_sub). I do use TLS termination behind AWS ELB but this should not be a problem, since infrastructure setup is (was) working - but shared subscriptions does not. 

I do have things that I add in cluster setup (vernemq.conf)... for instance:

# IPs are of course different in configuration files. This is more for important keys... what I have and what I don't have set.

nodename = VerneMQ@<internal AWS IP>
distributed_cookie = <some long text>
allow_annonymous = on    # since I am behind AWS firewall and behind 2-way TLS termination
listener.tcp.default = <internal AWS IP>:<port>


And this is pretty much all that I recon is important. 

On that test server... I test like this. 

# subscriber(s)
mosquitto_sub --cafile rootCA.crt --cert cert.pem --key privatekey.pem -h <FQDN - AWS ELB> -p <PORT> -t '$share/sharename/testshare'

# publisher
mosquitto_pub --cafile rootCA.crt --cert cert.pem --key privatekey.pem -h <FQDN - AWS ELB> -p <PORT> -t '$share/sharename/testshare' -q 1 -m <some message text>

**Comment by larshesel** [comment] 2017-02-17 14:45
Does it work if you skip the load balancer and test directly against the cluster? Is the cluster status OK on both nodes (output of `vmq-admin cluster status`)?

**Comment by ioolkos** [comment] 2017-02-17 14:51
maybe just a typo, but the publisher should read:

// publisher
mosquitto_pub --cafile rootCA.crt --cert cert.pem --key privatekey.pem -h <FQDN - AWS ELB> -p <PORT> -t `'testshare'` -q 1 -m <some message text>

**Comment by tomazbracic** [comment] 2017-02-17 20:48
@ioolkos it was not a typo. My bad. 

@larshesel Load balancer is configured with Proxy protocol which means, ELB is doing nothing else but routing messages between 2 nodes behind. It works without problems in configuration without shared subscribers. And this setup is quite common. Will try to test from inside the AWS, but then this is no good to me and I don't understand then.

**Comment by ioolkos** [comment] 2017-02-17 22:16
Allright, thanks @tomazbracic 
We'll try to look into this tomorrow. It almost sounds like some kind of interaction effect between the load balancer strategy and the shared subscription strategy (prefer_local, local only etc).

**Comment by tomazbracic** [comment] 2017-02-17 22:17
@ioolkos 
I do have this set in vernemq.conf

shared_subscription_policy = prefer_local

**Comment by larshesel** [comment] 2017-02-18 08:02
To have a better chance at understanding what's going on here, could you provide us with the logs from both servers (debug loglevel) together with a transcript of the client commands that you execute (with the -d flag set, so we can see client-id's etc)?

The cluster status of both nodes before starting the experiment would also be helpful.

It would still be very helpful to see if you can reproduce this when bypassing the load balancer. It helps is simplify and localize the problem.

**Comment by larshesel** [comment] 2017-02-18 08:08
One other thing which just dawned on me: You wrote you're using the 0.15.3-1 package? That one does not contain shared subscriptions feature as this is still only in the nightly package and not in a tagged release. Exactly which packages are deployed in the cluster?

**Comment by tomazbracic** [comment] 2017-02-18 19:16
@ioolkos 

package that i use is vernemq_0.15.3-1_amd64.deb. If you need more specific, please tell me how to provide the more exact info.

**Comment by larshesel** [comment] 2017-02-18 19:33
Then you're not running a version capable of shared subscriptions as that feature has not yet been included in a tagged release, but is only available in the nightly builds. See also the changelog: https://github.com/erlio/vernemq/blob/master/changelog.md#changelog . We'll likely release a proper tagged release next week which includes the shared subscriptions, but in the meantime you can download the nightly builds over here: http://vernemq.com/downloads/index.html

**Comment by larshesel** [comment] 2017-02-20 10:31
Based on your email I guess we can close this issue as the issues you're having now there is not relelated to shared subscriptions, but rather systemd/init scripts. We'll try to respond to your mail as soon as possible - but please allow for some time as we're swamped ATM. Thanks for helping us learn about the rougher edges and corners of Verne!

**Closed by larshesel** 2017-02-20 10:31 UTC
