### ISSUE TITLE
Unable to use redis for authentication

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#444] opened 2017-07-16 07:51 UTC
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): 20

`
/var/log/vernemq/error.log
2017-07-16 07:42:09.628 [error] <0.344.0> Supervisor vmq_diversity_sup had child vmq_diversity_plugin started with vmq_diversity_plugin:start_link() at <0.345.0> exit with reason killed in context shutdown_error
`

`
/var/log/vernemq/console.log 
2017-07-16 07:42:13.231 [info] <0.215.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir /var/lib/vernemq/meta/meta/11 options for LevelDB: [{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,36404174}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2017-07-16 07:42:13.275 [info] <0.31.0> Application plumtree started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:13.289 [info] <0.31.0> Application vmq_plugin started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:13.289 [info] <0.31.0> Application ssl_verify_fun started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:13.289 [info] <0.31.0> Application epgsql started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:13.305 [info] <0.31.0> Application hackney started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:14.528 [info] <0.217.0>@vmq_cluster:init:113 plumtree peer service event handler 'vmq_cluster' registered
2017-07-16 07:42:14.678 [info] <0.330.0>@vmq_reg_trie:handle_info:183 loaded 1 subscriptions into vmq_reg_trie
2017-07-16 07:42:15.113 [info] <0.31.0> Application vmq_diversity started on node 'VerneMQ@127.0.0.1'
2017-07-16 07:42:15.214 [info] <0.348.0>@vmq_diversity_app:start:71 enable auth script for redis "/usr/share/vernemq/lua/auth/redis.lua"
`

`
/var/log/vernemq/crash.log
2017-07-16 07:42:09 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_diversity_sup}
     Context:    shutdown_error
     Reason:     killed
     Offender:   [{pid,<0.345.0>},{id,vmq_diversity_plugin},{mfargs,{vmq_diversity_plugin,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
`
Redis server is working fine.

While trying to connect to the vernemq server, I found this in logs
`
/var/log/vernemq/console.log
2017-07-16 07:49:26.167 [warning] <0.3489.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_0_0">>} due to error
2017-07-16 07:49:27.169 [warning] <0.3490.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_0_0">>} due to error
2017-07-16 07:49:29.171 [warning] <0.3491.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_0_0">>} due to error
2017-07-16 07:49:33.174 [warning] <0.3492.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_0_0">>} due to error
`

**Comment by larshesel** [comment] 2017-07-17 08:57
How did you configure redis in the `vernemq.conf` file? It looks like the redis client was not able to connect to the redis server when VerneMQ was started.

**Comment by vedavidhbudimuri** [comment] 2017-07-17 09:07
Hey @larshesel,
Thanks for the reply. I'm able to open redis shell, its hosted locally on default port and no password has been set up. Can you tell me what else I could provide to make this issue more clear?

**Comment by larshesel** [comment] 2017-07-17 09:25
Can you show us a complete console.log and crash.log file (please delete the files before starting VerneMQ to avoid having old data in them) when reproducing this?

**Comment by larshesel** [comment] 2017-07-19 07:47
Let me know if this issue is still relevant (looks like you've moved on to build plugins in erlang), so closing for now.

**Closed by larshesel** 2017-07-19 07:47 UTC

**Comment by vedavidhbudimuri** [comment] 2017-07-21 02:44
Hey @larshesel , I have written a small plugin which adds every message to a queue. It would be grateful if you could take a look, As I am completely new to erlang. I was unable to add predefined messages i.e connect, disconnect, subscribe message to rabbitmq. Can u suggest some way?
Please do mention any minor suggestions to the plugin, I want to make this plugin production ready.

Plugin: https://bitbucket.org/vedavidhbudimuri/vmq_rab_queue/

**Comment by larshesel** [comment] 2017-07-21 06:42
Hi @vedavidhbudimuri 

I don't have the time at the moment to do such a code review - I glanced at the code and thought it looked 'nice' but I didn't look at the semantics or anything.

**Comment by vedavidhbudimuri** [comment] 2017-07-21 06:59
Thank you @larshesel for your time. 
The console out for the redis auth testing is 
`2017-07-21 06:55:16.181 [warning] <0.367.0>@vmq_diversity_cache:validate_acl:307 unknown property {<<"topic">>,<<"#">>} for ACL {publish_acl,undefined,2,268435456,1,undefined}`
`2017-07-21 06:55:16.181 [warning] <0.367.0>@vmq_diversity_cache:validate_acl:307 unknown property {<<"topic">>,<<"#">>} for ACL {subscribe_acl,undefined,2,undefined}`
`2017-07-21 06:55:16.207 [error] <0.489.0>@vmq_mqtt_fsm:auth_on_publish:660 can't auth publish [<<"client_1">>,{[],<<"client_1">>},1,[<<"topic">>,<<"write">>,<<"source">>,<<"client_0">>],<<"Message from client 1">>,false] due to error`


And to populate redis
`SET "[\"\",\"client_1\",\"client_1\"]" "{\"passhash\":\"$2a$12$C.Ceq7dgVgbuNBT.BDpFSu6w1iaIDMPzsJ4lIaK.uc3OQt.RdItBe\",\"subscribe_acl\":[{\"topic\":\"#\"}],\"publish_acl\":[{\"topic\":\"#\"}]}"`

password is same as username i.e client_1
