### ISSUE TITLE
Cannot reconnect to session (clean_session = false) after having subscribed to shared subscription

### ISSUE THREAD

**Issue by jnicholls** [erlio/vernemq#827] opened 2018-09-11 02:25 UTC
### Environment

- VerneMQ Version: 1.4.1
- OS: Debian Stretch host (running docker-vernemq container)
- Erlang/OTP version (if building from source):

### Expected behavior

I have a service that subscribes to a shared subscription (for the day I need to scale it out horizontally), and all messages on this topic are QoS 1. I have a persistent client expiration of `1d` and max offline messages of `50000000`. If this client disconnects and then reconnects with `clean_session = false` and the same client id, then the expectation is that all queued messages are released to it once it reconnects.

### Actual behaviour

The client cannot successfully reconnect. The session looks and remains as followed from a `vmq-admin session show` output:

```
+----------------+---------+----------+-------------+---------+----------------+
|   client_id    |is_online|mountpoint|  peer_host  |peer_port|      user      |
+----------------+---------+----------+-------------+---------+----------------+
|SWW6011011006458|  true   |          |  redacted   |  39996  |SWW6011011006458|
|SWW6011011006550|  true   |          |  redacted   |  23944  |SWW6011011006550|
|SWW6011011000801|  true   |          |  redacted   |  14492  |SWW6011011000801|
|SWW6011011006209|  true   |          |  redacted   |  29784  |SWW6011011006209|
|SWW6011011006519|  true   |          |  redacted   |  59083  |SWW6011011006519|
|SWW6011011000606|  true   |          |  redacted   |  12845  |SWW6011011000606|
|SWW6011011006268|  true   |          |  redacted   |  58662  |SWW6011011006268|
|SWW6011011006203|  true   |          |  redacted   |  14195  |SWW6011011006203|
|SWW6011011006499|  true   |          |  redacted   |  1720   |SWW6011011006499|
|device-service-0|  false  |          |    null     |  null   |      null      |
```

Notice that it stays in a "null" state. The client is never able to reconnect while vernemq remains in this state.

In order to resolve the situation, I must run:

```
vmq-admin session disconnect client-id=device-service-0 --cleanup
```

The session has to be completely cleaned up from the broker(s) (I have 2 by the way), which then lets the client successfully reconnect...albeit all queued messages are lost of course.

Does 1.5.0 resolve this by chance? Thanks in advance!

**Comment by larshesel** [comment] 2018-09-11 05:39
Hi, thanks for opening this issue. Could you start a trace for the client on the node where the client will connect using `vmq-admin trace client client-id=device-service-0` before connecting and see how it looks when it connects? Also, what is the error from the client perspective?

**Comment by larshesel** [comment] 2018-09-11 11:38
Great - it would also be good to know if you there are any errors in the logs which might be related.

**Comment by jnicholls** [comment] 2018-09-11 11:53
I will share it all, sure. When I examined the logs there was nothing of interest in them related to the failed attempts to connect. I am using default logging as the docker container has setup; I will also attempt more verbose logging.

**Comment by larshesel** [comment] 2018-09-18 15:20
Closing this for now - we can reopen if more information becomes available.

**Closed by larshesel** 2018-09-18 15:20 UTC

**Comment by larshesel** [comment] 2018-09-18 15:45
yes, I can't reproduce this:

```
$ mosquitto_sub -t '$share/world/blah' -d -q 1  -V mqttv311 -c -i client
Client client sending CONNECT
Client client received CONNACK
Client client sending SUBSCRIBE (Mid: 1, Topic: $share/world/blah, QoS: 1)
Client client received SUBACK
Subscribed (mid: 1): 1
^C
$ mosquitto_sub -t '$share/world/blah' -d -q 1  -V mqttv311 -c -i client
Client client sending CONNECT
Client client received CONNACK
Client client sending SUBSCRIBE (Mid: 1, Topic: $share/world/blah, QoS: 1)
Client client received SUBACK
Subscribed (mid: 1): 1
^C
```

I haven't tested on 1.4.1, this was current master.

**Comment by larshesel** [comment] 2018-09-18 15:49
I cannot reproduce it on 1.4.1 either. There must be something else going on in your setup or I'm missing something,
