### ISSUE TITLE
vernemq cannot start because of unknown_module 

### ISSUE THREAD

**Issue by TangMonk** [erlio/vernemq#189] opened 2016-08-20 14:50 UTC
I do following command:

```
$ bin/vmq-admin plugin enable --name=vmq_diversity --path=/Users/tangmonk/Downloads/vmq_diversity/_build/default/

$ bin/vmq-admin plugin disable --name=vmq_diversity

$ bin/vmq-admin plugin enable --name=vmq_diversity

$ bin/vernemq console

[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Eshell V7.2.1  (abort with ^G)
(VerneMQ@127.0.0.1)1> {"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,{unknown_module,vmq_diversity_plugin}}},{gen_server,call,[vmq_plugin_mgr,{enable_module_plugin,change_config,vmq_config,change_config,1},infinity]}}}},{vmq_server_app,start,[normal,[]]}}}"}

Crash dump is being written to: /erl_crash.dump...Kernel pid terminated (application_controller) ({application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,{unknown_module,vmq_diversity_plugin}}},{g
```

I think the problem is when I enable `vmq_diversity` without specify `--path` option at second time, So vernemq cannot find where is the module. But I can do this with build-in modules(vmq_passwd, vmq_acl).

Now I cannot start the vernemq, I think I should recompile the source code...

**Comment by dergraf** [comment] 2016-08-20 15:27
Your path is probably wrong. `//User` .

**Comment by TangMonk** [comment] 2016-08-20 15:44
@dergraf I am sorry, this command is a demonstration, I run this command at past hours, but I am sure I enabled the plugin.

The problem is how to start the vernemq without recompile, and the project should avoid this situation happen.

**Comment by dergraf** [comment] 2016-08-20 17:32
You could manually edit the `vmq_plugin.conf` file. I am on mobile right now so I cant give you the correct path. It's somewhere in the vernemq lib folder.

**Comment by ioolkos** [comment] 2016-08-20 18:57
If you need to manually disable a plugin, because it prevents VerneMQ from booting, you can delete if from `_build/default/rel/vernemq/lib/vmq_plugin.conf`

Delete the line that starts with {application, vmq_diversity and then add the closing brackets. It then looks sth like below:

```erlang
{plugins,[{application,vmq_passwd,[]},
          {application,vmq_acl,[]},
          {module,vmq_config,[{hooks,[{change_config,change_config,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_write,msg_store_write,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_delete,msg_store_delete,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_find,msg_store_find,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_read,msg_store_read,2}]}]}]}.
```

But yes, the behaviour you found is very confusing and we need to fix this.

Thank you very much for reporting it & apologies for any delay in understanding and answering today.

**Comment by TangMonk** [comment] 2016-08-21 02:08
@ioolkos thanks very much 👍

**Comment by larshesel** [comment] 2016-08-22 13:11
Hi there - as the errors says vernemq cannot start due to `{stop,plugin_not_found}` - in this case it looks like the problem is in the last line: `{application,vmq_diversity,[{paths,[]}]}]}.` since the `vmq_diversity` as the `paths` list is empty (`[]`).

If you remove this line so it reads:

```
{plugins,[{module,vmq_config,[{hooks,[{change_config,change_config,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_write,msg_store_write,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_delete,msg_store_delete,2}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_find,msg_store_find,1}]}]},
          {module,vmq_lvldb_store,
                  [{hooks,[{msg_store_read,msg_store_read,2}]}]},
          {application,vmq_passwd,[{paths,[]}]}.
```

You should be able to start vernemq again. How the config ended up with an empty path for the `vmq_diversity` plugin is a good question.

**Comment by larshesel** [comment] 2016-08-24 13:21
Hi @TangMonk did the above solve your problem? If not feel free to reopen or file a new issue.

**Closed by larshesel** 2016-08-24 13:21 UTC
