### ISSUE TITLE
[Errno 104] Connection reset by peer.

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#442] opened 2017-07-15 11:28 UTC
While load testing the facing [Errno 104] Connection reset by peer. I have spawned 100 processes with each creating 100 threading and each thread sending 100 messages. I'm using a single node here on a 16 GB system with 4 cores.

I'm using erlang 20, vernemq 1.1.0, OS Ubuntu

Here is the crash.log

2017-07-15 11:16:39 =ERROR REPORT====
** Generic server vmq_cluster_mon terminating
** Last message in was timeout
** When Server state == {state}
** Reason for termination ==
** {noproc,[{gen,do_for_proc,2,[{file,"gen.erl"},{line,261}]},{gen_event,rpc,2,[{file,"gen_event.erl"},{line,197}]},{vmq_cluster_mon,terminate,2,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/vmq_server/src/vmq_cluster_mon.erl"},{line,153}]},{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,629}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,795}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-07-15 11:16:39 =CRASH REPORT====
  crasher:
    initial call: vmq_cluster_mon:init/1
    pid: <0.3923.6>
    registered_name: vmq_cluster_mon
    exception exit: {noproc,[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,800}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [vmq_cluster_node_sup,vmq_server_sup,<0.238.0>]
    messages: []
    links: [<0.3921.6>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 324
  neighbours:

**Comment by ioolkos** [comment] 2017-07-15 12:03
close as duplicate of https://github.com/erlio/vernemq/issues/441

**Closed by ioolkos** 2017-07-15 12:03 UTC
