### ISSUE TITLE
VerneMQ Webhooks plugin doesn't catch events

### ISSUE THREAD

**Issue by PetrShypila** [erlio/vernemq#293] opened 2017-03-03 14:53 UTC
### Environment

- VerneMQ Version: 0.15.3
- OS: Linux Docker container

### Expected behavior

- Registered hooks trigger on subscribe

### Actual behaviour

- Not all sent messages received. No hooks triggered.

### Details

I use dockerized docker version. However, I also used original one, but always have same issues. 

During testing I launch broker, with webhooks plugin(for docker I installed this plugin, for version 1.0.0rc1 I just enabled it) and open single connection by using NodeJS `MQTT` library. Client code could be found [here](https://gist.github.com/PetrShypila/a3632cc57a75bce1ddb876ca4c1426d8). Auth service code used by webhooks is [here](https://gist.github.com/PetrShypila/9f4e0b25690df1b0ad460666fd036bf5).

One of problems is that client for example could receive a message or could not. Just a matter of luck. Sometimes brocker restart helps. It connects, subscribes, sends but doesn't receive a message back.

Second problem is regarding webhooks plugin.  Here is example how I register hook for plugin:
`vmq-admin webhooks register hook=auth_on_subscribe endpoint="http://10.30.160.145/auth_on_subscribe"`. After registration it is not visible in list of hooks on output from `vmq-admin plugin show` 

    +------------+-----------+-----------------+-----------------------------+
    |   Plugin   |   Type    |     Hook(s)     |            M:F/A            |
    +------------+-----------+-----------------+-----------------------------+
    | vmq_passwd |application|auth_on_register |vmq_passwd:auth_on_register/5|
    |  vmq_acl   |application| auth_on_publish |  vmq_acl:auth_on_publish/6  |
    |            |           |auth_on_subscribe| vmq_acl:auth_on_subscribe/3 |
    |vmq_webhooks|application|                 |                             |
    +------------+-----------+-----------------+-----------------------------+

But if I register it once again I receive a message that it is already registered. 

`can't register endpoint due to 'already_registered'`

Probably it expected behavior but for me would be obvious to see registered hooks for webhooks plugin in the table above. By the way, application which I use for webhooks plugin is definitely accessible from docker by provided url. I checked it via curl -X POST ... command

Also I have some errors from logs regarding webhooks plugin which are not obvious for me:

    2017-03-03 14:25:11.515 [error] <0.748.0> gen_server vmq_webhooks_plugin terminated with reason: no function clause matching lists:unzip([[{<<"http://10.30.160.145/auth_on_subscribe">>,#{base64_payload => true}}]], [], []) line 401
    2017-03-03 14:25:11.515 [error] <0.748.0> CRASH REPORT Process vmq_webhooks_plugin with 0 neighbours exited with reason: no function clause matching lists:unzip([[{<<"http://10.30.160.145/auth_on_subscribe">>,#{base64_payload => true}}]], [], []) line 401 in gen_server:terminate/7 line 814
    2017-03-03 14:25:11.515 [error] <0.747.0> Supervisor vmq_webhooks_sup had child vmq_webhooks_plugin started with vmq_webhooks_plugin:start_link() at <0.748.0> exit with reason no function clause matching lists:unzip([[{<<"http://10.30.160.145/auth_on_subscribe">>,#{base64_payload => true}}]], [], []) line 401 in context shutdown_error

Could you please assist me here?

**Comment by larshesel** [comment] 2017-03-03 15:33
Hi

Let's try and attack these things systematically and try to eliminate possible error sources. It is not clear to me what of the above comes from 0.15.3 and what comes from 1.0.0rc1 and they handle persisting of webhooks and plugins quite differently. So let's try to focus only on vernemq 1.0.0rc1 and see if we can make it work.

From what I see above you still have the `vmq_acl` and `vmq_passwd` plugins enabled, but since you're implementing all the auth hooks in your endpoint you might want to disable those plugins.

Further, the reason why you're not seeing the hooks when running `vmq-admin plugin show` is because the hooks are being registered as internal module plugins. This is of course not so obvious, but you can see them by running `vmq-admin plugin show --internal`. So, from a clean 1.0.0rc1 installation can you modify the `vernemq.conf` file in the following way:

```yaml
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on
vmq_webhooks.wh1.endpoint = http://10.30.160.145/auth_on_register
vmq_webhooks.wh1.hook = auth_on_register
vmq_webhooks.wh2.endpoint = http://10.30.160.145/auth_on_subscribe
vmq_webhooks.wh2.hook = auth_on_subscribe
vmq_webhooks.wh3.endpoint = http://10.30.160.145/auth_on_publish
vmq_webhooks.wh3.hook = auth_on_publish
```

And start vernemq.
Can you verify that the output of  `vmq-admin plugin show --internal` looks like:

```
+-------------------+-----------+-----------------+---------------------------------------+
|      Plugin       |   Type    |     Hook(s)     |                 M:F/A                 |
+-------------------+-----------+-----------------+---------------------------------------+
|    vmq_config     |  module   |  change_config  |      vmq_config:change_config/1       |
|  vmq_lvldb_store  |  module   | msg_store_write |   vmq_lvldb_store:msg_store_write/2   |
|  vmq_lvldb_store  |  module   |msg_store_delete |  vmq_lvldb_store:msg_store_delete/2   |
|  vmq_lvldb_store  |  module   | msg_store_find  |   vmq_lvldb_store:msg_store_find/1    |
|  vmq_lvldb_store  |  module   | msg_store_read  |   vmq_lvldb_store:msg_store_read/2    |
|   vmq_webhooks    |application|                 |                                       |
|vmq_webhooks_plugin|  module   |auth_on_register |vmq_webhooks_plugin:auth_on_register/5 |
|vmq_webhooks_plugin|  module   |auth_on_subscribe|vmq_webhooks_plugin:auth_on_subscribe/3|
|vmq_webhooks_plugin|  module   | auth_on_publish | vmq_webhooks_plugin:auth_on_publish/6 |
+-------------------+-----------+-----------------+---------------------------------------+
```

and of `vmq-admin wehbooks status` should look like:

```
+-----------------+--------------------------------------+-------------+
|      hook       |               endpoint               |base64payload|
+-----------------+--------------------------------------+-------------+
|auth_on_subscribe|http://10.30.160.145/auth_on_subscribe|    true     |
|auth_on_register |http://10.30.160.145/auth_on_register |    true     |
| auth_on_publish | http://10.30.160.145/auth_on_publish |    true     |
+-----------------+--------------------------------------+-------------+
```

And try to test if that works for you and what your experiences are?

It would be very interesting to know more about your message loss issues, but let's first see if we can get the webhooks config straightened out.

Hope this helps.

**Comment by PetrShypila** [comment] 2017-03-06 11:08
Hello Lars,

Thank you for fast reply. I played with VerneMQ 1.0.0rc1 during a weekend. Here is what I collected.

1. If I want to work with `vmq_webhooks` and also having `vmq_acl` and `vmq_passwd` plugins enabled 'auth_*' hooks should not be implemented. Now it is obvious for me.

2. Exactly this configuration caused problems with delivering messages. With `vmq_acl` and `vmq_passwd` plugins disabled `auth_on_scubscribe` hook was triggered. After I enabled these plugins hook stopped triggering and I started losing messages.

Thank you again for your help,
Petr

**Comment by larshesel** [comment] 2017-03-10 21:28
Hi Petr

It is possible to combine `vmq_acl` and vmq_passwd` with other plugins, but they need to be configured to do so (see the docs here  http://vernemq.com/docs/configuration/file-auth.html ). Note, that for instance `vmq_passwd` will reject a client which tries to connect without a username or a password in the connection message, but if the both are present but not available in the password file `vmq_passwd` will return `next` and the next registered `auth_on_register` hook will be allowed to run. This allows for composing authentication chains (similar for the other auth hooks).

I would expect something like this to be the reason why your hooks stopped being trigged when enabling the `vmq_passwd` and `vmq_acl` plugins. If you need those plugins, please make sure they're configured correctly. If you're still experiencing issues please try to set the log level to `debug` and send us a copy of it together with your vernemq.conf file and the exact steps used to reproduce the problem.

I hope this helps!

**Comment by larshesel** [comment] 2017-03-16 07:04
Hi @PetrShypila closing this - let us know if you run into other issues.

**Closed by larshesel** 2017-03-16 07:04 UTC
