### ISSUE TITLE
VerneMQ crashes reading metadata when restarted

### ISSUE THREAD

**Issue by rbino** [erlio/vernemq#703] opened 2018-05-16 10:01 UTC
### Environment

- VerneMQ Version: git master
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): `Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]`

### Actual behaviour

VerneMQ crashes when it is restarted after some metadata is added.

Steps to reproduce:

- Clone the repo
- `make rel`
- Add a test user for vmq-passwd
- Start VerneMQ
- Do some action that causes metadata to be written (e.g. `mosquitto_sub -u test -P test -t "#" -q 2 -d`)
- Stop VerneMQ
- Try restarting VerneMQ, it crashes

If I do `rm -rf _build/default/rel/vernemq/data/meta/` I can start VerneMQ again.

Here's the [error.log](https://github.com/erlio/vernemq/files/2008566/error.log) of the crash.

**Comment by larshesel** [comment] 2018-05-16 13:17
Hi, thanks for reporting -investigating. I suspect it has something to do with https://github.com/erlio/vernemq/pull/688

**Comment by larshesel** [comment] 2018-05-16 13:28
It indeed looks like it is commit e305f8e which caused this regression. Looking into how to fix it. /cc @dergraf

**Comment by larshesel** [comment] 2018-05-16 13:52
hi @rbino, can I get you to test the PR in #704 (https://github.com/larshesel/vernemq/tree/fix-metadata-regression)

**Comment by larshesel** [comment] 2018-05-16 21:58
Just merged #704 - thanks for reporting - it's really nice to have found this before releasing 1.4.0!

**Closed by larshesel** 2018-05-16 21:58 UTC
