### ISSUE TITLE
Failover Behavior for Clustered Broker System

### ISSUE THREAD

**Issue by hbahn** [erlio/vernemq#159] opened 2016-06-22 14:51 UTC
Hi, There, 

I am afraid that I am bothering all of you. :(

We set a clustered system for our broker system. We have been testing many failover cases.
However, we have some problems.

First of all, the first testing scenario is like this,

1. node 1 (on), node 2 (on)
2. node 1 (down forcedly), node 2 (on) - make the node 1 leave from cluster (put the leave command on the node 2) and node 1 (on)

**[Problem] the cluster does not accept SUBSCRIBE...(other Message types were not tested)
[Action what we did] so before we make node 1 on, we remove all the configuration files (under the directory /var/lib/vernemq) and the cluster is working well.**
**[Point what we concern] is the action (removing the configuration files and offline message under the directory /var/lib/vernemq) safe for resilience broker system?**

After that we tried the failover cases sequentially, 

1. node 1 (on), node 2 (on)
2. node 1 (down), node 2 (on)
3. node 1 (on), node 2 (on)
4. node 1 (on), node 2 (down)
5. node 1 (on), node 2 (on)
6. node 1 (down), node 2 (on)
7. node 1 (on), node 2 (on)

**[Problem] in the 7th step, we made the node 1 start (vernemq start, and we see that vernemq started properly). However, mqtt clients experienced CONNECT fails after several re-trials the client could CONNECT with cluster (one of nodes)**
**[Action what we did] nothing we can do... just wait..**

How can we overcome this problem..?
Thanks in advance.

**Comment by ioolkos** [comment] 2016-06-22 15:47
You're questions are very welcome & very helpful. Thank your very much!

We'll try to reproduce the situation as soon as possible. Feel free to send us the 2 vernemq.conf files per mail, if you'd like to.

**Comment by hbahn** [comment] 2016-06-22 16:15
Here is the configuration file.

two node's configuration is identical except for node name and ip address.

Thanks.
Hongbeom Ahn.



삼성 갤럭시 스마트폰에서 보냈습니다.


-------- 원본 이메일 --------
보낸 사람: ioolkos <notifications@github.com>
날짜: 16/6/23 오전 12:53 (GMT+09:00)
받은 사람: erlio/vernemq <vernemq@noreply.github.com>
참조: "안홍범/IoT Tech. Lab" <hb.ahn@sk.com>, Author <author@noreply.github.com>
제목: Re: [erlio/vernemq] Failover Behavior for Clustered Broker System (#159)


You're questions are very welcome & very helpful. Thank your very much!

We'll try to reproduce the situation as soon as possible. Feel free to send us the 2 vernemq.conf files per mail, if you'd like to.

-

**Comment by hbahn** [comment] 2016-06-22 16:24
I just sent that file you request on info@erl.io.

many thanks for your help again.

**Comment by ioolkos** [comment] 2016-06-22 16:26
Problem 1 has to do with the current behaviour if you make a stopped node leave. If you want the same node to be part of your cluster again, you need to delete it's data/meta folder, before restarting it, and then issue a cluster join again.
Otherwise you'll restart a node, that is basically trying to reach all the old cluster nodes it knew about, as it still thinks its a cluster.

We might find a way to make this more obvious or elegant.

**Comment by hbahn** [comment] 2016-06-22 16:35
Thanks for your quick response.

1) should we remove all the data and child directory under /var/lib/vernemq? is it okay when we do this procedure over and over? or any recommendation e.g., do not remove any specific directory or file.
2) in this case do we need to do leave command on correspondant node (here node 2 for the described problem)?

**Comment by ioolkos** [comment] 2016-06-22 16:42
I can't reproduce the second problem (delay in connecting after alternate node down) in a quick test. Will try more.

It's OK to remove data or data/meta, IF your realize what you throw away by doing that. But doing cluster leaves on stopped nodes as a regular procedure makes me think that you like to implement something else, for which it's maybe not meant for.
Like elastic behaviour? @dergraf comments on this?

**Comment by ioolkos** [comment] 2016-06-23 07:42
I still cannot reproduce problem 2 (delay in connecting after alternate node down).

How many clients/connections are on the broker nodes during this test?

**Comment by ioolkos** [comment] 2016-06-27 19:17
Hello @hbahn, have you been able to resolve this issue (aka Problem 2)?
Thank you very much!

**Comment by dergraf** [comment] 2016-07-15 06:58
Let's close this for the moment. Please feel free to reopen it.

**Closed by dergraf** 2016-07-15 06:58 UTC
